/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = 
  {4, 4, 0, 4, 7, 9, 10, 0,
  1, 2, 3, 1, 2, 3, 2, 3,
  3};
static const casadi_int casadi_s3[17] = 
  {4, 4, 0, 1, 3, 6, 10, 0,
  0, 1, 0, 1, 2, 0, 1, 2,
  3};
static const casadi_int casadi_s4[3] = {11, 1, 1};
static const casadi_int casadi_s5[3] = {4, 1, 1};
static const casadi_int casadi_s6[3] = {15, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c1[16] = 
  {1., 0., 0., 0., 0., 1., 0., 0.,
  0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_expl_ode_fun:(i0[11],i1[4],i2[15])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+11, *w01=w+22, *w02=w+43, *w03=w+52, w04, w05, w06, w07, *w08=w+65, w09, w10;
  casadi_real *w11=w+71, w12, w13, *w14=w+82, *w15=w+91, *w16=w+94, *w17=w+127, *w18=w+160, *w19=w+172, *w20=w+176, *w21=w+180, *w22=w+184;
  casadi_real *w23=w+200, *w24=w+216, *w25=w+260, *w26=w+304, *w27=w+332, *w28=w+348, *w29=w+364, *w30=w+380, *w31=w+424, *w32=w+545, w33, w34;
  casadi_real w35, *w36=w+669, *w37=w+680;
  const casadi_real *cr, *cs, *ct, *ss, *wr02, *wr23;
  /* #0: @0 = zeros(11x1) */
  casadi_clear(w00, 11);
  /* #1: @1 = zeros(3x7) */
  casadi_clear(w01, 21);
  /* #2: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr02 = casadi_c0;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w03, 9);
  /* #4: @4 = input[0][3] */
  w04 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = input[0][4] */
  w05 = arg[0] ? arg[0][4] : 0;
  /* #6: @6 = input[0][5] */
  w06 = arg[0] ? arg[0][5] : 0;
  /* #7: @7 = input[0][6] */
  w07 = arg[0] ? arg[0][6] : 0;
  /* #8: @8 = vertcat(@4, @5, @6, @7) */
  rr=w08;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  /* #9: @9 = ||@8||_F */
  w09 = casadi_norm_2(4, w08);
  /* #10: @8 = (@8/@9) */
  for (i=0, rr=w08; i<4; ++i) (*rr++) /= w09;
  /* #11: @9 = @8[3] */
  for (rr=(&w09), cs=w08+3; cs!=w08+4; cs+=1) *rr++ = *cs;
  /* #12: @10 = (-@9) */
  w10 = (- w09 );
  /* #13: @11 = @3; (@11[3] = @10) */
  casadi_copy(w03, 9, w11);
  for (rr=w11+3, cs=(&w10); rr!=w11+4; rr+=1) *rr = *cs++;
  /* #14: @10 = @8[2] */
  for (rr=(&w10), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #15: (@11[6] = @10) */
  for (rr=w11+6, cs=(&w10); rr!=w11+7; rr+=1) *rr = *cs++;
  /* #16: @12 = @8[1] */
  for (rr=(&w12), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #17: @13 = (-@12) */
  w13 = (- w12 );
  /* #18: (@11[7] = @13) */
  for (rr=w11+7, cs=(&w13); rr!=w11+8; rr+=1) *rr = *cs++;
  /* #19: (@11[1] = @9) */
  for (rr=w11+1, cs=(&w09); rr!=w11+2; rr+=1) *rr = *cs++;
  /* #20: @10 = (-@10) */
  w10 = (- w10 );
  /* #21: (@11[2] = @10) */
  for (rr=w11+2, cs=(&w10); rr!=w11+3; rr+=1) *rr = *cs++;
  /* #22: (@11[5] = @12) */
  for (rr=w11+5, cs=(&w12); rr!=w11+6; rr+=1) *rr = *cs++;
  /* #23: @14 = (2.*@11) */
  for (i=0, rr=w14, cs=w11; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #24: @3 = mac(@14,@11,@3) */
  for (i=0, rr=w03; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w14+j, ct=w11+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #25: @2 = (@2+@3) */
  for (i=0, rr=w02, cr=wr02, cs=w03; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #26: @12 = @8[0] */
  for (rr=(&w12), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #27: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #28: @11 = (@12*@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) (*rr++)  = (w12*(*cs++));
  /* #29: @2 = (@2+@11) */
  for (i=0, rr=w02, cs=w11; i<9; ++i) (*rr++) += (*cs++);
  /* #30: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #31: @16 = horzcat(@1, @2, @15) */
  rr=w16;
  for (i=0, cs=w01; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #32: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #33: @18 = zeros(4x3) */
  casadi_clear(w18, 12);
  /* #34: @12 = 0.5 */
  w12 = 5.0000000000000000e-01;
  /* #35: @10 = 0 */
  w10 = 0.;
  /* #36: @9 = input[0][10] */
  w09 = arg[0] ? arg[0][10] : 0;
  /* #37: @13 = (-@9) */
  w13 = (- w09 );
  /* #38: @8 = horzcat(@10, @10, @10, @13) */
  rr=w08;
  *rr++ = w10;
  *rr++ = w10;
  *rr++ = w10;
  *rr++ = w13;
  /* #39: @8 = @8' */
  /* #40: @19 = horzcat(@10, @10, @9, @10) */
  rr=w19;
  *rr++ = w10;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w10;
  /* #41: @19 = @19' */
  /* #42: @20 = horzcat(@10, @13, @10, @10) */
  rr=w20;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w10;
  /* #43: @20 = @20' */
  /* #44: @21 = horzcat(@9, @10, @10, @10) */
  rr=w21;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w10;
  *rr++ = w10;
  /* #45: @21 = @21' */
  /* #46: @22 = horzcat(@8, @19, @20, @21) */
  rr=w22;
  for (i=0, cs=w08; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  /* #47: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #48: @23 = (@12*@23) */
  for (i=0, rr=w23, cs=w23; i<16; ++i) (*rr++)  = (w12*(*cs++));
  /* #49: @22 = zeros(4x4) */
  casadi_clear(w22, 16);
  /* #50: @24 = horzcat(@18, @23, @22) */
  rr=w24;
  for (i=0, cs=w18; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  /* #51: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #52: @26 = zeros(4x7) */
  casadi_clear(w26, 28);
  /* #53: @23 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  wr23 = casadi_c1;
  /* #54: @12 = 0.6756 */
  w12 = 6.7559999999999998e-01;
  /* #55: @27 = @22; (@27[0] = @12) */
  casadi_copy(w22, 16, w27);
  for (rr=w27+0, cs=(&w12); rr!=w27+1; rr+=1) *rr = *cs++;
  /* #56: (@27[4] = @10) */
  for (rr=w27+4, cs=(&w10); rr!=w27+5; rr+=1) *rr = *cs++;
  /* #57: (@27[8] = @10) */
  for (rr=w27+8, cs=(&w10); rr!=w27+9; rr+=1) *rr = *cs++;
  /* #58: (@27[12] = @10) */
  for (rr=w27+12, cs=(&w10); rr!=w27+13; rr+=1) *rr = *cs++;
  /* #59: (@27[1] = @10) */
  for (rr=w27+1, cs=(&w10); rr!=w27+2; rr+=1) *rr = *cs++;
  /* #60: @12 = 0.6344 */
  w12 = 6.3439999999999996e-01;
  /* #61: (@27[5] = @12) */
  for (rr=w27+5, cs=(&w12); rr!=w27+6; rr+=1) *rr = *cs++;
  /* #62: (@27[9] = @10) */
  for (rr=w27+9, cs=(&w10); rr!=w27+10; rr+=1) *rr = *cs++;
  /* #63: (@27[13] = @10) */
  for (rr=w27+13, cs=(&w10); rr!=w27+14; rr+=1) *rr = *cs++;
  /* #64: (@27[2] = @10) */
  for (rr=w27+2, cs=(&w10); rr!=w27+3; rr+=1) *rr = *cs++;
  /* #65: (@27[6] = @10) */
  for (rr=w27+6, cs=(&w10); rr!=w27+7; rr+=1) *rr = *cs++;
  /* #66: @12 = 0.408 */
  w12 = 4.0799999999999997e-01;
  /* #67: (@27[10] = @12) */
  for (rr=w27+10, cs=(&w12); rr!=w27+11; rr+=1) *rr = *cs++;
  /* #68: (@27[14] = @10) */
  for (rr=w27+14, cs=(&w10); rr!=w27+15; rr+=1) *rr = *cs++;
  /* #69: (@27[3] = @10) */
  for (rr=w27+3, cs=(&w10); rr!=w27+4; rr+=1) *rr = *cs++;
  /* #70: (@27[7] = @10) */
  for (rr=w27+7, cs=(&w10); rr!=w27+8; rr+=1) *rr = *cs++;
  /* #71: (@27[11] = @10) */
  for (rr=w27+11, cs=(&w10); rr!=w27+12; rr+=1) *rr = *cs++;
  /* #72: @12 = 0.2953 */
  w12 = 2.9530000000000001e-01;
  /* #73: (@27[15] = @12) */
  for (rr=w27+15, cs=(&w12); rr!=w27+16; rr+=1) *rr = *cs++;
  /* #74: @28 = (@27\@23) */
  rr = w28;
  ss = w27;
  casadi_copy(wr23, 16, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #75: @12 = 0.5941 */
  w12 = 5.9409999999999996e-01;
  /* #76: @29 = @22; (@29[0] = @12) */
  casadi_copy(w22, 16, w29);
  for (rr=w29+0, cs=(&w12); rr!=w29+1; rr+=1) *rr = *cs++;
  /* #77: @12 = -0.8109 */
  w12 = -8.1089999999999995e-01;
  /* #78: @12 = (@12*@9) */
  w12 *= w09;
  /* #79: (@29[4] = @12) */
  for (rr=w29+4, cs=(&w12); rr!=w29+5; rr+=1) *rr = *cs++;
  /* #80: (@29[8] = @10) */
  for (rr=w29+8, cs=(&w10); rr!=w29+9; rr+=1) *rr = *cs++;
  /* #81: (@29[12] = @10) */
  for (rr=w29+12, cs=(&w10); rr!=w29+13; rr+=1) *rr = *cs++;
  /* #82: @12 = 0.3984 */
  w12 = 3.9839999999999998e-01;
  /* #83: @12 = (@12*@9) */
  w12 *= w09;
  /* #84: (@29[1] = @12) */
  for (rr=w29+1, cs=(&w12); rr!=w29+2; rr+=1) *rr = *cs++;
  /* #85: @12 = 0.704 */
  w12 = 7.0399999999999996e-01;
  /* #86: (@29[5] = @12) */
  for (rr=w29+5, cs=(&w12); rr!=w29+6; rr+=1) *rr = *cs++;
  /* #87: (@29[9] = @10) */
  for (rr=w29+9, cs=(&w10); rr!=w29+10; rr+=1) *rr = *cs++;
  /* #88: (@29[13] = @10) */
  for (rr=w29+13, cs=(&w10); rr!=w29+14; rr+=1) *rr = *cs++;
  /* #89: (@29[2] = @10) */
  for (rr=w29+2, cs=(&w10); rr!=w29+3; rr+=1) *rr = *cs++;
  /* #90: (@29[6] = @10) */
  for (rr=w29+6, cs=(&w10); rr!=w29+7; rr+=1) *rr = *cs++;
  /* #91: @12 = 0.9365 */
  w12 = 9.3650000000000000e-01;
  /* #92: (@29[10] = @12) */
  for (rr=w29+10, cs=(&w12); rr!=w29+11; rr+=1) *rr = *cs++;
  /* #93: (@29[14] = @10) */
  for (rr=w29+14, cs=(&w10); rr!=w29+15; rr+=1) *rr = *cs++;
  /* #94: (@29[3] = @10) */
  for (rr=w29+3, cs=(&w10); rr!=w29+4; rr+=1) *rr = *cs++;
  /* #95: (@29[7] = @10) */
  for (rr=w29+7, cs=(&w10); rr!=w29+8; rr+=1) *rr = *cs++;
  /* #96: (@29[11] = @10) */
  for (rr=w29+11, cs=(&w10); rr!=w29+12; rr+=1) *rr = *cs++;
  /* #97: @10 = 0.9752 */
  w10 = 9.7519999999999996e-01;
  /* #98: (@29[15] = @10) */
  for (rr=w29+15, cs=(&w10); rr!=w29+16; rr+=1) *rr = *cs++;
  /* #99: @22 = mac(@28,@29,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w28+j, ct=w29+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #100: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<16; ++i) *rr++ = (- *cs++ );
  /* #101: @24 = horzcat(@26, @22) */
  rr=w24;
  for (i=0, cs=w26; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  /* #102: @30 = @24' */
  for (i=0, rr=w30, cs=w24; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #103: @31 = horzcat(@17, @25, @30) */
  rr=w31;
  for (i=0, cs=w17; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<44; ++i) *rr++ = *cs++;
  /* #104: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #105: @10 = input[0][0] */
  w10 = arg[0] ? arg[0][0] : 0;
  /* #106: @12 = input[0][1] */
  w12 = arg[0] ? arg[0][1] : 0;
  /* #107: @13 = input[0][2] */
  w13 = arg[0] ? arg[0][2] : 0;
  /* #108: @33 = input[0][7] */
  w33 = arg[0] ? arg[0][7] : 0;
  /* #109: @34 = input[0][8] */
  w34 = arg[0] ? arg[0][8] : 0;
  /* #110: @35 = input[0][9] */
  w35 = arg[0] ? arg[0][9] : 0;
  /* #111: @36 = vertcat(@10, @12, @13, @4, @5, @6, @7, @33, @34, @35, @9) */
  rr=w36;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w09;
  /* #112: @37 = mac(@32,@36,@0) */
  casadi_copy(w00, 11, w37);
  for (i=0, rr=w37; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, cs=w32+j, ct=w36+i*11; k<11; ++k) *rr += cs[k*11]**ct++;
  /* #113: @23 = (@27\@23) */
  rr = w23;
  ss = w27;
  casadi_copy(wr23, 16, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #114: @27 = @23' */
  for (i=0, rr=w27, cs=w23; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #115: @25 = horzcat(@26, @27) */
  rr=w25;
  for (i=0, cs=w26; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<16; ++i) *rr++ = *cs++;
  /* #116: @30 = @25' */
  for (i=0, rr=w30, cs=w25; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #117: @10 = input[1][0] */
  w10 = arg[1] ? arg[1][0] : 0;
  /* #118: @12 = input[1][1] */
  w12 = arg[1] ? arg[1][1] : 0;
  /* #119: @13 = input[1][2] */
  w13 = arg[1] ? arg[1][2] : 0;
  /* #120: @4 = input[1][3] */
  w04 = arg[1] ? arg[1][3] : 0;
  /* #121: @8 = vertcat(@10, @12, @13, @4) */
  rr=w08;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w04;
  /* #122: @0 = mac(@30,@8,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, cs=w30+j, ct=w08+i*4; k<4; ++k) *rr += cs[k*11]**ct++;
  /* #123: @37 = (@37+@0) */
  for (i=0, rr=w37, cs=w00; i<11; ++i) (*rr++) += (*cs++);
  /* #124: output[0][0] = @37 */
  casadi_copy(w37, 11, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 691;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 691*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
