/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = 
  {4, 4, 0, 4, 7, 9, 10, 0,
  1, 2, 3, 1, 2, 3, 2, 3,
  3};
static const casadi_int casadi_s3[17] = 
  {4, 4, 0, 1, 3, 6, 10, 0,
  0, 1, 0, 1, 2, 0, 1, 2,
  3};
static const casadi_int casadi_s4[3] = {11, 1, 1};
static const casadi_int casadi_s5[3] = {4, 1, 1};
static const casadi_int casadi_s6[3] = {15, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c1[16] = 
  {1., 0., 0., 0., 0., 1., 0., 0.,
  0., 0., 1., 0., 0., 0., 0., 1.};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* Drone_ode_expl_vde_adj:(i0[11],i1[11],i2[4],i3[15])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+11, *w01=w+22, *w02=w+43, *w03=w+52, w04, w05, w06, w07, *w08=w+65, w09, *w10=w+70;
  casadi_real w11, w12, *w13=w+76, w14, w15, *w16=w+87, *w17=w+96, *w18=w+105, *w19=w+108, *w20=w+141, *w21=w+174, w22;
  casadi_real *w23=w+187, *w24=w+191, *w25=w+195, *w26=w+199, *w27=w+203, *w28=w+219, *w29=w+235, *w30=w+279, *w31=w+323, *w32=w+351, *w33=w+367, *w34=w+383;
  casadi_real w35, w36, *w37=w+401, *w38=w+417, *w39=w+461, w41, w42, w43, w44, w45, w46, w47;
  casadi_real w48, w49, w50, w51, w52, w53, *w54=w+606, *w55=w+727;
  const casadi_real *cr, *cs, *ct, *ss, *wr02, *wr28, *wr40;
  /* #0: @0 = zeros(11x1) */
  casadi_clear(w00, 11);
  /* #1: @1 = zeros(3x7) */
  casadi_clear(w01, 21);
  /* #2: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr02 = casadi_c0;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w03, 9);
  /* #4: @4 = input[0][3] */
  w04 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = input[0][4] */
  w05 = arg[0] ? arg[0][4] : 0;
  /* #6: @6 = input[0][5] */
  w06 = arg[0] ? arg[0][5] : 0;
  /* #7: @7 = input[0][6] */
  w07 = arg[0] ? arg[0][6] : 0;
  /* #8: @8 = vertcat(@4, @5, @6, @7) */
  rr=w08;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  /* #9: @9 = ||@8||_F */
  w09 = casadi_norm_2(4, w08);
  /* #10: @10 = (@8/@9) */
  for (i=0, rr=w10, cr=w08; i<4; ++i) (*rr++)  = ((*cr++)/w09);
  /* #11: @11 = @10[3] */
  for (rr=(&w11), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #12: @12 = (-@11) */
  w12 = (- w11 );
  /* #13: @13 = @3; (@13[3] = @12) */
  casadi_copy(w03, 9, w13);
  for (rr=w13+3, cs=(&w12); rr!=w13+4; rr+=1) *rr = *cs++;
  /* #14: @12 = @10[2] */
  for (rr=(&w12), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #15: (@13[6] = @12) */
  for (rr=w13+6, cs=(&w12); rr!=w13+7; rr+=1) *rr = *cs++;
  /* #16: @14 = @10[1] */
  for (rr=(&w14), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #17: @15 = (-@14) */
  w15 = (- w14 );
  /* #18: (@13[7] = @15) */
  for (rr=w13+7, cs=(&w15); rr!=w13+8; rr+=1) *rr = *cs++;
  /* #19: (@13[1] = @11) */
  for (rr=w13+1, cs=(&w11); rr!=w13+2; rr+=1) *rr = *cs++;
  /* #20: @12 = (-@12) */
  w12 = (- w12 );
  /* #21: (@13[2] = @12) */
  for (rr=w13+2, cs=(&w12); rr!=w13+3; rr+=1) *rr = *cs++;
  /* #22: (@13[5] = @14) */
  for (rr=w13+5, cs=(&w14); rr!=w13+6; rr+=1) *rr = *cs++;
  /* #23: @16 = (2.*@13) */
  for (i=0, rr=w16, cs=w13; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #24: @17 = mac(@16,@13,@3) */
  casadi_copy(w03, 9, w17);
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w16+j, ct=w13+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #25: @2 = (@2+@17) */
  for (i=0, rr=w02, cr=wr02, cs=w17; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #26: @14 = @10[0] */
  for (rr=(&w14), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #27: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #28: @17 = (@14*@13) */
  for (i=0, rr=w17, cs=w13; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #29: @2 = (@2+@17) */
  for (i=0, rr=w02, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #30: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #31: @19 = horzcat(@1, @2, @18) */
  rr=w19;
  for (i=0, cs=w01; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w02; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #32: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #33: @21 = zeros(4x3) */
  casadi_clear(w21, 12);
  /* #34: @12 = 0.5 */
  w12 = 5.0000000000000000e-01;
  /* #35: @11 = 0 */
  w11 = 0.;
  /* #36: @15 = input[0][10] */
  w15 = arg[0] ? arg[0][10] : 0;
  /* #37: @22 = (-@15) */
  w22 = (- w15 );
  /* #38: @23 = horzcat(@11, @11, @11, @22) */
  rr=w23;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w22;
  /* #39: @23 = @23' */
  /* #40: @24 = horzcat(@11, @11, @15, @11) */
  rr=w24;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w15;
  *rr++ = w11;
  /* #41: @24 = @24' */
  /* #42: @25 = horzcat(@11, @22, @11, @11) */
  rr=w25;
  *rr++ = w11;
  *rr++ = w22;
  *rr++ = w11;
  *rr++ = w11;
  /* #43: @25 = @25' */
  /* #44: @26 = horzcat(@15, @11, @11, @11) */
  rr=w26;
  *rr++ = w15;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w11;
  /* #45: @26 = @26' */
  /* #46: @27 = horzcat(@23, @24, @25, @26) */
  rr=w27;
  for (i=0, cs=w23; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  /* #47: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #48: @28 = (@12*@28) */
  for (i=0, rr=w28, cs=w28; i<16; ++i) (*rr++)  = (w12*(*cs++));
  /* #49: @27 = zeros(4x4) */
  casadi_clear(w27, 16);
  /* #50: @29 = horzcat(@21, @28, @27) */
  rr=w29;
  for (i=0, cs=w21; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<16; ++i) *rr++ = *cs++;
  /* #51: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #52: @31 = zeros(4x7) */
  casadi_clear(w31, 28);
  /* #53: @28 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  wr28 = casadi_c1;
  /* #54: @22 = 0.6756 */
  w22 = 6.7559999999999998e-01;
  /* #55: @32 = @27; (@32[0] = @22) */
  casadi_copy(w27, 16, w32);
  for (rr=w32+0, cs=(&w22); rr!=w32+1; rr+=1) *rr = *cs++;
  /* #56: (@32[4] = @11) */
  for (rr=w32+4, cs=(&w11); rr!=w32+5; rr+=1) *rr = *cs++;
  /* #57: (@32[8] = @11) */
  for (rr=w32+8, cs=(&w11); rr!=w32+9; rr+=1) *rr = *cs++;
  /* #58: (@32[12] = @11) */
  for (rr=w32+12, cs=(&w11); rr!=w32+13; rr+=1) *rr = *cs++;
  /* #59: (@32[1] = @11) */
  for (rr=w32+1, cs=(&w11); rr!=w32+2; rr+=1) *rr = *cs++;
  /* #60: @22 = 0.6344 */
  w22 = 6.3439999999999996e-01;
  /* #61: (@32[5] = @22) */
  for (rr=w32+5, cs=(&w22); rr!=w32+6; rr+=1) *rr = *cs++;
  /* #62: (@32[9] = @11) */
  for (rr=w32+9, cs=(&w11); rr!=w32+10; rr+=1) *rr = *cs++;
  /* #63: (@32[13] = @11) */
  for (rr=w32+13, cs=(&w11); rr!=w32+14; rr+=1) *rr = *cs++;
  /* #64: (@32[2] = @11) */
  for (rr=w32+2, cs=(&w11); rr!=w32+3; rr+=1) *rr = *cs++;
  /* #65: (@32[6] = @11) */
  for (rr=w32+6, cs=(&w11); rr!=w32+7; rr+=1) *rr = *cs++;
  /* #66: @22 = 0.408 */
  w22 = 4.0799999999999997e-01;
  /* #67: (@32[10] = @22) */
  for (rr=w32+10, cs=(&w22); rr!=w32+11; rr+=1) *rr = *cs++;
  /* #68: (@32[14] = @11) */
  for (rr=w32+14, cs=(&w11); rr!=w32+15; rr+=1) *rr = *cs++;
  /* #69: (@32[3] = @11) */
  for (rr=w32+3, cs=(&w11); rr!=w32+4; rr+=1) *rr = *cs++;
  /* #70: (@32[7] = @11) */
  for (rr=w32+7, cs=(&w11); rr!=w32+8; rr+=1) *rr = *cs++;
  /* #71: (@32[11] = @11) */
  for (rr=w32+11, cs=(&w11); rr!=w32+12; rr+=1) *rr = *cs++;
  /* #72: @22 = 0.2953 */
  w22 = 2.9530000000000001e-01;
  /* #73: (@32[15] = @22) */
  for (rr=w32+15, cs=(&w22); rr!=w32+16; rr+=1) *rr = *cs++;
  /* #74: @33 = (@32\@28) */
  rr = w33;
  ss = w32;
  casadi_copy(wr28, 16, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #75: @22 = 0.5941 */
  w22 = 5.9409999999999996e-01;
  /* #76: @34 = @27; (@34[0] = @22) */
  casadi_copy(w27, 16, w34);
  for (rr=w34+0, cs=(&w22); rr!=w34+1; rr+=1) *rr = *cs++;
  /* #77: @22 = -0.8109 */
  w22 = -8.1089999999999995e-01;
  /* #78: @35 = (@22*@15) */
  w35  = (w22*w15);
  /* #79: (@34[4] = @35) */
  for (rr=w34+4, cs=(&w35); rr!=w34+5; rr+=1) *rr = *cs++;
  /* #80: (@34[8] = @11) */
  for (rr=w34+8, cs=(&w11); rr!=w34+9; rr+=1) *rr = *cs++;
  /* #81: (@34[12] = @11) */
  for (rr=w34+12, cs=(&w11); rr!=w34+13; rr+=1) *rr = *cs++;
  /* #82: @35 = 0.3984 */
  w35 = 3.9839999999999998e-01;
  /* #83: @36 = (@35*@15) */
  w36  = (w35*w15);
  /* #84: (@34[1] = @36) */
  for (rr=w34+1, cs=(&w36); rr!=w34+2; rr+=1) *rr = *cs++;
  /* #85: @36 = 0.704 */
  w36 = 7.0399999999999996e-01;
  /* #86: (@34[5] = @36) */
  for (rr=w34+5, cs=(&w36); rr!=w34+6; rr+=1) *rr = *cs++;
  /* #87: (@34[9] = @11) */
  for (rr=w34+9, cs=(&w11); rr!=w34+10; rr+=1) *rr = *cs++;
  /* #88: (@34[13] = @11) */
  for (rr=w34+13, cs=(&w11); rr!=w34+14; rr+=1) *rr = *cs++;
  /* #89: (@34[2] = @11) */
  for (rr=w34+2, cs=(&w11); rr!=w34+3; rr+=1) *rr = *cs++;
  /* #90: (@34[6] = @11) */
  for (rr=w34+6, cs=(&w11); rr!=w34+7; rr+=1) *rr = *cs++;
  /* #91: @36 = 0.9365 */
  w36 = 9.3650000000000000e-01;
  /* #92: (@34[10] = @36) */
  for (rr=w34+10, cs=(&w36); rr!=w34+11; rr+=1) *rr = *cs++;
  /* #93: (@34[14] = @11) */
  for (rr=w34+14, cs=(&w11); rr!=w34+15; rr+=1) *rr = *cs++;
  /* #94: (@34[3] = @11) */
  for (rr=w34+3, cs=(&w11); rr!=w34+4; rr+=1) *rr = *cs++;
  /* #95: (@34[7] = @11) */
  for (rr=w34+7, cs=(&w11); rr!=w34+8; rr+=1) *rr = *cs++;
  /* #96: (@34[11] = @11) */
  for (rr=w34+11, cs=(&w11); rr!=w34+12; rr+=1) *rr = *cs++;
  /* #97: @36 = 0.9752 */
  w36 = 9.7519999999999996e-01;
  /* #98: (@34[15] = @36) */
  for (rr=w34+15, cs=(&w36); rr!=w34+16; rr+=1) *rr = *cs++;
  /* #99: @37 = mac(@33,@34,@27) */
  casadi_copy(w27, 16, w37);
  for (i=0, rr=w37; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w33+j, ct=w34+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #100: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<16; ++i) *rr++ = (- *cs++ );
  /* #101: @29 = horzcat(@31, @37) */
  rr=w29;
  for (i=0, cs=w31; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<16; ++i) *rr++ = *cs++;
  /* #102: @38 = @29' */
  for (i=0, rr=w38, cs=w29; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #103: @39 = horzcat(@20, @30, @38) */
  rr=w39;
  for (i=0, cs=w20; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<44; ++i) *rr++ = *cs++;
  /* #104: @40 = input[1][0] */
  wr40 = arg[1] ? arg[1] : casadi_zeros;
  /* #105: @0 = mac(@39,@40,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, cs=w39+j, ct=wr40+i*11; k<11; ++k) *rr += cs[k*11]**ct++;
  /* #106: {@36, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50} = vertsplit(@0) */
  w36 = w00[0];
  w41 = w00[1];
  w42 = w00[2];
  w43 = w00[3];
  w44 = w00[4];
  w45 = w00[5];
  w46 = w00[6];
  w47 = w00[7];
  w48 = w00[8];
  w49 = w00[9];
  w50 = w00[10];
  /* #107: output[0][0] = @36 */
  if (res[0]) res[0][0] = w36;
  /* #108: output[0][1] = @41 */
  if (res[0]) res[0][1] = w41;
  /* #109: output[0][2] = @42 */
  if (res[0]) res[0][2] = w42;
  /* #110: @23 = zeros(4x1) */
  casadi_clear(w23, 4);
  /* #111: @39 = zeros(11x11) */
  casadi_clear(w39, 121);
  /* #112: @42 = input[0][0] */
  w42 = arg[0] ? arg[0][0] : 0;
  /* #113: @41 = input[0][1] */
  w41 = arg[0] ? arg[0][1] : 0;
  /* #114: @36 = input[0][2] */
  w36 = arg[0] ? arg[0][2] : 0;
  /* #115: @51 = input[0][7] */
  w51 = arg[0] ? arg[0][7] : 0;
  /* #116: @52 = input[0][8] */
  w52 = arg[0] ? arg[0][8] : 0;
  /* #117: @53 = input[0][9] */
  w53 = arg[0] ? arg[0][9] : 0;
  /* #118: @0 = vertcat(@42, @41, @36, @4, @5, @6, @7, @51, @52, @53, @15) */
  rr=w00;
  *rr++ = w42;
  *rr++ = w41;
  *rr++ = w36;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w15;
  /* #119: @0 = @0' */
  /* #120: @39 = mac(@40,@0,@39) */
  for (i=0, rr=w39; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, cs=wr40+j, ct=w00+i*1; k<1; ++k) *rr += cs[k*11]**ct++;
  /* #121: @54 = @39' */
  for (i=0, rr=w54, cs=w39; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #122: {@20, @30, @38} = horzsplit(@54) */
  casadi_copy(w54, 33, w20);
  casadi_copy(w54+33, 44, w30);
  casadi_copy(w54+77, 44, w38);
  /* #123: @19 = @20' */
  for (i=0, rr=w19, cs=w20; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #124: {NULL, @2, NULL} = horzsplit(@19) */
  casadi_copy(w19+21, 9, w02);
  /* #125: @42 = dot(@13, @2) */
  w42 = casadi_dot(9, w13, w02);
  /* #126: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #127: @24 = @23; (@24[0] += @42) */
  casadi_copy(w23, 4, w24);
  for (rr=w24+0, cs=(&w42); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #128: @17 = (@14*@2) */
  for (i=0, rr=w17, cs=w02; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #129: @55 = @16' */
  for (i=0, rr=w55, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #130: @16 = mac(@55,@2,@3) */
  casadi_copy(w03, 9, w16);
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w55+j, ct=w02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #131: @17 = (@17+@16) */
  for (i=0, rr=w17, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  /* #132: @16 = @13' */
  for (i=0, rr=w16, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #133: @3 = mac(@2,@16,@3) */
  for (i=0, rr=w03; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w02+j, ct=w16+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #134: @3 = (2.*@3) */
  for (i=0, rr=w03, cs=w03; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #135: @17 = (@17+@3) */
  for (i=0, rr=w17, cs=w03; i<9; ++i) (*rr++) += (*cs++);
  /* #136: @14 = @17[5] */
  for (rr=(&w14), cs=w17+5; cs!=w17+6; cs+=1) *rr++ = *cs;
  /* #137: (@24[1] += @14) */
  for (rr=w24+1, cs=(&w14); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #138: (@17[5] = @11) */
  for (rr=w17+5, cs=(&w11); rr!=w17+6; rr+=1) *rr = *cs++;
  /* #139: @14 = @17[2] */
  for (rr=(&w14), cs=w17+2; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #140: @14 = (-@14) */
  w14 = (- w14 );
  /* #141: (@24[2] += @14) */
  for (rr=w24+2, cs=(&w14); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #142: (@17[2] = @11) */
  for (rr=w17+2, cs=(&w11); rr!=w17+3; rr+=1) *rr = *cs++;
  /* #143: @14 = @17[1] */
  for (rr=(&w14), cs=w17+1; cs!=w17+2; cs+=1) *rr++ = *cs;
  /* #144: (@24[3] += @14) */
  for (rr=w24+3, cs=(&w14); rr!=w24+4; rr+=1) *rr += *cs++;
  /* #145: (@17[1] = @11) */
  for (rr=w17+1, cs=(&w11); rr!=w17+2; rr+=1) *rr = *cs++;
  /* #146: @14 = @17[7] */
  for (rr=(&w14), cs=w17+7; cs!=w17+8; cs+=1) *rr++ = *cs;
  /* #147: @14 = (-@14) */
  w14 = (- w14 );
  /* #148: (@24[1] += @14) */
  for (rr=w24+1, cs=(&w14); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #149: (@17[7] = @11) */
  for (rr=w17+7, cs=(&w11); rr!=w17+8; rr+=1) *rr = *cs++;
  /* #150: @14 = @17[6] */
  for (rr=(&w14), cs=w17+6; cs!=w17+7; cs+=1) *rr++ = *cs;
  /* #151: (@24[2] += @14) */
  for (rr=w24+2, cs=(&w14); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #152: (@17[6] = @11) */
  for (rr=w17+6, cs=(&w11); rr!=w17+7; rr+=1) *rr = *cs++;
  /* #153: @14 = @17[3] */
  for (rr=(&w14), cs=w17+3; cs!=w17+4; cs+=1) *rr++ = *cs;
  /* #154: @14 = (-@14) */
  w14 = (- w14 );
  /* #155: (@24[3] += @14) */
  for (rr=w24+3, cs=(&w14); rr!=w24+4; rr+=1) *rr += *cs++;
  /* #156: @25 = (@24/@9) */
  for (i=0, rr=w25, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)/w09);
  /* #157: @10 = (@10/@9) */
  for (i=0, rr=w10; i<4; ++i) (*rr++) /= w09;
  /* #158: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) *rr++ = (- *cs++ );
  /* #159: @14 = dot(@10, @24) */
  w14 = casadi_dot(4, w10, w24);
  /* #160: @14 = (@14/@9) */
  w14 /= w09;
  /* #161: @8 = (@14*@8) */
  for (i=0, rr=w08, cs=w08; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #162: @25 = (@25+@8) */
  for (i=0, rr=w25, cs=w08; i<4; ++i) (*rr++) += (*cs++);
  /* #163: {@14, @9, @42, @41} = vertsplit(@25) */
  w14 = w25[0];
  w09 = w25[1];
  w42 = w25[2];
  w41 = w25[3];
  /* #164: @43 = (@43+@14) */
  w43 += w14;
  /* #165: output[0][3] = @43 */
  if (res[0]) res[0][3] = w43;
  /* #166: @44 = (@44+@9) */
  w44 += w09;
  /* #167: output[0][4] = @44 */
  if (res[0]) res[0][4] = w44;
  /* #168: @45 = (@45+@42) */
  w45 += w42;
  /* #169: output[0][5] = @45 */
  if (res[0]) res[0][5] = w45;
  /* #170: @46 = (@46+@41) */
  w46 += w41;
  /* #171: output[0][6] = @46 */
  if (res[0]) res[0][6] = w46;
  /* #172: output[0][7] = @47 */
  if (res[0]) res[0][7] = w47;
  /* #173: output[0][8] = @48 */
  if (res[0]) res[0][8] = w48;
  /* #174: output[0][9] = @49 */
  if (res[0]) res[0][9] = w49;
  /* #175: @37 = @33' */
  for (i=0, rr=w37, cs=w33; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #176: @29 = @38' */
  for (i=0, rr=w29, cs=w38; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #177: {NULL, @33} = horzsplit(@29) */
  casadi_copy(w29+28, 16, w33);
  /* #178: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<16; ++i) *rr++ = (- *cs++ );
  /* #179: @27 = mac(@37,@33,@27) */
  for (i=0, rr=w27; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w37+j, ct=w33+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #180: (@27[15] = @11) */
  for (rr=w27+15, cs=(&w11); rr!=w27+16; rr+=1) *rr = *cs++;
  /* #181: (@27[11] = @11) */
  for (rr=w27+11, cs=(&w11); rr!=w27+12; rr+=1) *rr = *cs++;
  /* #182: (@27[7] = @11) */
  for (rr=w27+7, cs=(&w11); rr!=w27+8; rr+=1) *rr = *cs++;
  /* #183: (@27[3] = @11) */
  for (rr=w27+3, cs=(&w11); rr!=w27+4; rr+=1) *rr = *cs++;
  /* #184: (@27[14] = @11) */
  for (rr=w27+14, cs=(&w11); rr!=w27+15; rr+=1) *rr = *cs++;
  /* #185: (@27[10] = @11) */
  for (rr=w27+10, cs=(&w11); rr!=w27+11; rr+=1) *rr = *cs++;
  /* #186: (@27[6] = @11) */
  for (rr=w27+6, cs=(&w11); rr!=w27+7; rr+=1) *rr = *cs++;
  /* #187: (@27[2] = @11) */
  for (rr=w27+2, cs=(&w11); rr!=w27+3; rr+=1) *rr = *cs++;
  /* #188: (@27[13] = @11) */
  for (rr=w27+13, cs=(&w11); rr!=w27+14; rr+=1) *rr = *cs++;
  /* #189: (@27[9] = @11) */
  for (rr=w27+9, cs=(&w11); rr!=w27+10; rr+=1) *rr = *cs++;
  /* #190: (@27[5] = @11) */
  for (rr=w27+5, cs=(&w11); rr!=w27+6; rr+=1) *rr = *cs++;
  /* #191: @49 = @27[1] */
  for (rr=(&w49), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #192: @35 = (@35*@49) */
  w35 *= w49;
  /* #193: @50 = (@50+@35) */
  w50 += w35;
  /* #194: (@27[1] = @11) */
  for (rr=w27+1, cs=(&w11); rr!=w27+2; rr+=1) *rr = *cs++;
  /* #195: (@27[12] = @11) */
  for (rr=w27+12, cs=(&w11); rr!=w27+13; rr+=1) *rr = *cs++;
  /* #196: (@27[8] = @11) */
  for (rr=w27+8, cs=(&w11); rr!=w27+9; rr+=1) *rr = *cs++;
  /* #197: @11 = @27[4] */
  for (rr=(&w11), cs=w27+4; cs!=w27+5; cs+=1) *rr++ = *cs;
  /* #198: @22 = (@22*@11) */
  w22 *= w11;
  /* #199: @50 = (@50+@22) */
  w50 += w22;
  /* #200: @29 = @30' */
  for (i=0, rr=w29, cs=w30; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #201: {NULL, @27, NULL} = horzsplit(@29) */
  casadi_copy(w29+12, 16, w27);
  /* #202: @27 = (@12*@27) */
  for (i=0, rr=w27, cs=w27; i<16; ++i) (*rr++)  = (w12*(*cs++));
  /* #203: @37 = @27' */
  for (i=0, rr=w37, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #204: {@25, @8, @10, @24} = horzsplit(@37) */
  casadi_copy(w37, 4, w25);
  casadi_copy(w37+4, 4, w08);
  casadi_copy(w37+8, 4, w10);
  casadi_copy(w37+12, 4, w24);
  /* #205: @24 = @24' */
  /* #206: {@12, NULL, NULL, NULL} = horzsplit(@24) */
  w12 = w24[0];
  /* #207: @50 = (@50+@12) */
  w50 += w12;
  /* #208: @10 = @10' */
  /* #209: {NULL, @12, NULL, NULL} = horzsplit(@10) */
  w12 = w10[1];
  /* #210: @50 = (@50-@12) */
  w50 -= w12;
  /* #211: @8 = @8' */
  /* #212: {NULL, NULL, @12, NULL} = horzsplit(@8) */
  w12 = w08[2];
  /* #213: @50 = (@50+@12) */
  w50 += w12;
  /* #214: @25 = @25' */
  /* #215: {NULL, NULL, NULL, @12} = horzsplit(@25) */
  w12 = w25[3];
  /* #216: @50 = (@50-@12) */
  w50 -= w12;
  /* #217: output[0][10] = @50 */
  if (res[0]) res[0][10] = w50;
  /* #218: @28 = (@32\@28) */
  rr = w28;
  ss = w32;
  casadi_copy(wr28, 16, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #219: @32 = @28' */
  for (i=0, rr=w32, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #220: @29 = horzcat(@31, @32) */
  rr=w29;
  for (i=0, cs=w31; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<16; ++i) *rr++ = *cs++;
  /* #221: @23 = mac(@29,@40,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w29+j, ct=wr40+i*11; k<11; ++k) *rr += cs[k*4]**ct++;
  /* #222: {@50, @12, @22, @11} = vertsplit(@23) */
  w50 = w23[0];
  w12 = w23[1];
  w22 = w23[2];
  w11 = w23[3];
  /* #223: output[0][11] = @50 */
  if (res[0]) res[0][11] = w50;
  /* #224: output[0][12] = @12 */
  if (res[0]) res[0][12] = w12;
  /* #225: output[0][13] = @22 */
  if (res[0]) res[0][13] = w22;
  /* #226: output[0][14] = @11 */
  if (res[0]) res[0][14] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 736;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 12*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 736*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
