/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s2[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[7] = {0, 1, 2, 9, 10, 11, 12};
static const casadi_int casadi_s5[7] = {0, 3, 6, 9, 13, 17, 21};
static const casadi_int casadi_s6[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s7[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s8[7] = {3, 4, 5, 13, 14, 15, 16};
static const casadi_int casadi_s9[7] = {1, 4, 7, 10, 14, 18, 22};
static const casadi_int casadi_s10[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s11[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s12[7] = {6, 7, 8, 17, 18, 19, 20};
static const casadi_int casadi_s13[7] = {2, 5, 8, 11, 15, 19, 23};
static const casadi_int casadi_s14[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s15[39] = 
  {11, 11, 0, 3, 6, 9, 13, 17,
  21, 25, 25, 25, 25, 25, 0, 1,
  2, 0, 1, 2, 0, 1, 2, 3,
  4, 5, 6, 3, 4, 5, 6, 3,
  4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s16[3] = {11, 1, 1};
static const casadi_int casadi_s17[3] = {0, 1, 1};
static const casadi_int casadi_s18[3] = {15, 1, 1};
static const casadi_int casadi_s19[3] = {1, 1, 1};
static const casadi_int casadi_s20[3] = {0, 0, 1};
static const casadi_int casadi_s21[3] = {0, 11, 1};

/* Drone_ode_cost_ext_cost_e_fun_jac_hess:(i0[11],i1[0],i2[0],i3[15])->(o0,o1[11],o2[11x11,25nz],o3[],o4[0x11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w19=w+38, *w20=w+49, *w21=w+52, *w22=w+61;
  casadi_real *w23=w+64, *w24=w+68, *w25=w+72, *w26=w+76, *w27=w+80, *w28=w+83, *w29=w+86, *w30=w+89, *w31=w+92, *w32=w+101, *w33=w+104, *w34=w+108;
  casadi_real *w35=w+111, *w36=w+114, w37, w38, w39, w40, w41, *w42=w+123, w43, w44, w45, w46;
  casadi_real w47, w48, w49, *w50=w+141, *w51=w+166, *w53=w+172, *w54=w+176, *w55=w+180, *w56=w+184, *w57=w+187, *w58=w+190, w59;
  casadi_real *w60=w+194, w61, w62, w63, w64, w65, w66, w67, *w68=w+205, *w69=w+212, *w70=w+214, *w71=w+217;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #20: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #21: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #22: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #23: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #24: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #25: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #26: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #27: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #28: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #29: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #30: @19 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #31: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #32: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #34: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #35: @2 = 1.1 */
  w02 = 1.1000000000000001e+00;
  /* #36: (@21[0] = @2) */
  for (rr=w21+0, cs=(&w02); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #37: (@21[4] = @2) */
  for (rr=w21+4, cs=(&w02); rr!=w21+5; rr+=1) *rr = *cs++;
  /* #38: (@21[8] = @2) */
  for (rr=w21+8, cs=(&w02); rr!=w21+9; rr+=1) *rr = *cs++;
  /* #39: @22 = mac(@20,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@22,@18,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @10 = (-@10) */
  w10 = (- w10 );
  /* #42: @11 = (-@11) */
  w11 = (- w11 );
  /* #43: @12 = (-@12) */
  w12 = (- w12 );
  /* #44: @23 = vertcat(@9, @10, @11, @12) */
  rr=w23;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #45: @24 = @19[3:7] */
  for (rr=w24, cs=w19+3; cs!=w19+7; cs+=1) *rr++ = *cs;
  /* #46: @9 = ||@24||_F */
  w09 = casadi_norm_2(4, w24);
  /* #47: @23 = (@23/@9) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) /= w09;
  /* #48: @10 = @23[0] */
  for (rr=(&w10), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #49: @11 = (@10*@5) */
  w11  = (w10*w05);
  /* #50: @12 = @23[1] */
  for (rr=(&w12), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #51: @3 = (@12*@6) */
  w03  = (w12*w06);
  /* #52: @11 = (@11-@3) */
  w11 -= w03;
  /* #53: @3 = @23[2] */
  for (rr=(&w03), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #54: @4 = (@3*@7) */
  w04  = (w03*w07);
  /* #55: @11 = (@11-@4) */
  w11 -= w04;
  /* #56: @4 = @23[3] */
  for (rr=(&w04), cs=w23+3; cs!=w23+4; cs+=1) *rr++ = *cs;
  /* #57: @13 = (@4*@8) */
  w13  = (w04*w08);
  /* #58: @11 = (@11-@13) */
  w11 -= w13;
  /* #59: @13 = (@11<@0) */
  w13  = (w11<w00);
  /* #60: @14 = (@10*@6) */
  w14  = (w10*w06);
  /* #61: @15 = (@12*@5) */
  w15  = (w12*w05);
  /* #62: @14 = (@14+@15) */
  w14 += w15;
  /* #63: @15 = (@3*@8) */
  w15  = (w03*w08);
  /* #64: @14 = (@14+@15) */
  w14 += w15;
  /* #65: @15 = (@4*@7) */
  w15  = (w04*w07);
  /* #66: @14 = (@14-@15) */
  w14 -= w15;
  /* #67: @15 = (@10*@7) */
  w15  = (w10*w07);
  /* #68: @16 = (@12*@8) */
  w16  = (w12*w08);
  /* #69: @15 = (@15-@16) */
  w15 -= w16;
  /* #70: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #71: @15 = (@15+@16) */
  w15 += w16;
  /* #72: @16 = (@4*@6) */
  w16  = (w04*w06);
  /* #73: @15 = (@15+@16) */
  w15 += w16;
  /* #74: @10 = (@10*@8) */
  w10 *= w08;
  /* #75: @12 = (@12*@7) */
  w12 *= w07;
  /* #76: @10 = (@10+@12) */
  w10 += w12;
  /* #77: @3 = (@3*@6) */
  w03 *= w06;
  /* #78: @10 = (@10-@3) */
  w10 -= w03;
  /* #79: @4 = (@4*@5) */
  w04 *= w05;
  /* #80: @10 = (@10+@4) */
  w10 += w04;
  /* #81: @25 = vertcat(@11, @14, @15, @10) */
  rr=w25;
  *rr++ = w11;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w10;
  /* #82: @26 = (-@25) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) *rr++ = (- *cs++ );
  /* #83: @26 = (@13?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #84: @11 = (!@13) */
  w11 = (! w13 );
  /* #85: @25 = (@11?@25:0) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #86: @26 = (@26+@25) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #87: @18 = @26[1:4] */
  for (rr=w18, cs=w26+1; cs!=w26+4; cs+=1) *rr++ = *cs;
  /* #88: @27 = (2.*@18) */
  for (i=0, rr=w27, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #89: @14 = ||@18||_F */
  w14 = casadi_norm_2(3, w18);
  /* #90: @15 = @26[0] */
  for (rr=(&w15), cs=w26+0; cs!=w26+1; cs+=1) *rr++ = *cs;
  /* #91: @10 = atan2(@14,@15) */
  w10  = atan2(w14,w15);
  /* #92: @28 = (@27*@10) */
  for (i=0, rr=w28, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w10);
  /* #93: @28 = (@28/@14) */
  for (i=0, rr=w28; i<3; ++i) (*rr++) /= w14;
  /* #94: @29 = @28' */
  casadi_copy(w28, 3, w29);
  /* #95: @30 = mac(@29,@21,@1) */
  casadi_copy(w01, 3, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #96: @0 = mac(@30,@28,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #97: @2 = (@2+@0) */
  w02 += w00;
  /* #98: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #99: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #100: @23 = (@23/@9) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) /= w09;
  /* #101: @26 = (-@23) */
  for (i=0, rr=w26, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #102: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #103: @2 = sq(@14) */
  w02 = casadi_sq( w14 );
  /* #104: @0 = sq(@15) */
  w00 = casadi_sq( w15 );
  /* #105: @2 = (@2+@0) */
  w02 += w00;
  /* #106: @0 = (@14/@2) */
  w00  = (w14/w02);
  /* #107: @30 = @30' */
  /* #108: @31 = @21' */
  for (i=0, rr=w31, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #109: @32 = mac(@29,@31,@1) */
  casadi_copy(w01, 3, w32);
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #110: @32 = @32' */
  /* #111: @30 = (@30+@32) */
  for (i=0, rr=w30, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #112: @32 = (@30/@14) */
  for (i=0, rr=w32, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #113: @4 = dot(@27, @32) */
  w04 = casadi_dot(3, w27, w32);
  /* #114: @3 = (@0*@4) */
  w03  = (w00*w04);
  /* #115: @3 = (-@3) */
  w03 = (- w03 );
  /* #116: @33 = @25; (@33[0] += @3) */
  casadi_copy(w25, 4, w33);
  for (rr=w33+0, cs=(&w03); rr!=w33+1; rr+=1) *rr += *cs++;
  /* #117: @28 = (@28/@14) */
  for (i=0, rr=w28; i<3; ++i) (*rr++) /= w14;
  /* #118: @29 = (-@28) */
  for (i=0, rr=w29, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #119: @3 = dot(@29, @30) */
  w03 = casadi_dot(3, w29, w30);
  /* #120: @12 = (@15/@2) */
  w12  = (w15/w02);
  /* #121: @16 = (@12*@4) */
  w16  = (w12*w04);
  /* #122: @3 = (@3+@16) */
  w03 += w16;
  /* #123: @3 = (@3/@14) */
  w03 /= w14;
  /* #124: @34 = (@3*@18) */
  for (i=0, rr=w34, cs=w18; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #125: @35 = (@10*@32) */
  for (i=0, rr=w35, cs=w32; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #126: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #127: @34 = (@34+@35) */
  for (i=0, rr=w34, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #128: (@33[1:4] += @34) */
  for (rr=w33+1, cs=w34; rr!=w33+4; rr+=1) *rr += *cs++;
  /* #129: @36 = (@11?@33:0) */
  for (i=0, rr=w36, cs=w33; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #130: @33 = (-@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) *rr++ = (- *cs++ );
  /* #131: @33 = (@13?@33:0) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #132: @36 = (@36+@33) */
  for (i=0, rr=w36, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #133: {@16, @37, @38, @39} = vertsplit(@36) */
  w16 = w36[0];
  w37 = w36[1];
  w38 = w36[2];
  w39 = w36[3];
  /* #134: @40 = (@5*@39) */
  w40  = (w05*w39);
  /* #135: @41 = (@6*@38) */
  w41  = (w06*w38);
  /* #136: @40 = (@40+@41) */
  w40 += w41;
  /* #137: @41 = (@7*@37) */
  w41  = (w07*w37);
  /* #138: @40 = (@40-@41) */
  w40 -= w41;
  /* #139: @41 = (@8*@16) */
  w41  = (w08*w16);
  /* #140: @40 = (@40-@41) */
  w40 -= w41;
  /* #141: @36 = @25; (@36[3] += @40) */
  casadi_copy(w25, 4, w36);
  for (rr=w36+3, cs=(&w40); rr!=w36+4; rr+=1) *rr += *cs++;
  /* #142: @40 = (@5*@38) */
  w40  = (w05*w38);
  /* #143: @41 = (@6*@39) */
  w41  = (w06*w39);
  /* #144: @40 = (@40-@41) */
  w40 -= w41;
  /* #145: @41 = (@8*@37) */
  w41  = (w08*w37);
  /* #146: @40 = (@40+@41) */
  w40 += w41;
  /* #147: @41 = (@7*@16) */
  w41  = (w07*w16);
  /* #148: @40 = (@40-@41) */
  w40 -= w41;
  /* #149: (@36[2] += @40) */
  for (rr=w36+2, cs=(&w40); rr!=w36+3; rr+=1) *rr += *cs++;
  /* #150: @40 = (@7*@39) */
  w40  = (w07*w39);
  /* #151: @41 = (@8*@38) */
  w41  = (w08*w38);
  /* #152: @40 = (@40-@41) */
  w40 -= w41;
  /* #153: @41 = (@5*@37) */
  w41  = (w05*w37);
  /* #154: @40 = (@40+@41) */
  w40 += w41;
  /* #155: @41 = (@6*@16) */
  w41  = (w06*w16);
  /* #156: @40 = (@40-@41) */
  w40 -= w41;
  /* #157: (@36[1] += @40) */
  for (rr=w36+1, cs=(&w40); rr!=w36+2; rr+=1) *rr += *cs++;
  /* #158: @39 = (@8*@39) */
  w39  = (w08*w39);
  /* #159: @38 = (@7*@38) */
  w38  = (w07*w38);
  /* #160: @39 = (@39+@38) */
  w39 += w38;
  /* #161: @37 = (@6*@37) */
  w37  = (w06*w37);
  /* #162: @39 = (@39+@37) */
  w39 += w37;
  /* #163: @16 = (@5*@16) */
  w16  = (w05*w16);
  /* #164: @39 = (@39+@16) */
  w39 += w16;
  /* #165: (@36[0] += @39) */
  for (rr=w36+0, cs=(&w39); rr!=w36+1; rr+=1) *rr += *cs++;
  /* #166: @39 = dot(@26, @36) */
  w39 = casadi_dot(4, w26, w36);
  /* #167: @39 = (@39/@9) */
  w39 /= w09;
  /* #168: @33 = (@39*@24) */
  for (i=0, rr=w33, cs=w24; i<4; ++i) (*rr++)  = (w39*(*cs++));
  /* #169: @42 = @19; (@42[3:7] += @33) */
  casadi_copy(w19, 11, w42);
  for (rr=w42+3, cs=w33; rr!=w42+7; rr+=1) *rr += *cs++;
  /* #170: @22 = @22' */
  /* #171: @34 = mac(@20,@31,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #172: @34 = @34' */
  /* #173: @22 = (@22+@34) */
  for (i=0, rr=w22, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #174: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #175: (@42[:3] += @22) */
  for (rr=w42+0, cs=w22; rr!=w42+3; rr+=1) *rr += *cs++;
  /* #176: {@16, @37, @38, @40, @41, @43, @44, @45, @46, @47, @48} = vertsplit(@42) */
  w16 = w42[0];
  w37 = w42[1];
  w38 = w42[2];
  w40 = w42[3];
  w41 = w42[4];
  w43 = w42[5];
  w44 = w42[6];
  w45 = w42[7];
  w46 = w42[8];
  w47 = w42[9];
  w48 = w42[10];
  /* #177: output[1][0] = @16 */
  if (res[1]) res[1][0] = w16;
  /* #178: output[1][1] = @37 */
  if (res[1]) res[1][1] = w37;
  /* #179: output[1][2] = @38 */
  if (res[1]) res[1][2] = w38;
  /* #180: @33 = (@36/@9) */
  for (i=0, rr=w33, cr=w36; i<4; ++i) (*rr++)  = ((*cr++)/w09);
  /* #181: {@38, @37, @16, @49} = vertsplit(@33) */
  w38 = w33[0];
  w37 = w33[1];
  w16 = w33[2];
  w49 = w33[3];
  /* #182: @38 = (@38+@40) */
  w38 += w40;
  /* #183: output[1][3] = @38 */
  if (res[1]) res[1][3] = w38;
  /* #184: @41 = (@41-@37) */
  w41 -= w37;
  /* #185: output[1][4] = @41 */
  if (res[1]) res[1][4] = w41;
  /* #186: @43 = (@43-@16) */
  w43 -= w16;
  /* #187: output[1][5] = @43 */
  if (res[1]) res[1][5] = w43;
  /* #188: @44 = (@44-@49) */
  w44 -= w49;
  /* #189: output[1][6] = @44 */
  if (res[1]) res[1][6] = w44;
  /* #190: output[1][7] = @45 */
  if (res[1]) res[1][7] = w45;
  /* #191: output[1][8] = @46 */
  if (res[1]) res[1][8] = w46;
  /* #192: output[1][9] = @47 */
  if (res[1]) res[1][9] = w47;
  /* #193: output[1][10] = @48 */
  if (res[1]) res[1][10] = w48;
  /* #194: @50 = zeros(11x11,25nz) */
  casadi_clear(w50, 25);
  /* #195: @51 = ones(11x1,6nz) */
  casadi_fill(w51, 6, 1.);
  /* #196: {@48, NULL, NULL, @47, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@51) */
  w48 = w51[0];
  w47 = w51[1];
  /* #197: @52 = 00 */
  /* #198: @46 = vertcat(@47, @52, @52, @52) */
  rr=(&w46);
  *rr++ = w47;
  /* #199: @46 = (@46/@9) */
  w46 /= w09;
  /* #200: @53 = dense(@46) */
  casadi_densify((&w46), casadi_s0, w53, 0);
  /* #201: @46 = project(@24) */
  casadi_sparsify(w24, (&w46), casadi_s0, 0);
  /* #202: @47 = sparsity_cast(@47) */
  /* #203: @45 = dot(@46, @47) */
  w45 = casadi_dot(1, (&w46), (&w47));
  /* #204: @45 = (@45/@9) */
  w45 /= w09;
  /* #205: @54 = (@23*@45) */
  for (i=0, rr=w54, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)*w45);
  /* #206: @53 = (@53-@54) */
  for (i=0, rr=w53, cs=w54; i<4; ++i) (*rr++) -= (*cs++);
  /* #207: @46 = @53[0] */
  for (rr=(&w46), cs=w53+0; cs!=w53+1; cs+=1) *rr++ = *cs;
  /* #208: @44 = (@5*@46) */
  w44  = (w05*w46);
  /* #209: @49 = @53[1] */
  for (rr=(&w49), cs=w53+1; cs!=w53+2; cs+=1) *rr++ = *cs;
  /* #210: @43 = (@6*@49) */
  w43  = (w06*w49);
  /* #211: @44 = (@44-@43) */
  w44 -= w43;
  /* #212: @43 = @53[2] */
  for (rr=(&w43), cs=w53+2; cs!=w53+3; cs+=1) *rr++ = *cs;
  /* #213: @16 = (@7*@43) */
  w16  = (w07*w43);
  /* #214: @44 = (@44-@16) */
  w44 -= w16;
  /* #215: @16 = @53[3] */
  for (rr=(&w16), cs=w53+3; cs!=w53+4; cs+=1) *rr++ = *cs;
  /* #216: @41 = (@8*@16) */
  w41  = (w08*w16);
  /* #217: @44 = (@44-@41) */
  w44 -= w41;
  /* #218: @41 = (@6*@46) */
  w41  = (w06*w46);
  /* #219: @37 = (@5*@49) */
  w37  = (w05*w49);
  /* #220: @41 = (@41+@37) */
  w41 += w37;
  /* #221: @37 = (@8*@43) */
  w37  = (w08*w43);
  /* #222: @41 = (@41+@37) */
  w41 += w37;
  /* #223: @37 = (@7*@16) */
  w37  = (w07*w16);
  /* #224: @41 = (@41-@37) */
  w41 -= w37;
  /* #225: @37 = (@7*@46) */
  w37  = (w07*w46);
  /* #226: @38 = (@8*@49) */
  w38  = (w08*w49);
  /* #227: @37 = (@37-@38) */
  w37 -= w38;
  /* #228: @38 = (@5*@43) */
  w38  = (w05*w43);
  /* #229: @37 = (@37+@38) */
  w37 += w38;
  /* #230: @38 = (@6*@16) */
  w38  = (w06*w16);
  /* #231: @37 = (@37+@38) */
  w37 += w38;
  /* #232: @46 = (@8*@46) */
  w46  = (w08*w46);
  /* #233: @49 = (@7*@49) */
  w49  = (w07*w49);
  /* #234: @46 = (@46+@49) */
  w46 += w49;
  /* #235: @43 = (@6*@43) */
  w43  = (w06*w43);
  /* #236: @46 = (@46-@43) */
  w46 -= w43;
  /* #237: @16 = (@5*@16) */
  w16  = (w05*w16);
  /* #238: @46 = (@46+@16) */
  w46 += w16;
  /* #239: @54 = vertcat(@44, @41, @37, @46) */
  rr=w54;
  *rr++ = w44;
  *rr++ = w41;
  *rr++ = w37;
  *rr++ = w46;
  /* #240: @55 = (-@54) */
  for (i=0, rr=w55, cs=w54; i<4; ++i) *rr++ = (- *cs++ );
  /* #241: @55 = (@13?@55:0) */
  for (i=0, rr=w55, cs=w55; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #242: @54 = (@11?@54:0) */
  for (i=0, rr=w54, cs=w54; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #243: @55 = (@55+@54) */
  for (i=0, rr=w55, cs=w54; i<4; ++i) (*rr++) += (*cs++);
  /* #244: @22 = @55[1:4] */
  for (rr=w22, cs=w55+1; cs!=w55+4; cs+=1) *rr++ = *cs;
  /* #245: @44 = dot(@18, @22) */
  w44 = casadi_dot(3, w18, w22);
  /* #246: @44 = (@44/@14) */
  w44 /= w14;
  /* #247: @41 = (@44/@2) */
  w41  = (w44/w02);
  /* #248: @37 = (@0/@2) */
  w37  = (w00/w02);
  /* #249: @46 = (2.*@14) */
  w46 = (2.* w14 );
  /* #250: @16 = (@46*@44) */
  w16  = (w46*w44);
  /* #251: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #252: @43 = @55[0] */
  for (rr=(&w43), cs=w55+0; cs!=w55+1; cs+=1) *rr++ = *cs;
  /* #253: @49 = (@15*@43) */
  w49  = (w15*w43);
  /* #254: @16 = (@16+@49) */
  w16 += w49;
  /* #255: @49 = (@37*@16) */
  w49  = (w37*w16);
  /* #256: @41 = (@41-@49) */
  w41 -= w49;
  /* #257: @41 = (@4*@41) */
  w41  = (w04*w41);
  /* #258: @34 = (2.*@22) */
  for (i=0, rr=w34, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #259: @20 = (@10*@34) */
  for (i=0, rr=w20, cs=w34; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #260: @49 = (@12*@44) */
  w49  = (w12*w44);
  /* #261: @38 = (@0*@43) */
  w38  = (w00*w43);
  /* #262: @49 = (@49-@38) */
  w49 -= w38;
  /* #263: @35 = (@27*@49) */
  for (i=0, rr=w35, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w49);
  /* #264: @20 = (@20+@35) */
  for (i=0, rr=w20, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #265: @20 = (@20/@14) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w14;
  /* #266: @35 = (@28*@44) */
  for (i=0, rr=w35, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #267: @20 = (@20-@35) */
  for (i=0, rr=w20, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #268: @35 = @20' */
  casadi_copy(w20, 3, w35);
  /* #269: @56 = mac(@35,@21,@1) */
  casadi_copy(w01, 3, w56);
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #270: @56 = @56' */
  /* #271: @57 = mac(@35,@31,@1) */
  casadi_copy(w01, 3, w57);
  for (i=0, rr=w57; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #272: @57 = @57' */
  /* #273: @56 = (@56+@57) */
  for (i=0, rr=w56, cs=w57; i<3; ++i) (*rr++) += (*cs++);
  /* #274: @57 = (@56/@14) */
  for (i=0, rr=w57, cr=w56; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #275: @35 = (@32/@14) */
  for (i=0, rr=w35, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #276: @58 = (@35*@44) */
  for (i=0, rr=w58, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #277: @57 = (@57-@58) */
  for (i=0, rr=w57, cs=w58; i<3; ++i) (*rr++) -= (*cs++);
  /* #278: @38 = dot(@27, @57) */
  w38 = casadi_dot(3, w27, w57);
  /* #279: @40 = dot(@34, @32) */
  w40 = casadi_dot(3, w34, w32);
  /* #280: @38 = (@38+@40) */
  w38 += w40;
  /* #281: @40 = (@0*@38) */
  w40  = (w00*w38);
  /* #282: @41 = (@41+@40) */
  w41 += w40;
  /* #283: @41 = (-@41) */
  w41 = (- w41 );
  /* #284: @55 = @25; (@55[0] += @41) */
  casadi_copy(w25, 4, w55);
  for (rr=w55+0, cs=(&w41); rr!=w55+1; rr+=1) *rr += *cs++;
  /* #285: @41 = dot(@29, @56) */
  w41 = casadi_dot(3, w29, w56);
  /* #286: @20 = (@20/@14) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w14;
  /* #287: @56 = (@28/@14) */
  for (i=0, rr=w56, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #288: @34 = (@56*@44) */
  for (i=0, rr=w34, cr=w56; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #289: @20 = (@20-@34) */
  for (i=0, rr=w20, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #290: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #291: @40 = dot(@20, @30) */
  w40 = casadi_dot(3, w20, w30);
  /* #292: @41 = (@41+@40) */
  w41 += w40;
  /* #293: @43 = (@43/@2) */
  w43 /= w02;
  /* #294: @40 = (@12/@2) */
  w40  = (w12/w02);
  /* #295: @16 = (@40*@16) */
  w16  = (w40*w16);
  /* #296: @43 = (@43-@16) */
  w43 -= w16;
  /* #297: @43 = (@4*@43) */
  w43  = (w04*w43);
  /* #298: @38 = (@12*@38) */
  w38  = (w12*w38);
  /* #299: @43 = (@43+@38) */
  w43 += w38;
  /* #300: @41 = (@41+@43) */
  w41 += w43;
  /* #301: @41 = (@41/@14) */
  w41 /= w14;
  /* #302: @43 = (@3/@14) */
  w43  = (w03/w14);
  /* #303: @44 = (@43*@44) */
  w44  = (w43*w44);
  /* #304: @41 = (@41-@44) */
  w41 -= w44;
  /* #305: @20 = (@18*@41) */
  for (i=0, rr=w20, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w41);
  /* #306: @22 = (@3*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #307: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #308: @22 = (@32*@49) */
  for (i=0, rr=w22, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w49);
  /* #309: @57 = (@10*@57) */
  for (i=0, rr=w57, cs=w57; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #310: @22 = (@22+@57) */
  for (i=0, rr=w22, cs=w57; i<3; ++i) (*rr++) += (*cs++);
  /* #311: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #312: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #313: (@55[1:4] += @20) */
  for (rr=w55+1, cs=w20; rr!=w55+4; rr+=1) *rr += *cs++;
  /* #314: @54 = (@11?@55:0) */
  for (i=0, rr=w54, cs=w55; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #315: @55 = (-@55) */
  for (i=0, rr=w55, cs=w55; i<4; ++i) *rr++ = (- *cs++ );
  /* #316: @55 = (@13?@55:0) */
  for (i=0, rr=w55, cs=w55; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #317: @54 = (@54+@55) */
  for (i=0, rr=w54, cs=w55; i<4; ++i) (*rr++) += (*cs++);
  /* #318: {@49, @41, @44, @38} = vertsplit(@54) */
  w49 = w54[0];
  w41 = w54[1];
  w44 = w54[2];
  w38 = w54[3];
  /* #319: @16 = (@5*@38) */
  w16  = (w05*w38);
  /* #320: @59 = (@6*@44) */
  w59  = (w06*w44);
  /* #321: @16 = (@16+@59) */
  w16 += w59;
  /* #322: @59 = (@7*@41) */
  w59  = (w07*w41);
  /* #323: @16 = (@16-@59) */
  w16 -= w59;
  /* #324: @59 = (@8*@49) */
  w59  = (w08*w49);
  /* #325: @16 = (@16-@59) */
  w16 -= w59;
  /* #326: @54 = @25; (@54[3] += @16) */
  casadi_copy(w25, 4, w54);
  for (rr=w54+3, cs=(&w16); rr!=w54+4; rr+=1) *rr += *cs++;
  /* #327: @16 = (@5*@44) */
  w16  = (w05*w44);
  /* #328: @59 = (@6*@38) */
  w59  = (w06*w38);
  /* #329: @16 = (@16-@59) */
  w16 -= w59;
  /* #330: @59 = (@8*@41) */
  w59  = (w08*w41);
  /* #331: @16 = (@16+@59) */
  w16 += w59;
  /* #332: @59 = (@7*@49) */
  w59  = (w07*w49);
  /* #333: @16 = (@16-@59) */
  w16 -= w59;
  /* #334: (@54[2] += @16) */
  for (rr=w54+2, cs=(&w16); rr!=w54+3; rr+=1) *rr += *cs++;
  /* #335: @16 = (@7*@38) */
  w16  = (w07*w38);
  /* #336: @59 = (@8*@44) */
  w59  = (w08*w44);
  /* #337: @16 = (@16-@59) */
  w16 -= w59;
  /* #338: @59 = (@5*@41) */
  w59  = (w05*w41);
  /* #339: @16 = (@16+@59) */
  w16 += w59;
  /* #340: @59 = (@6*@49) */
  w59  = (w06*w49);
  /* #341: @16 = (@16-@59) */
  w16 -= w59;
  /* #342: (@54[1] += @16) */
  for (rr=w54+1, cs=(&w16); rr!=w54+2; rr+=1) *rr += *cs++;
  /* #343: @38 = (@8*@38) */
  w38  = (w08*w38);
  /* #344: @44 = (@7*@44) */
  w44  = (w07*w44);
  /* #345: @38 = (@38+@44) */
  w38 += w44;
  /* #346: @41 = (@6*@41) */
  w41  = (w06*w41);
  /* #347: @38 = (@38+@41) */
  w38 += w41;
  /* #348: @49 = (@5*@49) */
  w49  = (w05*w49);
  /* #349: @38 = (@38+@49) */
  w38 += w49;
  /* #350: (@54[0] += @38) */
  for (rr=w54+0, cs=(&w38); rr!=w54+1; rr+=1) *rr += *cs++;
  /* #351: @38 = dot(@26, @54) */
  w38 = casadi_dot(4, w26, w54);
  /* #352: @53 = (@53/@9) */
  for (i=0, rr=w53; i<4; ++i) (*rr++) /= w09;
  /* #353: @55 = (@23/@9) */
  for (i=0, rr=w55, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)/w09);
  /* #354: @60 = (@55*@45) */
  for (i=0, rr=w60, cr=w55; i<4; ++i) (*rr++)  = ((*cr++)*w45);
  /* #355: @53 = (@53-@60) */
  for (i=0, rr=w53, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #356: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<4; ++i) *rr++ = (- *cs++ );
  /* #357: @49 = dot(@53, @36) */
  w49 = casadi_dot(4, w53, w36);
  /* #358: @38 = (@38+@49) */
  w38 += w49;
  /* #359: @38 = (@38/@9) */
  w38 /= w09;
  /* #360: @49 = (@39/@9) */
  w49  = (w39/w09);
  /* #361: @41 = (@49*@45) */
  w41  = (w49*w45);
  /* #362: @38 = (@38-@41) */
  w38 -= w41;
  /* #363: @53 = (@24*@38) */
  for (i=0, rr=w53, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w38);
  /* #364: @47 = (@39*@47) */
  w47  = (w39*w47);
  /* #365: @60 = dense(@47) */
  casadi_densify((&w47), casadi_s0, w60, 0);
  /* #366: @53 = (@53+@60) */
  for (i=0, rr=w53, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #367: @42 = @19; (@42[3:7] += @53) */
  casadi_copy(w19, 11, w42);
  for (rr=w42+3, cs=w53; rr!=w42+7; rr+=1) *rr += *cs++;
  /* #368: @48 = sparsity_cast(@48) */
  /* #369: @48 = (-@48) */
  w48 = (- w48 );
  /* #370: @48 = @48' */
  /* #371: @20 = mac(@48,@21,@1) */
  casadi_copy(w01, 3, w20);
  casadi_mtimes((&w48), casadi_s3, w21, casadi_s2, w20, casadi_s1, w, 0);
  /* #372: @20 = @20' */
  /* #373: @22 = mac(@48,@31,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w48), casadi_s3, w31, casadi_s2, w22, casadi_s1, w, 0);
  /* #374: @22 = @22' */
  /* #375: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #376: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #377: (@42[:3] += @20) */
  for (rr=w42+0, cs=w20; rr!=w42+3; rr+=1) *rr += *cs++;
  /* #378: {@48, @47, @38, @41, @44, @16, @59, @61, @62, @63, @64} = vertsplit(@42) */
  w48 = w42[0];
  w47 = w42[1];
  w38 = w42[2];
  w41 = w42[3];
  w44 = w42[4];
  w16 = w42[5];
  w59 = w42[6];
  w61 = w42[7];
  w62 = w42[8];
  w63 = w42[9];
  w64 = w42[10];
  /* #379: @54 = (@54/@9) */
  for (i=0, rr=w54; i<4; ++i) (*rr++) /= w09;
  /* #380: @33 = (@33/@9) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w09;
  /* #381: @53 = (@33*@45) */
  for (i=0, rr=w53, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w45);
  /* #382: @54 = (@54-@53) */
  for (i=0, rr=w54, cs=w53; i<4; ++i) (*rr++) -= (*cs++);
  /* #383: {@45, @65, @66, @67} = vertsplit(@54) */
  w45 = w54[0];
  w65 = w54[1];
  w66 = w54[2];
  w67 = w54[3];
  /* #384: @45 = (@45+@41) */
  w45 += w41;
  /* #385: @44 = (@44-@65) */
  w44 -= w65;
  /* #386: @16 = (@16-@66) */
  w16 -= w66;
  /* #387: @59 = (@59-@67) */
  w59 -= w67;
  /* #388: @42 = vertcat(@48, @47, @38, @45, @44, @16, @59, @61, @62, @63, @64) */
  rr=w42;
  *rr++ = w48;
  *rr++ = w47;
  *rr++ = w38;
  *rr++ = w45;
  *rr++ = w44;
  *rr++ = w16;
  *rr++ = w59;
  *rr++ = w61;
  *rr++ = w62;
  *rr++ = w63;
  *rr++ = w64;
  /* #389: @68 = @42[:7] */
  for (rr=w68, cs=w42+0; cs!=w42+7; cs+=1) *rr++ = *cs;
  /* #390: (@50[0, 1, 2, 9, 10, 11, 12] = @68) */
  for (cii=casadi_s4, rr=w50, cs=w68; cii!=casadi_s4+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #391: (@50[0, 3, 6, 9, 13, 17, 21] = @68) */
  for (cii=casadi_s5, rr=w50, cs=w68; cii!=casadi_s5+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #392: @69 = ones(11x1,2nz) */
  casadi_fill(w69, 2, 1.);
  /* #393: {NULL, @48, NULL, NULL, @47, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@69) */
  w48 = w69[0];
  w47 = w69[1];
  /* #394: @38 = (-@47) */
  w38 = (- w47 );
  /* #395: @45 = vertcat(@52, @38, @52, @52) */
  rr=(&w45);
  *rr++ = w38;
  /* #396: @45 = (@45/@9) */
  w45 /= w09;
  /* #397: @54 = dense(@45) */
  casadi_densify((&w45), casadi_s6, w54, 0);
  /* #398: @45 = project(@24) */
  casadi_sparsify(w24, (&w45), casadi_s6, 0);
  /* #399: @47 = sparsity_cast(@47) */
  /* #400: @38 = dot(@45, @47) */
  w38 = casadi_dot(1, (&w45), (&w47));
  /* #401: @38 = (@38/@9) */
  w38 /= w09;
  /* #402: @53 = (@23*@38) */
  for (i=0, rr=w53, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)*w38);
  /* #403: @54 = (@54-@53) */
  for (i=0, rr=w54, cs=w53; i<4; ++i) (*rr++) -= (*cs++);
  /* #404: @45 = @54[0] */
  for (rr=(&w45), cs=w54+0; cs!=w54+1; cs+=1) *rr++ = *cs;
  /* #405: @44 = (@5*@45) */
  w44  = (w05*w45);
  /* #406: @16 = @54[1] */
  for (rr=(&w16), cs=w54+1; cs!=w54+2; cs+=1) *rr++ = *cs;
  /* #407: @59 = (@6*@16) */
  w59  = (w06*w16);
  /* #408: @44 = (@44-@59) */
  w44 -= w59;
  /* #409: @59 = @54[2] */
  for (rr=(&w59), cs=w54+2; cs!=w54+3; cs+=1) *rr++ = *cs;
  /* #410: @61 = (@7*@59) */
  w61  = (w07*w59);
  /* #411: @44 = (@44-@61) */
  w44 -= w61;
  /* #412: @61 = @54[3] */
  for (rr=(&w61), cs=w54+3; cs!=w54+4; cs+=1) *rr++ = *cs;
  /* #413: @62 = (@8*@61) */
  w62  = (w08*w61);
  /* #414: @44 = (@44-@62) */
  w44 -= w62;
  /* #415: @62 = (@6*@45) */
  w62  = (w06*w45);
  /* #416: @63 = (@5*@16) */
  w63  = (w05*w16);
  /* #417: @62 = (@62+@63) */
  w62 += w63;
  /* #418: @63 = (@8*@59) */
  w63  = (w08*w59);
  /* #419: @62 = (@62+@63) */
  w62 += w63;
  /* #420: @63 = (@7*@61) */
  w63  = (w07*w61);
  /* #421: @62 = (@62-@63) */
  w62 -= w63;
  /* #422: @63 = (@7*@45) */
  w63  = (w07*w45);
  /* #423: @64 = (@8*@16) */
  w64  = (w08*w16);
  /* #424: @63 = (@63-@64) */
  w63 -= w64;
  /* #425: @64 = (@5*@59) */
  w64  = (w05*w59);
  /* #426: @63 = (@63+@64) */
  w63 += w64;
  /* #427: @64 = (@6*@61) */
  w64  = (w06*w61);
  /* #428: @63 = (@63+@64) */
  w63 += w64;
  /* #429: @45 = (@8*@45) */
  w45  = (w08*w45);
  /* #430: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #431: @45 = (@45+@16) */
  w45 += w16;
  /* #432: @59 = (@6*@59) */
  w59  = (w06*w59);
  /* #433: @45 = (@45-@59) */
  w45 -= w59;
  /* #434: @61 = (@5*@61) */
  w61  = (w05*w61);
  /* #435: @45 = (@45+@61) */
  w45 += w61;
  /* #436: @53 = vertcat(@44, @62, @63, @45) */
  rr=w53;
  *rr++ = w44;
  *rr++ = w62;
  *rr++ = w63;
  *rr++ = w45;
  /* #437: @60 = (-@53) */
  for (i=0, rr=w60, cs=w53; i<4; ++i) *rr++ = (- *cs++ );
  /* #438: @60 = (@13?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #439: @53 = (@11?@53:0) */
  for (i=0, rr=w53, cs=w53; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #440: @60 = (@60+@53) */
  for (i=0, rr=w60, cs=w53; i<4; ++i) (*rr++) += (*cs++);
  /* #441: @20 = @60[1:4] */
  for (rr=w20, cs=w60+1; cs!=w60+4; cs+=1) *rr++ = *cs;
  /* #442: @44 = dot(@18, @20) */
  w44 = casadi_dot(3, w18, w20);
  /* #443: @44 = (@44/@14) */
  w44 /= w14;
  /* #444: @62 = (@44/@2) */
  w62  = (w44/w02);
  /* #445: @63 = (@46*@44) */
  w63  = (w46*w44);
  /* #446: @45 = @60[0] */
  for (rr=(&w45), cs=w60+0; cs!=w60+1; cs+=1) *rr++ = *cs;
  /* #447: @61 = (@15*@45) */
  w61  = (w15*w45);
  /* #448: @63 = (@63+@61) */
  w63 += w61;
  /* #449: @61 = (@37*@63) */
  w61  = (w37*w63);
  /* #450: @62 = (@62-@61) */
  w62 -= w61;
  /* #451: @62 = (@4*@62) */
  w62  = (w04*w62);
  /* #452: @22 = (2.*@20) */
  for (i=0, rr=w22, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #453: @57 = (@10*@22) */
  for (i=0, rr=w57, cs=w22; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #454: @61 = (@12*@44) */
  w61  = (w12*w44);
  /* #455: @59 = (@0*@45) */
  w59  = (w00*w45);
  /* #456: @61 = (@61-@59) */
  w61 -= w59;
  /* #457: @34 = (@27*@61) */
  for (i=0, rr=w34, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #458: @57 = (@57+@34) */
  for (i=0, rr=w57, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #459: @57 = (@57/@14) */
  for (i=0, rr=w57; i<3; ++i) (*rr++) /= w14;
  /* #460: @34 = (@28*@44) */
  for (i=0, rr=w34, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #461: @57 = (@57-@34) */
  for (i=0, rr=w57, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #462: @34 = @57' */
  casadi_copy(w57, 3, w34);
  /* #463: @58 = mac(@34,@21,@1) */
  casadi_copy(w01, 3, w58);
  for (i=0, rr=w58; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #464: @58 = @58' */
  /* #465: @70 = mac(@34,@31,@1) */
  casadi_copy(w01, 3, w70);
  for (i=0, rr=w70; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #466: @70 = @70' */
  /* #467: @58 = (@58+@70) */
  for (i=0, rr=w58, cs=w70; i<3; ++i) (*rr++) += (*cs++);
  /* #468: @70 = (@58/@14) */
  for (i=0, rr=w70, cr=w58; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #469: @34 = (@35*@44) */
  for (i=0, rr=w34, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #470: @70 = (@70-@34) */
  for (i=0, rr=w70, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #471: @59 = dot(@27, @70) */
  w59 = casadi_dot(3, w27, w70);
  /* #472: @16 = dot(@22, @32) */
  w16 = casadi_dot(3, w22, w32);
  /* #473: @59 = (@59+@16) */
  w59 += w16;
  /* #474: @16 = (@0*@59) */
  w16  = (w00*w59);
  /* #475: @62 = (@62+@16) */
  w62 += w16;
  /* #476: @62 = (-@62) */
  w62 = (- w62 );
  /* #477: @60 = @25; (@60[0] += @62) */
  casadi_copy(w25, 4, w60);
  for (rr=w60+0, cs=(&w62); rr!=w60+1; rr+=1) *rr += *cs++;
  /* #478: @62 = dot(@29, @58) */
  w62 = casadi_dot(3, w29, w58);
  /* #479: @57 = (@57/@14) */
  for (i=0, rr=w57; i<3; ++i) (*rr++) /= w14;
  /* #480: @58 = (@56*@44) */
  for (i=0, rr=w58, cr=w56; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #481: @57 = (@57-@58) */
  for (i=0, rr=w57, cs=w58; i<3; ++i) (*rr++) -= (*cs++);
  /* #482: @57 = (-@57) */
  for (i=0, rr=w57, cs=w57; i<3; ++i) *rr++ = (- *cs++ );
  /* #483: @16 = dot(@57, @30) */
  w16 = casadi_dot(3, w57, w30);
  /* #484: @62 = (@62+@16) */
  w62 += w16;
  /* #485: @45 = (@45/@2) */
  w45 /= w02;
  /* #486: @63 = (@40*@63) */
  w63  = (w40*w63);
  /* #487: @45 = (@45-@63) */
  w45 -= w63;
  /* #488: @45 = (@4*@45) */
  w45  = (w04*w45);
  /* #489: @59 = (@12*@59) */
  w59  = (w12*w59);
  /* #490: @45 = (@45+@59) */
  w45 += w59;
  /* #491: @62 = (@62+@45) */
  w62 += w45;
  /* #492: @62 = (@62/@14) */
  w62 /= w14;
  /* #493: @44 = (@43*@44) */
  w44  = (w43*w44);
  /* #494: @62 = (@62-@44) */
  w62 -= w44;
  /* #495: @57 = (@18*@62) */
  for (i=0, rr=w57, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #496: @20 = (@3*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #497: @57 = (@57+@20) */
  for (i=0, rr=w57, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #498: @20 = (@32*@61) */
  for (i=0, rr=w20, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w61);
  /* #499: @70 = (@10*@70) */
  for (i=0, rr=w70, cs=w70; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #500: @20 = (@20+@70) */
  for (i=0, rr=w20, cs=w70; i<3; ++i) (*rr++) += (*cs++);
  /* #501: @20 = (2.*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #502: @57 = (@57+@20) */
  for (i=0, rr=w57, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #503: (@60[1:4] += @57) */
  for (rr=w60+1, cs=w57; rr!=w60+4; rr+=1) *rr += *cs++;
  /* #504: @53 = (@11?@60:0) */
  for (i=0, rr=w53, cs=w60; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #505: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #506: @60 = (@13?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #507: @53 = (@53+@60) */
  for (i=0, rr=w53, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #508: {@61, @62, @44, @45} = vertsplit(@53) */
  w61 = w53[0];
  w62 = w53[1];
  w44 = w53[2];
  w45 = w53[3];
  /* #509: @59 = (@5*@45) */
  w59  = (w05*w45);
  /* #510: @63 = (@6*@44) */
  w63  = (w06*w44);
  /* #511: @59 = (@59+@63) */
  w59 += w63;
  /* #512: @63 = (@7*@62) */
  w63  = (w07*w62);
  /* #513: @59 = (@59-@63) */
  w59 -= w63;
  /* #514: @63 = (@8*@61) */
  w63  = (w08*w61);
  /* #515: @59 = (@59-@63) */
  w59 -= w63;
  /* #516: @53 = @25; (@53[3] += @59) */
  casadi_copy(w25, 4, w53);
  for (rr=w53+3, cs=(&w59); rr!=w53+4; rr+=1) *rr += *cs++;
  /* #517: @59 = (@5*@44) */
  w59  = (w05*w44);
  /* #518: @63 = (@6*@45) */
  w63  = (w06*w45);
  /* #519: @59 = (@59-@63) */
  w59 -= w63;
  /* #520: @63 = (@8*@62) */
  w63  = (w08*w62);
  /* #521: @59 = (@59+@63) */
  w59 += w63;
  /* #522: @63 = (@7*@61) */
  w63  = (w07*w61);
  /* #523: @59 = (@59-@63) */
  w59 -= w63;
  /* #524: (@53[2] += @59) */
  for (rr=w53+2, cs=(&w59); rr!=w53+3; rr+=1) *rr += *cs++;
  /* #525: @59 = (@7*@45) */
  w59  = (w07*w45);
  /* #526: @63 = (@8*@44) */
  w63  = (w08*w44);
  /* #527: @59 = (@59-@63) */
  w59 -= w63;
  /* #528: @63 = (@5*@62) */
  w63  = (w05*w62);
  /* #529: @59 = (@59+@63) */
  w59 += w63;
  /* #530: @63 = (@6*@61) */
  w63  = (w06*w61);
  /* #531: @59 = (@59-@63) */
  w59 -= w63;
  /* #532: (@53[1] += @59) */
  for (rr=w53+1, cs=(&w59); rr!=w53+2; rr+=1) *rr += *cs++;
  /* #533: @45 = (@8*@45) */
  w45  = (w08*w45);
  /* #534: @44 = (@7*@44) */
  w44  = (w07*w44);
  /* #535: @45 = (@45+@44) */
  w45 += w44;
  /* #536: @62 = (@6*@62) */
  w62  = (w06*w62);
  /* #537: @45 = (@45+@62) */
  w45 += w62;
  /* #538: @61 = (@5*@61) */
  w61  = (w05*w61);
  /* #539: @45 = (@45+@61) */
  w45 += w61;
  /* #540: (@53[0] += @45) */
  for (rr=w53+0, cs=(&w45); rr!=w53+1; rr+=1) *rr += *cs++;
  /* #541: @45 = dot(@26, @53) */
  w45 = casadi_dot(4, w26, w53);
  /* #542: @54 = (@54/@9) */
  for (i=0, rr=w54; i<4; ++i) (*rr++) /= w09;
  /* #543: @60 = (@55*@38) */
  for (i=0, rr=w60, cr=w55; i<4; ++i) (*rr++)  = ((*cr++)*w38);
  /* #544: @54 = (@54-@60) */
  for (i=0, rr=w54, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #545: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<4; ++i) *rr++ = (- *cs++ );
  /* #546: @61 = dot(@54, @36) */
  w61 = casadi_dot(4, w54, w36);
  /* #547: @45 = (@45+@61) */
  w45 += w61;
  /* #548: @45 = (@45/@9) */
  w45 /= w09;
  /* #549: @61 = (@49*@38) */
  w61  = (w49*w38);
  /* #550: @45 = (@45-@61) */
  w45 -= w61;
  /* #551: @54 = (@24*@45) */
  for (i=0, rr=w54, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w45);
  /* #552: @47 = (@39*@47) */
  w47  = (w39*w47);
  /* #553: @60 = dense(@47) */
  casadi_densify((&w47), casadi_s6, w60, 0);
  /* #554: @54 = (@54+@60) */
  for (i=0, rr=w54, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #555: @42 = @19; (@42[3:7] += @54) */
  casadi_copy(w19, 11, w42);
  for (rr=w42+3, cs=w54; rr!=w42+7; rr+=1) *rr += *cs++;
  /* #556: @48 = sparsity_cast(@48) */
  /* #557: @48 = (-@48) */
  w48 = (- w48 );
  /* #558: @48 = @48' */
  /* #559: @57 = mac(@48,@21,@1) */
  casadi_copy(w01, 3, w57);
  casadi_mtimes((&w48), casadi_s7, w21, casadi_s2, w57, casadi_s1, w, 0);
  /* #560: @57 = @57' */
  /* #561: @20 = mac(@48,@31,@1) */
  casadi_copy(w01, 3, w20);
  casadi_mtimes((&w48), casadi_s7, w31, casadi_s2, w20, casadi_s1, w, 0);
  /* #562: @20 = @20' */
  /* #563: @57 = (@57+@20) */
  for (i=0, rr=w57, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #564: @57 = (-@57) */
  for (i=0, rr=w57, cs=w57; i<3; ++i) *rr++ = (- *cs++ );
  /* #565: (@42[:3] += @57) */
  for (rr=w42+0, cs=w57; rr!=w42+3; rr+=1) *rr += *cs++;
  /* #566: {@48, @47, @45, @61, @62, @44, @59, @63, @16, @64, @67} = vertsplit(@42) */
  w48 = w42[0];
  w47 = w42[1];
  w45 = w42[2];
  w61 = w42[3];
  w62 = w42[4];
  w44 = w42[5];
  w59 = w42[6];
  w63 = w42[7];
  w16 = w42[8];
  w64 = w42[9];
  w67 = w42[10];
  /* #567: @53 = (@53/@9) */
  for (i=0, rr=w53; i<4; ++i) (*rr++) /= w09;
  /* #568: @54 = (@33*@38) */
  for (i=0, rr=w54, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w38);
  /* #569: @53 = (@53-@54) */
  for (i=0, rr=w53, cs=w54; i<4; ++i) (*rr++) -= (*cs++);
  /* #570: {@38, @66, @65, @41} = vertsplit(@53) */
  w38 = w53[0];
  w66 = w53[1];
  w65 = w53[2];
  w41 = w53[3];
  /* #571: @38 = (@38+@61) */
  w38 += w61;
  /* #572: @62 = (@62-@66) */
  w62 -= w66;
  /* #573: @44 = (@44-@65) */
  w44 -= w65;
  /* #574: @59 = (@59-@41) */
  w59 -= w41;
  /* #575: @42 = vertcat(@48, @47, @45, @38, @62, @44, @59, @63, @16, @64, @67) */
  rr=w42;
  *rr++ = w48;
  *rr++ = w47;
  *rr++ = w45;
  *rr++ = w38;
  *rr++ = w62;
  *rr++ = w44;
  *rr++ = w59;
  *rr++ = w63;
  *rr++ = w16;
  *rr++ = w64;
  *rr++ = w67;
  /* #576: @68 = @42[:7] */
  for (rr=w68, cs=w42+0; cs!=w42+7; cs+=1) *rr++ = *cs;
  /* #577: (@50[3, 4, 5, 13, 14, 15, 16] = @68) */
  for (cii=casadi_s8, rr=w50, cs=w68; cii!=casadi_s8+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #578: (@50[1, 4, 7, 10, 14, 18, 22] = @68) */
  for (cii=casadi_s9, rr=w50, cs=w68; cii!=casadi_s9+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #579: @69 = ones(11x1,2nz) */
  casadi_fill(w69, 2, 1.);
  /* #580: {NULL, NULL, @48, NULL, NULL, @47, NULL, NULL, NULL, NULL, NULL} = vertsplit(@69) */
  w48 = w69[0];
  w47 = w69[1];
  /* #581: @45 = (-@47) */
  w45 = (- w47 );
  /* #582: @38 = vertcat(@52, @52, @45, @52) */
  rr=(&w38);
  *rr++ = w45;
  /* #583: @38 = (@38/@9) */
  w38 /= w09;
  /* #584: @53 = dense(@38) */
  casadi_densify((&w38), casadi_s10, w53, 0);
  /* #585: @38 = project(@24) */
  casadi_sparsify(w24, (&w38), casadi_s10, 0);
  /* #586: @47 = sparsity_cast(@47) */
  /* #587: @45 = dot(@38, @47) */
  w45 = casadi_dot(1, (&w38), (&w47));
  /* #588: @45 = (@45/@9) */
  w45 /= w09;
  /* #589: @54 = (@23*@45) */
  for (i=0, rr=w54, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)*w45);
  /* #590: @53 = (@53-@54) */
  for (i=0, rr=w53, cs=w54; i<4; ++i) (*rr++) -= (*cs++);
  /* #591: @38 = @53[0] */
  for (rr=(&w38), cs=w53+0; cs!=w53+1; cs+=1) *rr++ = *cs;
  /* #592: @62 = (@5*@38) */
  w62  = (w05*w38);
  /* #593: @44 = @53[1] */
  for (rr=(&w44), cs=w53+1; cs!=w53+2; cs+=1) *rr++ = *cs;
  /* #594: @59 = (@6*@44) */
  w59  = (w06*w44);
  /* #595: @62 = (@62-@59) */
  w62 -= w59;
  /* #596: @59 = @53[2] */
  for (rr=(&w59), cs=w53+2; cs!=w53+3; cs+=1) *rr++ = *cs;
  /* #597: @63 = (@7*@59) */
  w63  = (w07*w59);
  /* #598: @62 = (@62-@63) */
  w62 -= w63;
  /* #599: @63 = @53[3] */
  for (rr=(&w63), cs=w53+3; cs!=w53+4; cs+=1) *rr++ = *cs;
  /* #600: @16 = (@8*@63) */
  w16  = (w08*w63);
  /* #601: @62 = (@62-@16) */
  w62 -= w16;
  /* #602: @16 = (@6*@38) */
  w16  = (w06*w38);
  /* #603: @64 = (@5*@44) */
  w64  = (w05*w44);
  /* #604: @16 = (@16+@64) */
  w16 += w64;
  /* #605: @64 = (@8*@59) */
  w64  = (w08*w59);
  /* #606: @16 = (@16+@64) */
  w16 += w64;
  /* #607: @64 = (@7*@63) */
  w64  = (w07*w63);
  /* #608: @16 = (@16-@64) */
  w16 -= w64;
  /* #609: @64 = (@7*@38) */
  w64  = (w07*w38);
  /* #610: @67 = (@8*@44) */
  w67  = (w08*w44);
  /* #611: @64 = (@64-@67) */
  w64 -= w67;
  /* #612: @67 = (@5*@59) */
  w67  = (w05*w59);
  /* #613: @64 = (@64+@67) */
  w64 += w67;
  /* #614: @67 = (@6*@63) */
  w67  = (w06*w63);
  /* #615: @64 = (@64+@67) */
  w64 += w67;
  /* #616: @38 = (@8*@38) */
  w38  = (w08*w38);
  /* #617: @44 = (@7*@44) */
  w44  = (w07*w44);
  /* #618: @38 = (@38+@44) */
  w38 += w44;
  /* #619: @59 = (@6*@59) */
  w59  = (w06*w59);
  /* #620: @38 = (@38-@59) */
  w38 -= w59;
  /* #621: @63 = (@5*@63) */
  w63  = (w05*w63);
  /* #622: @38 = (@38+@63) */
  w38 += w63;
  /* #623: @54 = vertcat(@62, @16, @64, @38) */
  rr=w54;
  *rr++ = w62;
  *rr++ = w16;
  *rr++ = w64;
  *rr++ = w38;
  /* #624: @60 = (-@54) */
  for (i=0, rr=w60, cs=w54; i<4; ++i) *rr++ = (- *cs++ );
  /* #625: @60 = (@13?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #626: @54 = (@11?@54:0) */
  for (i=0, rr=w54, cs=w54; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #627: @60 = (@60+@54) */
  for (i=0, rr=w60, cs=w54; i<4; ++i) (*rr++) += (*cs++);
  /* #628: @57 = @60[1:4] */
  for (rr=w57, cs=w60+1; cs!=w60+4; cs+=1) *rr++ = *cs;
  /* #629: @62 = dot(@18, @57) */
  w62 = casadi_dot(3, w18, w57);
  /* #630: @62 = (@62/@14) */
  w62 /= w14;
  /* #631: @16 = (@62/@2) */
  w16  = (w62/w02);
  /* #632: @64 = (@46*@62) */
  w64  = (w46*w62);
  /* #633: @38 = @60[0] */
  for (rr=(&w38), cs=w60+0; cs!=w60+1; cs+=1) *rr++ = *cs;
  /* #634: @63 = (@15*@38) */
  w63  = (w15*w38);
  /* #635: @64 = (@64+@63) */
  w64 += w63;
  /* #636: @63 = (@37*@64) */
  w63  = (w37*w64);
  /* #637: @16 = (@16-@63) */
  w16 -= w63;
  /* #638: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #639: @20 = (2.*@57) */
  for (i=0, rr=w20, cs=w57; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #640: @70 = (@10*@20) */
  for (i=0, rr=w70, cs=w20; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #641: @63 = (@12*@62) */
  w63  = (w12*w62);
  /* #642: @59 = (@0*@38) */
  w59  = (w00*w38);
  /* #643: @63 = (@63-@59) */
  w63 -= w59;
  /* #644: @58 = (@27*@63) */
  for (i=0, rr=w58, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #645: @70 = (@70+@58) */
  for (i=0, rr=w70, cs=w58; i<3; ++i) (*rr++) += (*cs++);
  /* #646: @70 = (@70/@14) */
  for (i=0, rr=w70; i<3; ++i) (*rr++) /= w14;
  /* #647: @58 = (@28*@62) */
  for (i=0, rr=w58, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #648: @70 = (@70-@58) */
  for (i=0, rr=w70, cs=w58; i<3; ++i) (*rr++) -= (*cs++);
  /* #649: @58 = @70' */
  casadi_copy(w70, 3, w58);
  /* #650: @22 = mac(@58,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w58+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #651: @22 = @22' */
  /* #652: @34 = mac(@58,@31,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w58+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #653: @34 = @34' */
  /* #654: @22 = (@22+@34) */
  for (i=0, rr=w22, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #655: @34 = (@22/@14) */
  for (i=0, rr=w34, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #656: @58 = (@35*@62) */
  for (i=0, rr=w58, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #657: @34 = (@34-@58) */
  for (i=0, rr=w34, cs=w58; i<3; ++i) (*rr++) -= (*cs++);
  /* #658: @59 = dot(@27, @34) */
  w59 = casadi_dot(3, w27, w34);
  /* #659: @44 = dot(@20, @32) */
  w44 = casadi_dot(3, w20, w32);
  /* #660: @59 = (@59+@44) */
  w59 += w44;
  /* #661: @44 = (@0*@59) */
  w44  = (w00*w59);
  /* #662: @16 = (@16+@44) */
  w16 += w44;
  /* #663: @16 = (-@16) */
  w16 = (- w16 );
  /* #664: @60 = @25; (@60[0] += @16) */
  casadi_copy(w25, 4, w60);
  for (rr=w60+0, cs=(&w16); rr!=w60+1; rr+=1) *rr += *cs++;
  /* #665: @16 = dot(@29, @22) */
  w16 = casadi_dot(3, w29, w22);
  /* #666: @70 = (@70/@14) */
  for (i=0, rr=w70; i<3; ++i) (*rr++) /= w14;
  /* #667: @22 = (@56*@62) */
  for (i=0, rr=w22, cr=w56; i<3; ++i) (*rr++)  = ((*cr++)*w62);
  /* #668: @70 = (@70-@22) */
  for (i=0, rr=w70, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #669: @70 = (-@70) */
  for (i=0, rr=w70, cs=w70; i<3; ++i) *rr++ = (- *cs++ );
  /* #670: @44 = dot(@70, @30) */
  w44 = casadi_dot(3, w70, w30);
  /* #671: @16 = (@16+@44) */
  w16 += w44;
  /* #672: @38 = (@38/@2) */
  w38 /= w02;
  /* #673: @64 = (@40*@64) */
  w64  = (w40*w64);
  /* #674: @38 = (@38-@64) */
  w38 -= w64;
  /* #675: @38 = (@4*@38) */
  w38  = (w04*w38);
  /* #676: @59 = (@12*@59) */
  w59  = (w12*w59);
  /* #677: @38 = (@38+@59) */
  w38 += w59;
  /* #678: @16 = (@16+@38) */
  w16 += w38;
  /* #679: @16 = (@16/@14) */
  w16 /= w14;
  /* #680: @62 = (@43*@62) */
  w62  = (w43*w62);
  /* #681: @16 = (@16-@62) */
  w16 -= w62;
  /* #682: @70 = (@18*@16) */
  for (i=0, rr=w70, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w16);
  /* #683: @57 = (@3*@57) */
  for (i=0, rr=w57, cs=w57; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #684: @70 = (@70+@57) */
  for (i=0, rr=w70, cs=w57; i<3; ++i) (*rr++) += (*cs++);
  /* #685: @57 = (@32*@63) */
  for (i=0, rr=w57, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #686: @34 = (@10*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #687: @57 = (@57+@34) */
  for (i=0, rr=w57, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #688: @57 = (2.*@57) */
  for (i=0, rr=w57, cs=w57; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #689: @70 = (@70+@57) */
  for (i=0, rr=w70, cs=w57; i<3; ++i) (*rr++) += (*cs++);
  /* #690: (@60[1:4] += @70) */
  for (rr=w60+1, cs=w70; rr!=w60+4; rr+=1) *rr += *cs++;
  /* #691: @54 = (@11?@60:0) */
  for (i=0, rr=w54, cs=w60; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #692: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #693: @60 = (@13?@60:0) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #694: @54 = (@54+@60) */
  for (i=0, rr=w54, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #695: {@63, @16, @62, @38} = vertsplit(@54) */
  w63 = w54[0];
  w16 = w54[1];
  w62 = w54[2];
  w38 = w54[3];
  /* #696: @59 = (@5*@38) */
  w59  = (w05*w38);
  /* #697: @64 = (@6*@62) */
  w64  = (w06*w62);
  /* #698: @59 = (@59+@64) */
  w59 += w64;
  /* #699: @64 = (@7*@16) */
  w64  = (w07*w16);
  /* #700: @59 = (@59-@64) */
  w59 -= w64;
  /* #701: @64 = (@8*@63) */
  w64  = (w08*w63);
  /* #702: @59 = (@59-@64) */
  w59 -= w64;
  /* #703: @54 = @25; (@54[3] += @59) */
  casadi_copy(w25, 4, w54);
  for (rr=w54+3, cs=(&w59); rr!=w54+4; rr+=1) *rr += *cs++;
  /* #704: @59 = (@5*@62) */
  w59  = (w05*w62);
  /* #705: @64 = (@6*@38) */
  w64  = (w06*w38);
  /* #706: @59 = (@59-@64) */
  w59 -= w64;
  /* #707: @64 = (@8*@16) */
  w64  = (w08*w16);
  /* #708: @59 = (@59+@64) */
  w59 += w64;
  /* #709: @64 = (@7*@63) */
  w64  = (w07*w63);
  /* #710: @59 = (@59-@64) */
  w59 -= w64;
  /* #711: (@54[2] += @59) */
  for (rr=w54+2, cs=(&w59); rr!=w54+3; rr+=1) *rr += *cs++;
  /* #712: @59 = (@7*@38) */
  w59  = (w07*w38);
  /* #713: @64 = (@8*@62) */
  w64  = (w08*w62);
  /* #714: @59 = (@59-@64) */
  w59 -= w64;
  /* #715: @64 = (@5*@16) */
  w64  = (w05*w16);
  /* #716: @59 = (@59+@64) */
  w59 += w64;
  /* #717: @64 = (@6*@63) */
  w64  = (w06*w63);
  /* #718: @59 = (@59-@64) */
  w59 -= w64;
  /* #719: (@54[1] += @59) */
  for (rr=w54+1, cs=(&w59); rr!=w54+2; rr+=1) *rr += *cs++;
  /* #720: @38 = (@8*@38) */
  w38  = (w08*w38);
  /* #721: @62 = (@7*@62) */
  w62  = (w07*w62);
  /* #722: @38 = (@38+@62) */
  w38 += w62;
  /* #723: @16 = (@6*@16) */
  w16  = (w06*w16);
  /* #724: @38 = (@38+@16) */
  w38 += w16;
  /* #725: @63 = (@5*@63) */
  w63  = (w05*w63);
  /* #726: @38 = (@38+@63) */
  w38 += w63;
  /* #727: (@54[0] += @38) */
  for (rr=w54+0, cs=(&w38); rr!=w54+1; rr+=1) *rr += *cs++;
  /* #728: @38 = dot(@26, @54) */
  w38 = casadi_dot(4, w26, w54);
  /* #729: @53 = (@53/@9) */
  for (i=0, rr=w53; i<4; ++i) (*rr++) /= w09;
  /* #730: @60 = (@55*@45) */
  for (i=0, rr=w60, cr=w55; i<4; ++i) (*rr++)  = ((*cr++)*w45);
  /* #731: @53 = (@53-@60) */
  for (i=0, rr=w53, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #732: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<4; ++i) *rr++ = (- *cs++ );
  /* #733: @63 = dot(@53, @36) */
  w63 = casadi_dot(4, w53, w36);
  /* #734: @38 = (@38+@63) */
  w38 += w63;
  /* #735: @38 = (@38/@9) */
  w38 /= w09;
  /* #736: @63 = (@49*@45) */
  w63  = (w49*w45);
  /* #737: @38 = (@38-@63) */
  w38 -= w63;
  /* #738: @53 = (@24*@38) */
  for (i=0, rr=w53, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w38);
  /* #739: @47 = (@39*@47) */
  w47  = (w39*w47);
  /* #740: @60 = dense(@47) */
  casadi_densify((&w47), casadi_s10, w60, 0);
  /* #741: @53 = (@53+@60) */
  for (i=0, rr=w53, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #742: @42 = @19; (@42[3:7] += @53) */
  casadi_copy(w19, 11, w42);
  for (rr=w42+3, cs=w53; rr!=w42+7; rr+=1) *rr += *cs++;
  /* #743: @48 = sparsity_cast(@48) */
  /* #744: @48 = (-@48) */
  w48 = (- w48 );
  /* #745: @48 = @48' */
  /* #746: @70 = mac(@48,@21,@1) */
  casadi_copy(w01, 3, w70);
  casadi_mtimes((&w48), casadi_s11, w21, casadi_s2, w70, casadi_s1, w, 0);
  /* #747: @70 = @70' */
  /* #748: @57 = mac(@48,@31,@1) */
  casadi_copy(w01, 3, w57);
  casadi_mtimes((&w48), casadi_s11, w31, casadi_s2, w57, casadi_s1, w, 0);
  /* #749: @57 = @57' */
  /* #750: @70 = (@70+@57) */
  for (i=0, rr=w70, cs=w57; i<3; ++i) (*rr++) += (*cs++);
  /* #751: @70 = (-@70) */
  for (i=0, rr=w70, cs=w70; i<3; ++i) *rr++ = (- *cs++ );
  /* #752: (@42[:3] += @70) */
  for (rr=w42+0, cs=w70; rr!=w42+3; rr+=1) *rr += *cs++;
  /* #753: {@48, @47, @38, @63, @16, @62, @59, @64, @44, @67, @41} = vertsplit(@42) */
  w48 = w42[0];
  w47 = w42[1];
  w38 = w42[2];
  w63 = w42[3];
  w16 = w42[4];
  w62 = w42[5];
  w59 = w42[6];
  w64 = w42[7];
  w44 = w42[8];
  w67 = w42[9];
  w41 = w42[10];
  /* #754: @54 = (@54/@9) */
  for (i=0, rr=w54; i<4; ++i) (*rr++) /= w09;
  /* #755: @53 = (@33*@45) */
  for (i=0, rr=w53, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w45);
  /* #756: @54 = (@54-@53) */
  for (i=0, rr=w54, cs=w53; i<4; ++i) (*rr++) -= (*cs++);
  /* #757: {@45, @65, @66, @61} = vertsplit(@54) */
  w45 = w54[0];
  w65 = w54[1];
  w66 = w54[2];
  w61 = w54[3];
  /* #758: @45 = (@45+@63) */
  w45 += w63;
  /* #759: @16 = (@16-@65) */
  w16 -= w65;
  /* #760: @62 = (@62-@66) */
  w62 -= w66;
  /* #761: @59 = (@59-@61) */
  w59 -= w61;
  /* #762: @42 = vertcat(@48, @47, @38, @45, @16, @62, @59, @64, @44, @67, @41) */
  rr=w42;
  *rr++ = w48;
  *rr++ = w47;
  *rr++ = w38;
  *rr++ = w45;
  *rr++ = w16;
  *rr++ = w62;
  *rr++ = w59;
  *rr++ = w64;
  *rr++ = w44;
  *rr++ = w67;
  *rr++ = w41;
  /* #763: @68 = @42[:7] */
  for (rr=w68, cs=w42+0; cs!=w42+7; cs+=1) *rr++ = *cs;
  /* #764: (@50[6, 7, 8, 17, 18, 19, 20] = @68) */
  for (cii=casadi_s12, rr=w50, cs=w68; cii!=casadi_s12+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #765: (@50[2, 5, 8, 11, 15, 19, 23] = @68) */
  for (cii=casadi_s13, rr=w50, cs=w68; cii!=casadi_s13+7; ++cii, ++cs) rr[*cii] = *cs;
  /* #766: @48 = ones(11x1,1nz) */
  w48 = 1.;
  /* #767: {NULL, NULL, NULL, NULL, NULL, NULL, @47, NULL, NULL, NULL, NULL} = vertsplit(@48) */
  w47 = w48;
  /* #768: @48 = (-@47) */
  w48 = (- w47 );
  /* #769: @38 = vertcat(@52, @52, @52, @48) */
  rr=(&w38);
  *rr++ = w48;
  /* #770: @38 = (@38/@9) */
  w38 /= w09;
  /* #771: @54 = dense(@38) */
  casadi_densify((&w38), casadi_s14, w54, 0);
  /* #772: @38 = project(@24) */
  casadi_sparsify(w24, (&w38), casadi_s14, 0);
  /* #773: @47 = sparsity_cast(@47) */
  /* #774: @48 = dot(@38, @47) */
  w48 = casadi_dot(1, (&w38), (&w47));
  /* #775: @48 = (@48/@9) */
  w48 /= w09;
  /* #776: @23 = (@23*@48) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) *= w48;
  /* #777: @54 = (@54-@23) */
  for (i=0, rr=w54, cs=w23; i<4; ++i) (*rr++) -= (*cs++);
  /* #778: @38 = @54[0] */
  for (rr=(&w38), cs=w54+0; cs!=w54+1; cs+=1) *rr++ = *cs;
  /* #779: @45 = (@5*@38) */
  w45  = (w05*w38);
  /* #780: @16 = @54[1] */
  for (rr=(&w16), cs=w54+1; cs!=w54+2; cs+=1) *rr++ = *cs;
  /* #781: @62 = (@6*@16) */
  w62  = (w06*w16);
  /* #782: @45 = (@45-@62) */
  w45 -= w62;
  /* #783: @62 = @54[2] */
  for (rr=(&w62), cs=w54+2; cs!=w54+3; cs+=1) *rr++ = *cs;
  /* #784: @59 = (@7*@62) */
  w59  = (w07*w62);
  /* #785: @45 = (@45-@59) */
  w45 -= w59;
  /* #786: @59 = @54[3] */
  for (rr=(&w59), cs=w54+3; cs!=w54+4; cs+=1) *rr++ = *cs;
  /* #787: @64 = (@8*@59) */
  w64  = (w08*w59);
  /* #788: @45 = (@45-@64) */
  w45 -= w64;
  /* #789: @64 = (@6*@38) */
  w64  = (w06*w38);
  /* #790: @44 = (@5*@16) */
  w44  = (w05*w16);
  /* #791: @64 = (@64+@44) */
  w64 += w44;
  /* #792: @44 = (@8*@62) */
  w44  = (w08*w62);
  /* #793: @64 = (@64+@44) */
  w64 += w44;
  /* #794: @44 = (@7*@59) */
  w44  = (w07*w59);
  /* #795: @64 = (@64-@44) */
  w64 -= w44;
  /* #796: @44 = (@7*@38) */
  w44  = (w07*w38);
  /* #797: @67 = (@8*@16) */
  w67  = (w08*w16);
  /* #798: @44 = (@44-@67) */
  w44 -= w67;
  /* #799: @67 = (@5*@62) */
  w67  = (w05*w62);
  /* #800: @44 = (@44+@67) */
  w44 += w67;
  /* #801: @67 = (@6*@59) */
  w67  = (w06*w59);
  /* #802: @44 = (@44+@67) */
  w44 += w67;
  /* #803: @38 = (@8*@38) */
  w38  = (w08*w38);
  /* #804: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #805: @38 = (@38+@16) */
  w38 += w16;
  /* #806: @62 = (@6*@62) */
  w62  = (w06*w62);
  /* #807: @38 = (@38-@62) */
  w38 -= w62;
  /* #808: @59 = (@5*@59) */
  w59  = (w05*w59);
  /* #809: @38 = (@38+@59) */
  w38 += w59;
  /* #810: @23 = vertcat(@45, @64, @44, @38) */
  rr=w23;
  *rr++ = w45;
  *rr++ = w64;
  *rr++ = w44;
  *rr++ = w38;
  /* #811: @53 = (-@23) */
  for (i=0, rr=w53, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #812: @53 = (@13?@53:0) */
  for (i=0, rr=w53, cs=w53; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #813: @23 = (@11?@23:0) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #814: @53 = (@53+@23) */
  for (i=0, rr=w53, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #815: @70 = @53[1:4] */
  for (rr=w70, cs=w53+1; cs!=w53+4; cs+=1) *rr++ = *cs;
  /* #816: @45 = dot(@18, @70) */
  w45 = casadi_dot(3, w18, w70);
  /* #817: @45 = (@45/@14) */
  w45 /= w14;
  /* #818: @64 = (@45/@2) */
  w64  = (w45/w02);
  /* #819: @46 = (@46*@45) */
  w46 *= w45;
  /* #820: @44 = @53[0] */
  for (rr=(&w44), cs=w53+0; cs!=w53+1; cs+=1) *rr++ = *cs;
  /* #821: @15 = (@15*@44) */
  w15 *= w44;
  /* #822: @46 = (@46+@15) */
  w46 += w15;
  /* #823: @37 = (@37*@46) */
  w37 *= w46;
  /* #824: @64 = (@64-@37) */
  w64 -= w37;
  /* #825: @64 = (@4*@64) */
  w64  = (w04*w64);
  /* #826: @57 = (2.*@70) */
  for (i=0, rr=w57, cs=w70; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #827: @34 = (@10*@57) */
  for (i=0, rr=w34, cs=w57; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #828: @37 = (@12*@45) */
  w37  = (w12*w45);
  /* #829: @15 = (@0*@44) */
  w15  = (w00*w44);
  /* #830: @37 = (@37-@15) */
  w37 -= w15;
  /* #831: @22 = (@27*@37) */
  for (i=0, rr=w22, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w37);
  /* #832: @34 = (@34+@22) */
  for (i=0, rr=w34, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #833: @34 = (@34/@14) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w14;
  /* #834: @28 = (@28*@45) */
  for (i=0, rr=w28; i<3; ++i) (*rr++) *= w45;
  /* #835: @34 = (@34-@28) */
  for (i=0, rr=w34, cs=w28; i<3; ++i) (*rr++) -= (*cs++);
  /* #836: @28 = @34' */
  casadi_copy(w34, 3, w28);
  /* #837: @22 = mac(@28,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #838: @22 = @22' */
  /* #839: @1 = mac(@28,@31,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w28+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #840: @1 = @1' */
  /* #841: @22 = (@22+@1) */
  for (i=0, rr=w22, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #842: @1 = (@22/@14) */
  for (i=0, rr=w01, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #843: @35 = (@35*@45) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) *= w45;
  /* #844: @1 = (@1-@35) */
  for (i=0, rr=w01, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #845: @15 = dot(@27, @1) */
  w15 = casadi_dot(3, w27, w01);
  /* #846: @38 = dot(@57, @32) */
  w38 = casadi_dot(3, w57, w32);
  /* #847: @15 = (@15+@38) */
  w15 += w38;
  /* #848: @0 = (@0*@15) */
  w00 *= w15;
  /* #849: @64 = (@64+@0) */
  w64 += w00;
  /* #850: @64 = (-@64) */
  w64 = (- w64 );
  /* #851: @53 = @25; (@53[0] += @64) */
  casadi_copy(w25, 4, w53);
  for (rr=w53+0, cs=(&w64); rr!=w53+1; rr+=1) *rr += *cs++;
  /* #852: @64 = dot(@29, @22) */
  w64 = casadi_dot(3, w29, w22);
  /* #853: @34 = (@34/@14) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w14;
  /* #854: @56 = (@56*@45) */
  for (i=0, rr=w56; i<3; ++i) (*rr++) *= w45;
  /* #855: @34 = (@34-@56) */
  for (i=0, rr=w34, cs=w56; i<3; ++i) (*rr++) -= (*cs++);
  /* #856: @34 = (-@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #857: @0 = dot(@34, @30) */
  w00 = casadi_dot(3, w34, w30);
  /* #858: @64 = (@64+@0) */
  w64 += w00;
  /* #859: @44 = (@44/@2) */
  w44 /= w02;
  /* #860: @40 = (@40*@46) */
  w40 *= w46;
  /* #861: @44 = (@44-@40) */
  w44 -= w40;
  /* #862: @4 = (@4*@44) */
  w04 *= w44;
  /* #863: @12 = (@12*@15) */
  w12 *= w15;
  /* #864: @4 = (@4+@12) */
  w04 += w12;
  /* #865: @64 = (@64+@4) */
  w64 += w04;
  /* #866: @64 = (@64/@14) */
  w64 /= w14;
  /* #867: @43 = (@43*@45) */
  w43 *= w45;
  /* #868: @64 = (@64-@43) */
  w64 -= w43;
  /* #869: @18 = (@18*@64) */
  for (i=0, rr=w18; i<3; ++i) (*rr++) *= w64;
  /* #870: @70 = (@3*@70) */
  for (i=0, rr=w70, cs=w70; i<3; ++i) (*rr++)  = (w03*(*cs++));
  /* #871: @18 = (@18+@70) */
  for (i=0, rr=w18, cs=w70; i<3; ++i) (*rr++) += (*cs++);
  /* #872: @32 = (@32*@37) */
  for (i=0, rr=w32; i<3; ++i) (*rr++) *= w37;
  /* #873: @1 = (@10*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #874: @32 = (@32+@1) */
  for (i=0, rr=w32, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #875: @32 = (2.*@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #876: @18 = (@18+@32) */
  for (i=0, rr=w18, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #877: (@53[1:4] += @18) */
  for (rr=w53+1, cs=w18; rr!=w53+4; rr+=1) *rr += *cs++;
  /* #878: @23 = (@11?@53:0) */
  for (i=0, rr=w23, cs=w53; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #879: @53 = (-@53) */
  for (i=0, rr=w53, cs=w53; i<4; ++i) *rr++ = (- *cs++ );
  /* #880: @53 = (@13?@53:0) */
  for (i=0, rr=w53, cs=w53; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #881: @23 = (@23+@53) */
  for (i=0, rr=w23, cs=w53; i<4; ++i) (*rr++) += (*cs++);
  /* #882: {@13, @11, @10, @37} = vertsplit(@23) */
  w13 = w23[0];
  w11 = w23[1];
  w10 = w23[2];
  w37 = w23[3];
  /* #883: @3 = (@5*@37) */
  w03  = (w05*w37);
  /* #884: @64 = (@6*@10) */
  w64  = (w06*w10);
  /* #885: @3 = (@3+@64) */
  w03 += w64;
  /* #886: @64 = (@7*@11) */
  w64  = (w07*w11);
  /* #887: @3 = (@3-@64) */
  w03 -= w64;
  /* #888: @64 = (@8*@13) */
  w64  = (w08*w13);
  /* #889: @3 = (@3-@64) */
  w03 -= w64;
  /* #890: (@25[3] += @3) */
  for (rr=w25+3, cs=(&w03); rr!=w25+4; rr+=1) *rr += *cs++;
  /* #891: @3 = (@5*@10) */
  w03  = (w05*w10);
  /* #892: @64 = (@6*@37) */
  w64  = (w06*w37);
  /* #893: @3 = (@3-@64) */
  w03 -= w64;
  /* #894: @64 = (@8*@11) */
  w64  = (w08*w11);
  /* #895: @3 = (@3+@64) */
  w03 += w64;
  /* #896: @64 = (@7*@13) */
  w64  = (w07*w13);
  /* #897: @3 = (@3-@64) */
  w03 -= w64;
  /* #898: (@25[2] += @3) */
  for (rr=w25+2, cs=(&w03); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #899: @3 = (@7*@37) */
  w03  = (w07*w37);
  /* #900: @64 = (@8*@10) */
  w64  = (w08*w10);
  /* #901: @3 = (@3-@64) */
  w03 -= w64;
  /* #902: @64 = (@5*@11) */
  w64  = (w05*w11);
  /* #903: @3 = (@3+@64) */
  w03 += w64;
  /* #904: @64 = (@6*@13) */
  w64  = (w06*w13);
  /* #905: @3 = (@3-@64) */
  w03 -= w64;
  /* #906: (@25[1] += @3) */
  for (rr=w25+1, cs=(&w03); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #907: @8 = (@8*@37) */
  w08 *= w37;
  /* #908: @7 = (@7*@10) */
  w07 *= w10;
  /* #909: @8 = (@8+@7) */
  w08 += w07;
  /* #910: @6 = (@6*@11) */
  w06 *= w11;
  /* #911: @8 = (@8+@6) */
  w08 += w06;
  /* #912: @5 = (@5*@13) */
  w05 *= w13;
  /* #913: @8 = (@8+@5) */
  w08 += w05;
  /* #914: (@25[0] += @8) */
  for (rr=w25+0, cs=(&w08); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #915: @8 = dot(@26, @25) */
  w08 = casadi_dot(4, w26, w25);
  /* #916: @54 = (@54/@9) */
  for (i=0, rr=w54; i<4; ++i) (*rr++) /= w09;
  /* #917: @55 = (@55*@48) */
  for (i=0, rr=w55; i<4; ++i) (*rr++) *= w48;
  /* #918: @54 = (@54-@55) */
  for (i=0, rr=w54, cs=w55; i<4; ++i) (*rr++) -= (*cs++);
  /* #919: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<4; ++i) *rr++ = (- *cs++ );
  /* #920: @5 = dot(@54, @36) */
  w05 = casadi_dot(4, w54, w36);
  /* #921: @8 = (@8+@5) */
  w08 += w05;
  /* #922: @8 = (@8/@9) */
  w08 /= w09;
  /* #923: @49 = (@49*@48) */
  w49 *= w48;
  /* #924: @8 = (@8-@49) */
  w08 -= w49;
  /* #925: @24 = (@24*@8) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) *= w08;
  /* #926: @39 = (@39*@47) */
  w39 *= w47;
  /* #927: @54 = dense(@39) */
  casadi_densify((&w39), casadi_s14, w54, 0);
  /* #928: @24 = (@24+@54) */
  for (i=0, rr=w24, cs=w54; i<4; ++i) (*rr++) += (*cs++);
  /* #929: (@19[3:7] += @24) */
  for (rr=w19+3, cs=w24; rr!=w19+7; rr+=1) *rr += *cs++;
  /* #930: {@39, @47, @8, @49, @5, @13, @6, @11, @7, @10, @37} = vertsplit(@19) */
  w39 = w19[0];
  w47 = w19[1];
  w08 = w19[2];
  w49 = w19[3];
  w05 = w19[4];
  w13 = w19[5];
  w06 = w19[6];
  w11 = w19[7];
  w07 = w19[8];
  w10 = w19[9];
  w37 = w19[10];
  /* #931: @25 = (@25/@9) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) /= w09;
  /* #932: @33 = (@33*@48) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) *= w48;
  /* #933: @25 = (@25-@33) */
  for (i=0, rr=w25, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #934: {@48, @9, @3, @64} = vertsplit(@25) */
  w48 = w25[0];
  w09 = w25[1];
  w03 = w25[2];
  w64 = w25[3];
  /* #935: @48 = (@48+@49) */
  w48 += w49;
  /* #936: @5 = (@5-@9) */
  w05 -= w09;
  /* #937: @13 = (@13-@3) */
  w13 -= w03;
  /* #938: @6 = (@6-@64) */
  w06 -= w64;
  /* #939: @19 = vertcat(@39, @47, @8, @48, @5, @13, @6, @11, @7, @10, @37) */
  rr=w19;
  *rr++ = w39;
  *rr++ = w47;
  *rr++ = w08;
  *rr++ = w48;
  *rr++ = w05;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w37;
  /* #940: @25 = @19[3:7] */
  for (rr=w25, cs=w19+3; cs!=w19+7; cs+=1) *rr++ = *cs;
  /* #941: (@50[21:25] = @25) */
  for (rr=w50+21, cs=w25; rr!=w50+25; rr+=1) *rr = *cs++;
  /* #942: (@50[12:28:4] = @25) */
  for (rr=w50+12, cs=w25; rr!=w50+28; rr+=4) *rr = *cs++;
  /* #943: @71 = @50' */
  casadi_trans(w50,casadi_s15, w71, casadi_s15, iw);
  /* #944: output[2][0] = @71 */
  casadi_copy(w71, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    case 1: return casadi_s17;
    case 2: return casadi_s17;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s16;
    case 2: return casadi_s15;
    case 3: return casadi_s20;
    case 4: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 12;
  if (sz_w) *sz_w = 242;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 16*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 12*sizeof(casadi_int);
  if (sz_w) *sz_w = 242*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
