/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {1, 4, 0, 1, 2, 3, 4, 0,
  0, 0, 0};
static const casadi_int casadi_s1[23] = 
  {4, 4, 0, 4, 8, 12, 16, 0,
  1, 2, 3, 0, 1, 2, 3, 0,
  1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s4[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s5[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s7[11] = 
  {0, 1, 2, 3, 16, 17, 18, 25,
  26, 27, 28};
static const casadi_int casadi_s8[11] = 
  {0, 4, 8, 12, 16, 19, 22, 25,
  29, 33, 37};
static const casadi_int casadi_s9[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s10[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s11[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s12[11] = 
  {4, 5, 6, 7, 19, 20, 21, 29,
  30, 31, 32};
static const casadi_int casadi_s13[11] = 
  {1, 5, 9, 13, 17, 20, 23, 26,
  30, 34, 38};
static const casadi_int casadi_s14[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s15[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s16[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s17[11] = 
  {8, 9, 10, 11, 22, 23, 24, 33,
  34, 35, 36};
static const casadi_int casadi_s18[11] = 
  {2, 6, 10, 14, 18, 21, 24, 27,
  31, 35, 39};
static const casadi_int casadi_s19[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s20[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s21[59] = 
  {15, 15, 0, 4, 8, 12, 16, 19,
  22, 25, 29, 33, 37, 41, 41, 41,
  41, 41, 0, 1, 2, 3, 0, 1,
  2, 3, 0, 1, 2, 3, 0, 1,
  2, 3, 4, 5, 6, 4, 5, 6,
  4, 5, 6, 7, 8, 9, 10, 7,
  8, 9, 10, 7, 8, 9, 10, 7,
  8, 9, 10};
static const casadi_int casadi_s22[3] = {11, 1, 1};
static const casadi_int casadi_s23[3] = {4, 1, 1};
static const casadi_int casadi_s24[3] = {0, 1, 1};
static const casadi_int casadi_s25[3] = {15, 1, 1};
static const casadi_int casadi_s26[3] = {1, 1, 1};
static const casadi_int casadi_s27[3] = {0, 0, 1};
static const casadi_int casadi_s28[3] = {0, 15, 1};

/* Drone_ode_cost_ext_cost_fun_jac_hess:(i0[11],i1[4],i2[0],i3[15])->(o0,o1[15],o2[15x15,41nz],o3[],o4[0x15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *tt, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w19=w+38, *w20=w+49, *w21=w+52;
  casadi_real *w22=w+61, *w23=w+64, *w24=w+68, *w25=w+72, *w26=w+76, *w27=w+92, *w28=w+96, *w29=w+100, *w30=w+104, *w31=w+108, *w32=w+111, *w33=w+114;
  casadi_real *w34=w+117, *w35=w+120, *w36=w+136, *w37=w+145, *w38=w+148, *w39=w+151, w40, w41, w42, w43, w44, *w45=w+159;
  casadi_real w46, w47, w48, w49, w50, w51, w52, *w53=w+177, *w54=w+218, *w56=w+225, *w57=w+229, w58;
  casadi_real w59, w60, *w61=w+236, *w62=w+240, *w63=w+243, *w64=w+246, w65, w66, *w67=w+251, w68, w69, w70;
  casadi_real w71, w72, w73, w74, *w75=w+262, *w76=w+265, *w77=w+267, *w78=w+275;
  const casadi_int *cii;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #20: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #21: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #22: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #23: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #24: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #25: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #26: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #27: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #28: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #29: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #30: @19 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #31: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #32: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #34: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #35: @2 = 1.1 */
  w02 = 1.1000000000000001e+00;
  /* #36: (@21[0] = @2) */
  for (rr=w21+0, cs=(&w02); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #37: (@21[4] = @2) */
  for (rr=w21+4, cs=(&w02); rr!=w21+5; rr+=1) *rr = *cs++;
  /* #38: (@21[8] = @2) */
  for (rr=w21+8, cs=(&w02); rr!=w21+9; rr+=1) *rr = *cs++;
  /* #39: @22 = mac(@20,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@22,@18,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #42: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #43: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #44: @13 = input[1][2] */
  w13 = arg[1] ? arg[1][2] : 0;
  /* #45: @14 = input[1][3] */
  w14 = arg[1] ? arg[1][3] : 0;
  /* #46: @24 = vertcat(@3, @4, @13, @14) */
  rr=w24;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w13;
  *rr++ = w14;
  /* #47: @25 = @24' */
  casadi_copy(w24, 4, w25);
  /* #48: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #49: @3 = 1 */
  w03 = 1.;
  /* #50: (@26[0] = @3) */
  for (rr=w26+0, cs=(&w03); rr!=w26+1; rr+=1) *rr = *cs++;
  /* #51: (@26[5] = @3) */
  for (rr=w26+5, cs=(&w03); rr!=w26+6; rr+=1) *rr = *cs++;
  /* #52: (@26[10] = @3) */
  for (rr=w26+10, cs=(&w03); rr!=w26+11; rr+=1) *rr = *cs++;
  /* #53: (@26[15] = @3) */
  for (rr=w26+15, cs=(&w03); rr!=w26+16; rr+=1) *rr = *cs++;
  /* #54: @27 = mac(@25,@26,@23) */
  casadi_copy(w23, 4, w27);
  for (i=0, rr=w27; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w26+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #55: @3 = mac(@27,@24,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w24+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #56: @2 = (@2+@3) */
  w02 += w03;
  /* #57: @10 = (-@10) */
  w10 = (- w10 );
  /* #58: @11 = (-@11) */
  w11 = (- w11 );
  /* #59: @12 = (-@12) */
  w12 = (- w12 );
  /* #60: @24 = vertcat(@9, @10, @11, @12) */
  rr=w24;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #61: @28 = @19[3:7] */
  for (rr=w28, cs=w19+3; cs!=w19+7; cs+=1) *rr++ = *cs;
  /* #62: @9 = ||@28||_F */
  w09 = casadi_norm_2(4, w28);
  /* #63: @24 = (@24/@9) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w09;
  /* #64: @10 = @24[0] */
  for (rr=(&w10), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #65: @11 = (@10*@5) */
  w11  = (w10*w05);
  /* #66: @12 = @24[1] */
  for (rr=(&w12), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #67: @3 = (@12*@6) */
  w03  = (w12*w06);
  /* #68: @11 = (@11-@3) */
  w11 -= w03;
  /* #69: @3 = @24[2] */
  for (rr=(&w03), cs=w24+2; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #70: @4 = (@3*@7) */
  w04  = (w03*w07);
  /* #71: @11 = (@11-@4) */
  w11 -= w04;
  /* #72: @4 = @24[3] */
  for (rr=(&w04), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #73: @13 = (@4*@8) */
  w13  = (w04*w08);
  /* #74: @11 = (@11-@13) */
  w11 -= w13;
  /* #75: @13 = (@11<@0) */
  w13  = (w11<w00);
  /* #76: @14 = (@10*@6) */
  w14  = (w10*w06);
  /* #77: @15 = (@12*@5) */
  w15  = (w12*w05);
  /* #78: @14 = (@14+@15) */
  w14 += w15;
  /* #79: @15 = (@3*@8) */
  w15  = (w03*w08);
  /* #80: @14 = (@14+@15) */
  w14 += w15;
  /* #81: @15 = (@4*@7) */
  w15  = (w04*w07);
  /* #82: @14 = (@14-@15) */
  w14 -= w15;
  /* #83: @15 = (@10*@7) */
  w15  = (w10*w07);
  /* #84: @16 = (@12*@8) */
  w16  = (w12*w08);
  /* #85: @15 = (@15-@16) */
  w15 -= w16;
  /* #86: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #87: @15 = (@15+@16) */
  w15 += w16;
  /* #88: @16 = (@4*@6) */
  w16  = (w04*w06);
  /* #89: @15 = (@15+@16) */
  w15 += w16;
  /* #90: @10 = (@10*@8) */
  w10 *= w08;
  /* #91: @12 = (@12*@7) */
  w12 *= w07;
  /* #92: @10 = (@10+@12) */
  w10 += w12;
  /* #93: @3 = (@3*@6) */
  w03 *= w06;
  /* #94: @10 = (@10-@3) */
  w10 -= w03;
  /* #95: @4 = (@4*@5) */
  w04 *= w05;
  /* #96: @10 = (@10+@4) */
  w10 += w04;
  /* #97: @29 = vertcat(@11, @14, @15, @10) */
  rr=w29;
  *rr++ = w11;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w10;
  /* #98: @30 = (-@29) */
  for (i=0, rr=w30, cs=w29; i<4; ++i) *rr++ = (- *cs++ );
  /* #99: @30 = (@13?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #100: @11 = (!@13) */
  w11 = (! w13 );
  /* #101: @29 = (@11?@29:0) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #102: @30 = (@30+@29) */
  for (i=0, rr=w30, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #103: @18 = @30[1:4] */
  for (rr=w18, cs=w30+1; cs!=w30+4; cs+=1) *rr++ = *cs;
  /* #104: @31 = (2.*@18) */
  for (i=0, rr=w31, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #105: @14 = ||@18||_F */
  w14 = casadi_norm_2(3, w18);
  /* #106: @15 = @30[0] */
  for (rr=(&w15), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #107: @10 = atan2(@14,@15) */
  w10  = atan2(w14,w15);
  /* #108: @32 = (@31*@10) */
  for (i=0, rr=w32, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w10);
  /* #109: @32 = (@32/@14) */
  for (i=0, rr=w32; i<3; ++i) (*rr++) /= w14;
  /* #110: @33 = @32' */
  casadi_copy(w32, 3, w33);
  /* #111: @34 = mac(@33,@21,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #112: @0 = mac(@34,@32,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w32+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #113: @2 = (@2+@0) */
  w02 += w00;
  /* #114: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #115: @27 = @27' */
  /* #116: @35 = @26' */
  for (i=0, rr=w35, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #117: @30 = mac(@25,@35,@23) */
  casadi_copy(w23, 4, w30);
  for (i=0, rr=w30; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w35+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #118: @30 = @30' */
  /* #119: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #120: {@2, @0, @4, @3} = vertsplit(@27) */
  w02 = w27[0];
  w00 = w27[1];
  w04 = w27[2];
  w03 = w27[3];
  /* #121: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #122: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #123: output[1][2] = @4 */
  if (res[1]) res[1][2] = w04;
  /* #124: output[1][3] = @3 */
  if (res[1]) res[1][3] = w03;
  /* #125: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #126: @24 = (@24/@9) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w09;
  /* #127: @27 = (-@24) */
  for (i=0, rr=w27, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #128: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #129: @3 = sq(@14) */
  w03 = casadi_sq( w14 );
  /* #130: @4 = sq(@15) */
  w04 = casadi_sq( w15 );
  /* #131: @3 = (@3+@4) */
  w03 += w04;
  /* #132: @4 = (@14/@3) */
  w04  = (w14/w03);
  /* #133: @34 = @34' */
  /* #134: @36 = @21' */
  for (i=0, rr=w36, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #135: @37 = mac(@33,@36,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #136: @37 = @37' */
  /* #137: @34 = (@34+@37) */
  for (i=0, rr=w34, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #138: @37 = (@34/@14) */
  for (i=0, rr=w37, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #139: @0 = dot(@31, @37) */
  w00 = casadi_dot(3, w31, w37);
  /* #140: @2 = (@4*@0) */
  w02  = (w04*w00);
  /* #141: @2 = (-@2) */
  w02 = (- w02 );
  /* #142: @25 = @30; (@25[0] += @2) */
  casadi_copy(w30, 4, w25);
  for (rr=w25+0, cs=(&w02); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #143: @32 = (@32/@14) */
  for (i=0, rr=w32; i<3; ++i) (*rr++) /= w14;
  /* #144: @33 = (-@32) */
  for (i=0, rr=w33, cs=w32; i<3; ++i) *rr++ = (- *cs++ );
  /* #145: @2 = dot(@33, @34) */
  w02 = casadi_dot(3, w33, w34);
  /* #146: @12 = (@15/@3) */
  w12  = (w15/w03);
  /* #147: @16 = (@12*@0) */
  w16  = (w12*w00);
  /* #148: @2 = (@2+@16) */
  w02 += w16;
  /* #149: @2 = (@2/@14) */
  w02 /= w14;
  /* #150: @38 = (@2*@18) */
  for (i=0, rr=w38, cs=w18; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #151: @39 = (@10*@37) */
  for (i=0, rr=w39, cs=w37; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #152: @39 = (2.*@39) */
  for (i=0, rr=w39, cs=w39; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #153: @38 = (@38+@39) */
  for (i=0, rr=w38, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #154: (@25[1:4] += @38) */
  for (rr=w25+1, cs=w38; rr!=w25+4; rr+=1) *rr += *cs++;
  /* #155: @29 = (@11?@25:0) */
  for (i=0, rr=w29, cs=w25; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #156: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) *rr++ = (- *cs++ );
  /* #157: @25 = (@13?@25:0) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #158: @29 = (@29+@25) */
  for (i=0, rr=w29, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #159: {@16, @40, @41, @42} = vertsplit(@29) */
  w16 = w29[0];
  w40 = w29[1];
  w41 = w29[2];
  w42 = w29[3];
  /* #160: @43 = (@5*@42) */
  w43  = (w05*w42);
  /* #161: @44 = (@6*@41) */
  w44  = (w06*w41);
  /* #162: @43 = (@43+@44) */
  w43 += w44;
  /* #163: @44 = (@7*@40) */
  w44  = (w07*w40);
  /* #164: @43 = (@43-@44) */
  w43 -= w44;
  /* #165: @44 = (@8*@16) */
  w44  = (w08*w16);
  /* #166: @43 = (@43-@44) */
  w43 -= w44;
  /* #167: @29 = @30; (@29[3] += @43) */
  casadi_copy(w30, 4, w29);
  for (rr=w29+3, cs=(&w43); rr!=w29+4; rr+=1) *rr += *cs++;
  /* #168: @43 = (@5*@41) */
  w43  = (w05*w41);
  /* #169: @44 = (@6*@42) */
  w44  = (w06*w42);
  /* #170: @43 = (@43-@44) */
  w43 -= w44;
  /* #171: @44 = (@8*@40) */
  w44  = (w08*w40);
  /* #172: @43 = (@43+@44) */
  w43 += w44;
  /* #173: @44 = (@7*@16) */
  w44  = (w07*w16);
  /* #174: @43 = (@43-@44) */
  w43 -= w44;
  /* #175: (@29[2] += @43) */
  for (rr=w29+2, cs=(&w43); rr!=w29+3; rr+=1) *rr += *cs++;
  /* #176: @43 = (@7*@42) */
  w43  = (w07*w42);
  /* #177: @44 = (@8*@41) */
  w44  = (w08*w41);
  /* #178: @43 = (@43-@44) */
  w43 -= w44;
  /* #179: @44 = (@5*@40) */
  w44  = (w05*w40);
  /* #180: @43 = (@43+@44) */
  w43 += w44;
  /* #181: @44 = (@6*@16) */
  w44  = (w06*w16);
  /* #182: @43 = (@43-@44) */
  w43 -= w44;
  /* #183: (@29[1] += @43) */
  for (rr=w29+1, cs=(&w43); rr!=w29+2; rr+=1) *rr += *cs++;
  /* #184: @42 = (@8*@42) */
  w42  = (w08*w42);
  /* #185: @41 = (@7*@41) */
  w41  = (w07*w41);
  /* #186: @42 = (@42+@41) */
  w42 += w41;
  /* #187: @40 = (@6*@40) */
  w40  = (w06*w40);
  /* #188: @42 = (@42+@40) */
  w42 += w40;
  /* #189: @16 = (@5*@16) */
  w16  = (w05*w16);
  /* #190: @42 = (@42+@16) */
  w42 += w16;
  /* #191: (@29[0] += @42) */
  for (rr=w29+0, cs=(&w42); rr!=w29+1; rr+=1) *rr += *cs++;
  /* #192: @42 = dot(@27, @29) */
  w42 = casadi_dot(4, w27, w29);
  /* #193: @42 = (@42/@9) */
  w42 /= w09;
  /* #194: @25 = (@42*@28) */
  for (i=0, rr=w25, cs=w28; i<4; ++i) (*rr++)  = (w42*(*cs++));
  /* #195: @45 = @19; (@45[3:7] += @25) */
  casadi_copy(w19, 11, w45);
  for (rr=w45+3, cs=w25; rr!=w45+7; rr+=1) *rr += *cs++;
  /* #196: @22 = @22' */
  /* #197: @38 = mac(@20,@36,@1) */
  casadi_copy(w01, 3, w38);
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #198: @38 = @38' */
  /* #199: @22 = (@22+@38) */
  for (i=0, rr=w22, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #200: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #201: (@45[:3] += @22) */
  for (rr=w45+0, cs=w22; rr!=w45+3; rr+=1) *rr += *cs++;
  /* #202: {@16, @40, @41, @43, @44, @46, @47, @48, @49, @50, @51} = vertsplit(@45) */
  w16 = w45[0];
  w40 = w45[1];
  w41 = w45[2];
  w43 = w45[3];
  w44 = w45[4];
  w46 = w45[5];
  w47 = w45[6];
  w48 = w45[7];
  w49 = w45[8];
  w50 = w45[9];
  w51 = w45[10];
  /* #203: output[1][4] = @16 */
  if (res[1]) res[1][4] = w16;
  /* #204: output[1][5] = @40 */
  if (res[1]) res[1][5] = w40;
  /* #205: output[1][6] = @41 */
  if (res[1]) res[1][6] = w41;
  /* #206: @25 = (@29/@9) */
  for (i=0, rr=w25, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)/w09);
  /* #207: {@41, @40, @16, @52} = vertsplit(@25) */
  w41 = w25[0];
  w40 = w25[1];
  w16 = w25[2];
  w52 = w25[3];
  /* #208: @41 = (@41+@43) */
  w41 += w43;
  /* #209: output[1][7] = @41 */
  if (res[1]) res[1][7] = w41;
  /* #210: @44 = (@44-@40) */
  w44 -= w40;
  /* #211: output[1][8] = @44 */
  if (res[1]) res[1][8] = w44;
  /* #212: @46 = (@46-@16) */
  w46 -= w16;
  /* #213: output[1][9] = @46 */
  if (res[1]) res[1][9] = w46;
  /* #214: @47 = (@47-@52) */
  w47 -= w52;
  /* #215: output[1][10] = @47 */
  if (res[1]) res[1][10] = w47;
  /* #216: output[1][11] = @48 */
  if (res[1]) res[1][11] = w48;
  /* #217: output[1][12] = @49 */
  if (res[1]) res[1][12] = w49;
  /* #218: output[1][13] = @50 */
  if (res[1]) res[1][13] = w50;
  /* #219: output[1][14] = @51 */
  if (res[1]) res[1][14] = w51;
  /* #220: @53 = zeros(15x15,41nz) */
  casadi_clear(w53, 41);
  /* #221: @54 = ones(15x1,7nz) */
  casadi_fill(w54, 7, 1.);
  /* #222: {@51, NULL, NULL, NULL, @50, NULL, NULL, @49, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@54) */
  w51 = w54[0];
  w50 = w54[1];
  w49 = w54[2];
  /* #223: @55 = 00 */
  /* #224: @48 = vertcat(@51, @55, @55, @55) */
  rr=(&w48);
  *rr++ = w51;
  /* #225: @48 = @48' */
  /* #226: @56 = mac(@48,@26,@23) */
  casadi_copy(w23, 4, w56);
  casadi_mtimes((&w48), casadi_s2, w26, casadi_s1, w56, casadi_s0, w, 0);
  /* #227: @56 = @56' */
  /* #228: @57 = mac(@48,@35,@23) */
  casadi_copy(w23, 4, w57);
  casadi_mtimes((&w48), casadi_s2, w35, casadi_s1, w57, casadi_s0, w, 0);
  /* #229: @57 = @57' */
  /* #230: @56 = (@56+@57) */
  for (i=0, rr=w56, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #231: {@48, @51, @47, @52} = vertsplit(@56) */
  w48 = w56[0];
  w51 = w56[1];
  w47 = w56[2];
  w52 = w56[3];
  /* #232: @46 = vertcat(@49, @55, @55, @55) */
  rr=(&w46);
  *rr++ = w49;
  /* #233: @46 = (@46/@9) */
  w46 /= w09;
  /* #234: @56 = dense(@46) */
  casadi_densify((&w46), casadi_s3, w56, 0);
  /* #235: @46 = project(@28) */
  casadi_sparsify(w28, (&w46), casadi_s3, 0);
  /* #236: @49 = sparsity_cast(@49) */
  /* #237: @16 = dot(@46, @49) */
  w16 = casadi_dot(1, (&w46), (&w49));
  /* #238: @16 = (@16/@9) */
  w16 /= w09;
  /* #239: @57 = (@24*@16) */
  for (i=0, rr=w57, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #240: @56 = (@56-@57) */
  for (i=0, rr=w56, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #241: @46 = @56[0] */
  for (rr=(&w46), cs=w56+0; cs!=w56+1; cs+=1) *rr++ = *cs;
  /* #242: @44 = (@5*@46) */
  w44  = (w05*w46);
  /* #243: @40 = @56[1] */
  for (rr=(&w40), cs=w56+1; cs!=w56+2; cs+=1) *rr++ = *cs;
  /* #244: @41 = (@6*@40) */
  w41  = (w06*w40);
  /* #245: @44 = (@44-@41) */
  w44 -= w41;
  /* #246: @41 = @56[2] */
  for (rr=(&w41), cs=w56+2; cs!=w56+3; cs+=1) *rr++ = *cs;
  /* #247: @43 = (@7*@41) */
  w43  = (w07*w41);
  /* #248: @44 = (@44-@43) */
  w44 -= w43;
  /* #249: @43 = @56[3] */
  for (rr=(&w43), cs=w56+3; cs!=w56+4; cs+=1) *rr++ = *cs;
  /* #250: @58 = (@8*@43) */
  w58  = (w08*w43);
  /* #251: @44 = (@44-@58) */
  w44 -= w58;
  /* #252: @58 = (@6*@46) */
  w58  = (w06*w46);
  /* #253: @59 = (@5*@40) */
  w59  = (w05*w40);
  /* #254: @58 = (@58+@59) */
  w58 += w59;
  /* #255: @59 = (@8*@41) */
  w59  = (w08*w41);
  /* #256: @58 = (@58+@59) */
  w58 += w59;
  /* #257: @59 = (@7*@43) */
  w59  = (w07*w43);
  /* #258: @58 = (@58-@59) */
  w58 -= w59;
  /* #259: @59 = (@7*@46) */
  w59  = (w07*w46);
  /* #260: @60 = (@8*@40) */
  w60  = (w08*w40);
  /* #261: @59 = (@59-@60) */
  w59 -= w60;
  /* #262: @60 = (@5*@41) */
  w60  = (w05*w41);
  /* #263: @59 = (@59+@60) */
  w59 += w60;
  /* #264: @60 = (@6*@43) */
  w60  = (w06*w43);
  /* #265: @59 = (@59+@60) */
  w59 += w60;
  /* #266: @46 = (@8*@46) */
  w46  = (w08*w46);
  /* #267: @40 = (@7*@40) */
  w40  = (w07*w40);
  /* #268: @46 = (@46+@40) */
  w46 += w40;
  /* #269: @41 = (@6*@41) */
  w41  = (w06*w41);
  /* #270: @46 = (@46-@41) */
  w46 -= w41;
  /* #271: @43 = (@5*@43) */
  w43  = (w05*w43);
  /* #272: @46 = (@46+@43) */
  w46 += w43;
  /* #273: @57 = vertcat(@44, @58, @59, @46) */
  rr=w57;
  *rr++ = w44;
  *rr++ = w58;
  *rr++ = w59;
  *rr++ = w46;
  /* #274: @61 = (-@57) */
  for (i=0, rr=w61, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #275: @61 = (@13?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #276: @57 = (@11?@57:0) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #277: @61 = (@61+@57) */
  for (i=0, rr=w61, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #278: @22 = @61[1:4] */
  for (rr=w22, cs=w61+1; cs!=w61+4; cs+=1) *rr++ = *cs;
  /* #279: @44 = dot(@18, @22) */
  w44 = casadi_dot(3, w18, w22);
  /* #280: @44 = (@44/@14) */
  w44 /= w14;
  /* #281: @58 = (@44/@3) */
  w58  = (w44/w03);
  /* #282: @59 = (@4/@3) */
  w59  = (w04/w03);
  /* #283: @46 = (2.*@14) */
  w46 = (2.* w14 );
  /* #284: @43 = (@46*@44) */
  w43  = (w46*w44);
  /* #285: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #286: @41 = @61[0] */
  for (rr=(&w41), cs=w61+0; cs!=w61+1; cs+=1) *rr++ = *cs;
  /* #287: @40 = (@15*@41) */
  w40  = (w15*w41);
  /* #288: @43 = (@43+@40) */
  w43 += w40;
  /* #289: @40 = (@59*@43) */
  w40  = (w59*w43);
  /* #290: @58 = (@58-@40) */
  w58 -= w40;
  /* #291: @58 = (@0*@58) */
  w58  = (w00*w58);
  /* #292: @38 = (2.*@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #293: @20 = (@10*@38) */
  for (i=0, rr=w20, cs=w38; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #294: @40 = (@12*@44) */
  w40  = (w12*w44);
  /* #295: @60 = (@4*@41) */
  w60  = (w04*w41);
  /* #296: @40 = (@40-@60) */
  w40 -= w60;
  /* #297: @39 = (@31*@40) */
  for (i=0, rr=w39, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w40);
  /* #298: @20 = (@20+@39) */
  for (i=0, rr=w20, cs=w39; i<3; ++i) (*rr++) += (*cs++);
  /* #299: @20 = (@20/@14) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w14;
  /* #300: @39 = (@32*@44) */
  for (i=0, rr=w39, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #301: @20 = (@20-@39) */
  for (i=0, rr=w20, cs=w39; i<3; ++i) (*rr++) -= (*cs++);
  /* #302: @39 = @20' */
  casadi_copy(w20, 3, w39);
  /* #303: @62 = mac(@39,@21,@1) */
  casadi_copy(w01, 3, w62);
  for (i=0, rr=w62; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w39+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #304: @62 = @62' */
  /* #305: @63 = mac(@39,@36,@1) */
  casadi_copy(w01, 3, w63);
  for (i=0, rr=w63; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w39+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #306: @63 = @63' */
  /* #307: @62 = (@62+@63) */
  for (i=0, rr=w62, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #308: @63 = (@62/@14) */
  for (i=0, rr=w63, cr=w62; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #309: @39 = (@37/@14) */
  for (i=0, rr=w39, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #310: @64 = (@39*@44) */
  for (i=0, rr=w64, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #311: @63 = (@63-@64) */
  for (i=0, rr=w63, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #312: @60 = dot(@31, @63) */
  w60 = casadi_dot(3, w31, w63);
  /* #313: @65 = dot(@38, @37) */
  w65 = casadi_dot(3, w38, w37);
  /* #314: @60 = (@60+@65) */
  w60 += w65;
  /* #315: @65 = (@4*@60) */
  w65  = (w04*w60);
  /* #316: @58 = (@58+@65) */
  w58 += w65;
  /* #317: @58 = (-@58) */
  w58 = (- w58 );
  /* #318: @61 = @30; (@61[0] += @58) */
  casadi_copy(w30, 4, w61);
  for (rr=w61+0, cs=(&w58); rr!=w61+1; rr+=1) *rr += *cs++;
  /* #319: @58 = dot(@33, @62) */
  w58 = casadi_dot(3, w33, w62);
  /* #320: @20 = (@20/@14) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w14;
  /* #321: @62 = (@32/@14) */
  for (i=0, rr=w62, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #322: @38 = (@62*@44) */
  for (i=0, rr=w38, cr=w62; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #323: @20 = (@20-@38) */
  for (i=0, rr=w20, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #324: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #325: @65 = dot(@20, @34) */
  w65 = casadi_dot(3, w20, w34);
  /* #326: @58 = (@58+@65) */
  w58 += w65;
  /* #327: @41 = (@41/@3) */
  w41 /= w03;
  /* #328: @65 = (@12/@3) */
  w65  = (w12/w03);
  /* #329: @43 = (@65*@43) */
  w43  = (w65*w43);
  /* #330: @41 = (@41-@43) */
  w41 -= w43;
  /* #331: @41 = (@0*@41) */
  w41  = (w00*w41);
  /* #332: @60 = (@12*@60) */
  w60  = (w12*w60);
  /* #333: @41 = (@41+@60) */
  w41 += w60;
  /* #334: @58 = (@58+@41) */
  w58 += w41;
  /* #335: @58 = (@58/@14) */
  w58 /= w14;
  /* #336: @41 = (@2/@14) */
  w41  = (w02/w14);
  /* #337: @44 = (@41*@44) */
  w44  = (w41*w44);
  /* #338: @58 = (@58-@44) */
  w58 -= w44;
  /* #339: @20 = (@18*@58) */
  for (i=0, rr=w20, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w58);
  /* #340: @22 = (@2*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #341: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #342: @22 = (@37*@40) */
  for (i=0, rr=w22, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w40);
  /* #343: @63 = (@10*@63) */
  for (i=0, rr=w63, cs=w63; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #344: @22 = (@22+@63) */
  for (i=0, rr=w22, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #345: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #346: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #347: (@61[1:4] += @20) */
  for (rr=w61+1, cs=w20; rr!=w61+4; rr+=1) *rr += *cs++;
  /* #348: @57 = (@11?@61:0) */
  for (i=0, rr=w57, cs=w61; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #349: @61 = (-@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) *rr++ = (- *cs++ );
  /* #350: @61 = (@13?@61:0) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #351: @57 = (@57+@61) */
  for (i=0, rr=w57, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #352: {@40, @58, @44, @60} = vertsplit(@57) */
  w40 = w57[0];
  w58 = w57[1];
  w44 = w57[2];
  w60 = w57[3];
  /* #353: @43 = (@5*@60) */
  w43  = (w05*w60);
  /* #354: @66 = (@6*@44) */
  w66  = (w06*w44);
  /* #355: @43 = (@43+@66) */
  w43 += w66;
  /* #356: @66 = (@7*@58) */
  w66  = (w07*w58);
  /* #357: @43 = (@43-@66) */
  w43 -= w66;
  /* #358: @66 = (@8*@40) */
  w66  = (w08*w40);
  /* #359: @43 = (@43-@66) */
  w43 -= w66;
  /* #360: @57 = @30; (@57[3] += @43) */
  casadi_copy(w30, 4, w57);
  for (rr=w57+3, cs=(&w43); rr!=w57+4; rr+=1) *rr += *cs++;
  /* #361: @43 = (@5*@44) */
  w43  = (w05*w44);
  /* #362: @66 = (@6*@60) */
  w66  = (w06*w60);
  /* #363: @43 = (@43-@66) */
  w43 -= w66;
  /* #364: @66 = (@8*@58) */
  w66  = (w08*w58);
  /* #365: @43 = (@43+@66) */
  w43 += w66;
  /* #366: @66 = (@7*@40) */
  w66  = (w07*w40);
  /* #367: @43 = (@43-@66) */
  w43 -= w66;
  /* #368: (@57[2] += @43) */
  for (rr=w57+2, cs=(&w43); rr!=w57+3; rr+=1) *rr += *cs++;
  /* #369: @43 = (@7*@60) */
  w43  = (w07*w60);
  /* #370: @66 = (@8*@44) */
  w66  = (w08*w44);
  /* #371: @43 = (@43-@66) */
  w43 -= w66;
  /* #372: @66 = (@5*@58) */
  w66  = (w05*w58);
  /* #373: @43 = (@43+@66) */
  w43 += w66;
  /* #374: @66 = (@6*@40) */
  w66  = (w06*w40);
  /* #375: @43 = (@43-@66) */
  w43 -= w66;
  /* #376: (@57[1] += @43) */
  for (rr=w57+1, cs=(&w43); rr!=w57+2; rr+=1) *rr += *cs++;
  /* #377: @60 = (@8*@60) */
  w60  = (w08*w60);
  /* #378: @44 = (@7*@44) */
  w44  = (w07*w44);
  /* #379: @60 = (@60+@44) */
  w60 += w44;
  /* #380: @58 = (@6*@58) */
  w58  = (w06*w58);
  /* #381: @60 = (@60+@58) */
  w60 += w58;
  /* #382: @40 = (@5*@40) */
  w40  = (w05*w40);
  /* #383: @60 = (@60+@40) */
  w60 += w40;
  /* #384: (@57[0] += @60) */
  for (rr=w57+0, cs=(&w60); rr!=w57+1; rr+=1) *rr += *cs++;
  /* #385: @60 = dot(@27, @57) */
  w60 = casadi_dot(4, w27, w57);
  /* #386: @56 = (@56/@9) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) /= w09;
  /* #387: @61 = (@24/@9) */
  for (i=0, rr=w61, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)/w09);
  /* #388: @67 = (@61*@16) */
  for (i=0, rr=w67, cr=w61; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #389: @56 = (@56-@67) */
  for (i=0, rr=w56, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #390: @56 = (-@56) */
  for (i=0, rr=w56, cs=w56; i<4; ++i) *rr++ = (- *cs++ );
  /* #391: @40 = dot(@56, @29) */
  w40 = casadi_dot(4, w56, w29);
  /* #392: @60 = (@60+@40) */
  w60 += w40;
  /* #393: @60 = (@60/@9) */
  w60 /= w09;
  /* #394: @40 = (@42/@9) */
  w40  = (w42/w09);
  /* #395: @58 = (@40*@16) */
  w58  = (w40*w16);
  /* #396: @60 = (@60-@58) */
  w60 -= w58;
  /* #397: @56 = (@28*@60) */
  for (i=0, rr=w56, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #398: @49 = (@42*@49) */
  w49  = (w42*w49);
  /* #399: @67 = dense(@49) */
  casadi_densify((&w49), casadi_s3, w67, 0);
  /* #400: @56 = (@56+@67) */
  for (i=0, rr=w56, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #401: @45 = @19; (@45[3:7] += @56) */
  casadi_copy(w19, 11, w45);
  for (rr=w45+3, cs=w56; rr!=w45+7; rr+=1) *rr += *cs++;
  /* #402: @50 = sparsity_cast(@50) */
  /* #403: @50 = (-@50) */
  w50 = (- w50 );
  /* #404: @50 = @50' */
  /* #405: @20 = mac(@50,@21,@1) */
  casadi_copy(w01, 3, w20);
  casadi_mtimes((&w50), casadi_s6, w21, casadi_s5, w20, casadi_s4, w, 0);
  /* #406: @20 = @20' */
  /* #407: @22 = mac(@50,@36,@1) */
  casadi_copy(w01, 3, w22);
  casadi_mtimes((&w50), casadi_s6, w36, casadi_s5, w22, casadi_s4, w, 0);
  /* #408: @22 = @22' */
  /* #409: @20 = (@20+@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #410: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #411: (@45[:3] += @20) */
  for (rr=w45+0, cs=w20; rr!=w45+3; rr+=1) *rr += *cs++;
  /* #412: {@50, @49, @60, @58, @44, @43, @66, @68, @69, @70, @71} = vertsplit(@45) */
  w50 = w45[0];
  w49 = w45[1];
  w60 = w45[2];
  w58 = w45[3];
  w44 = w45[4];
  w43 = w45[5];
  w66 = w45[6];
  w68 = w45[7];
  w69 = w45[8];
  w70 = w45[9];
  w71 = w45[10];
  /* #413: @57 = (@57/@9) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w09;
  /* #414: @25 = (@25/@9) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) /= w09;
  /* #415: @56 = (@25*@16) */
  for (i=0, rr=w56, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #416: @57 = (@57-@56) */
  for (i=0, rr=w57, cs=w56; i<4; ++i) (*rr++) -= (*cs++);
  /* #417: {@16, @72, @73, @74} = vertsplit(@57) */
  w16 = w57[0];
  w72 = w57[1];
  w73 = w57[2];
  w74 = w57[3];
  /* #418: @16 = (@16+@58) */
  w16 += w58;
  /* #419: @44 = (@44-@72) */
  w44 -= w72;
  /* #420: @43 = (@43-@73) */
  w43 -= w73;
  /* #421: @66 = (@66-@74) */
  w66 -= w74;
  /* #422: @17 = vertcat(@48, @51, @47, @52, @50, @49, @60, @16, @44, @43, @66, @68, @69, @70, @71) */
  rr=w17;
  *rr++ = w48;
  *rr++ = w51;
  *rr++ = w47;
  *rr++ = w52;
  *rr++ = w50;
  *rr++ = w49;
  *rr++ = w60;
  *rr++ = w16;
  *rr++ = w44;
  *rr++ = w43;
  *rr++ = w66;
  *rr++ = w68;
  *rr++ = w69;
  *rr++ = w70;
  *rr++ = w71;
  /* #423: @45 = @17[:11] */
  for (rr=w45, cs=w17+0; cs!=w17+11; cs+=1) *rr++ = *cs;
  /* #424: (@53[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @45) */
  for (cii=casadi_s7, rr=w53, cs=w45; cii!=casadi_s7+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #425: (@53[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @45) */
  for (cii=casadi_s8, rr=w53, cs=w45; cii!=casadi_s8+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #426: @20 = ones(15x1,3nz) */
  casadi_fill(w20, 3, 1.);
  /* #427: {NULL, @48, NULL, NULL, NULL, @51, NULL, NULL, @47, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@20) */
  w48 = w20[0];
  w51 = w20[1];
  w47 = w20[2];
  /* #428: @52 = vertcat(@55, @48, @55, @55) */
  rr=(&w52);
  *rr++ = w48;
  /* #429: @52 = @52' */
  /* #430: @57 = mac(@52,@26,@23) */
  casadi_copy(w23, 4, w57);
  casadi_mtimes((&w52), casadi_s9, w26, casadi_s1, w57, casadi_s0, w, 0);
  /* #431: @57 = @57' */
  /* #432: @56 = mac(@52,@35,@23) */
  casadi_copy(w23, 4, w56);
  casadi_mtimes((&w52), casadi_s9, w35, casadi_s1, w56, casadi_s0, w, 0);
  /* #433: @56 = @56' */
  /* #434: @57 = (@57+@56) */
  for (i=0, rr=w57, cs=w56; i<4; ++i) (*rr++) += (*cs++);
  /* #435: {@52, @48, @50, @49} = vertsplit(@57) */
  w52 = w57[0];
  w48 = w57[1];
  w50 = w57[2];
  w49 = w57[3];
  /* #436: @60 = (-@47) */
  w60 = (- w47 );
  /* #437: @16 = vertcat(@55, @60, @55, @55) */
  rr=(&w16);
  *rr++ = w60;
  /* #438: @16 = (@16/@9) */
  w16 /= w09;
  /* #439: @57 = dense(@16) */
  casadi_densify((&w16), casadi_s10, w57, 0);
  /* #440: @16 = project(@28) */
  casadi_sparsify(w28, (&w16), casadi_s10, 0);
  /* #441: @47 = sparsity_cast(@47) */
  /* #442: @60 = dot(@16, @47) */
  w60 = casadi_dot(1, (&w16), (&w47));
  /* #443: @60 = (@60/@9) */
  w60 /= w09;
  /* #444: @56 = (@24*@60) */
  for (i=0, rr=w56, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #445: @57 = (@57-@56) */
  for (i=0, rr=w57, cs=w56; i<4; ++i) (*rr++) -= (*cs++);
  /* #446: @16 = @57[0] */
  for (rr=(&w16), cs=w57+0; cs!=w57+1; cs+=1) *rr++ = *cs;
  /* #447: @44 = (@5*@16) */
  w44  = (w05*w16);
  /* #448: @43 = @57[1] */
  for (rr=(&w43), cs=w57+1; cs!=w57+2; cs+=1) *rr++ = *cs;
  /* #449: @66 = (@6*@43) */
  w66  = (w06*w43);
  /* #450: @44 = (@44-@66) */
  w44 -= w66;
  /* #451: @66 = @57[2] */
  for (rr=(&w66), cs=w57+2; cs!=w57+3; cs+=1) *rr++ = *cs;
  /* #452: @68 = (@7*@66) */
  w68  = (w07*w66);
  /* #453: @44 = (@44-@68) */
  w44 -= w68;
  /* #454: @68 = @57[3] */
  for (rr=(&w68), cs=w57+3; cs!=w57+4; cs+=1) *rr++ = *cs;
  /* #455: @69 = (@8*@68) */
  w69  = (w08*w68);
  /* #456: @44 = (@44-@69) */
  w44 -= w69;
  /* #457: @69 = (@6*@16) */
  w69  = (w06*w16);
  /* #458: @70 = (@5*@43) */
  w70  = (w05*w43);
  /* #459: @69 = (@69+@70) */
  w69 += w70;
  /* #460: @70 = (@8*@66) */
  w70  = (w08*w66);
  /* #461: @69 = (@69+@70) */
  w69 += w70;
  /* #462: @70 = (@7*@68) */
  w70  = (w07*w68);
  /* #463: @69 = (@69-@70) */
  w69 -= w70;
  /* #464: @70 = (@7*@16) */
  w70  = (w07*w16);
  /* #465: @71 = (@8*@43) */
  w71  = (w08*w43);
  /* #466: @70 = (@70-@71) */
  w70 -= w71;
  /* #467: @71 = (@5*@66) */
  w71  = (w05*w66);
  /* #468: @70 = (@70+@71) */
  w70 += w71;
  /* #469: @71 = (@6*@68) */
  w71  = (w06*w68);
  /* #470: @70 = (@70+@71) */
  w70 += w71;
  /* #471: @16 = (@8*@16) */
  w16  = (w08*w16);
  /* #472: @43 = (@7*@43) */
  w43  = (w07*w43);
  /* #473: @16 = (@16+@43) */
  w16 += w43;
  /* #474: @66 = (@6*@66) */
  w66  = (w06*w66);
  /* #475: @16 = (@16-@66) */
  w16 -= w66;
  /* #476: @68 = (@5*@68) */
  w68  = (w05*w68);
  /* #477: @16 = (@16+@68) */
  w16 += w68;
  /* #478: @56 = vertcat(@44, @69, @70, @16) */
  rr=w56;
  *rr++ = w44;
  *rr++ = w69;
  *rr++ = w70;
  *rr++ = w16;
  /* #479: @67 = (-@56) */
  for (i=0, rr=w67, cs=w56; i<4; ++i) *rr++ = (- *cs++ );
  /* #480: @67 = (@13?@67:0) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #481: @56 = (@11?@56:0) */
  for (i=0, rr=w56, cs=w56; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #482: @67 = (@67+@56) */
  for (i=0, rr=w67, cs=w56; i<4; ++i) (*rr++) += (*cs++);
  /* #483: @20 = @67[1:4] */
  for (rr=w20, cs=w67+1; cs!=w67+4; cs+=1) *rr++ = *cs;
  /* #484: @44 = dot(@18, @20) */
  w44 = casadi_dot(3, w18, w20);
  /* #485: @44 = (@44/@14) */
  w44 /= w14;
  /* #486: @69 = (@44/@3) */
  w69  = (w44/w03);
  /* #487: @70 = (@46*@44) */
  w70  = (w46*w44);
  /* #488: @16 = @67[0] */
  for (rr=(&w16), cs=w67+0; cs!=w67+1; cs+=1) *rr++ = *cs;
  /* #489: @68 = (@15*@16) */
  w68  = (w15*w16);
  /* #490: @70 = (@70+@68) */
  w70 += w68;
  /* #491: @68 = (@59*@70) */
  w68  = (w59*w70);
  /* #492: @69 = (@69-@68) */
  w69 -= w68;
  /* #493: @69 = (@0*@69) */
  w69  = (w00*w69);
  /* #494: @22 = (2.*@20) */
  for (i=0, rr=w22, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #495: @63 = (@10*@22) */
  for (i=0, rr=w63, cs=w22; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #496: @68 = (@12*@44) */
  w68  = (w12*w44);
  /* #497: @66 = (@4*@16) */
  w66  = (w04*w16);
  /* #498: @68 = (@68-@66) */
  w68 -= w66;
  /* #499: @38 = (@31*@68) */
  for (i=0, rr=w38, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #500: @63 = (@63+@38) */
  for (i=0, rr=w63, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #501: @63 = (@63/@14) */
  for (i=0, rr=w63; i<3; ++i) (*rr++) /= w14;
  /* #502: @38 = (@32*@44) */
  for (i=0, rr=w38, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #503: @63 = (@63-@38) */
  for (i=0, rr=w63, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #504: @38 = @63' */
  casadi_copy(w63, 3, w38);
  /* #505: @64 = mac(@38,@21,@1) */
  casadi_copy(w01, 3, w64);
  for (i=0, rr=w64; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #506: @64 = @64' */
  /* #507: @75 = mac(@38,@36,@1) */
  casadi_copy(w01, 3, w75);
  for (i=0, rr=w75; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #508: @75 = @75' */
  /* #509: @64 = (@64+@75) */
  for (i=0, rr=w64, cs=w75; i<3; ++i) (*rr++) += (*cs++);
  /* #510: @75 = (@64/@14) */
  for (i=0, rr=w75, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #511: @38 = (@39*@44) */
  for (i=0, rr=w38, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #512: @75 = (@75-@38) */
  for (i=0, rr=w75, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #513: @66 = dot(@31, @75) */
  w66 = casadi_dot(3, w31, w75);
  /* #514: @43 = dot(@22, @37) */
  w43 = casadi_dot(3, w22, w37);
  /* #515: @66 = (@66+@43) */
  w66 += w43;
  /* #516: @43 = (@4*@66) */
  w43  = (w04*w66);
  /* #517: @69 = (@69+@43) */
  w69 += w43;
  /* #518: @69 = (-@69) */
  w69 = (- w69 );
  /* #519: @67 = @30; (@67[0] += @69) */
  casadi_copy(w30, 4, w67);
  for (rr=w67+0, cs=(&w69); rr!=w67+1; rr+=1) *rr += *cs++;
  /* #520: @69 = dot(@33, @64) */
  w69 = casadi_dot(3, w33, w64);
  /* #521: @63 = (@63/@14) */
  for (i=0, rr=w63; i<3; ++i) (*rr++) /= w14;
  /* #522: @64 = (@62*@44) */
  for (i=0, rr=w64, cr=w62; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #523: @63 = (@63-@64) */
  for (i=0, rr=w63, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #524: @63 = (-@63) */
  for (i=0, rr=w63, cs=w63; i<3; ++i) *rr++ = (- *cs++ );
  /* #525: @43 = dot(@63, @34) */
  w43 = casadi_dot(3, w63, w34);
  /* #526: @69 = (@69+@43) */
  w69 += w43;
  /* #527: @16 = (@16/@3) */
  w16 /= w03;
  /* #528: @70 = (@65*@70) */
  w70  = (w65*w70);
  /* #529: @16 = (@16-@70) */
  w16 -= w70;
  /* #530: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #531: @66 = (@12*@66) */
  w66  = (w12*w66);
  /* #532: @16 = (@16+@66) */
  w16 += w66;
  /* #533: @69 = (@69+@16) */
  w69 += w16;
  /* #534: @69 = (@69/@14) */
  w69 /= w14;
  /* #535: @44 = (@41*@44) */
  w44  = (w41*w44);
  /* #536: @69 = (@69-@44) */
  w69 -= w44;
  /* #537: @63 = (@18*@69) */
  for (i=0, rr=w63, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #538: @20 = (@2*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #539: @63 = (@63+@20) */
  for (i=0, rr=w63, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #540: @20 = (@37*@68) */
  for (i=0, rr=w20, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w68);
  /* #541: @75 = (@10*@75) */
  for (i=0, rr=w75, cs=w75; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #542: @20 = (@20+@75) */
  for (i=0, rr=w20, cs=w75; i<3; ++i) (*rr++) += (*cs++);
  /* #543: @20 = (2.*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #544: @63 = (@63+@20) */
  for (i=0, rr=w63, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #545: (@67[1:4] += @63) */
  for (rr=w67+1, cs=w63; rr!=w67+4; rr+=1) *rr += *cs++;
  /* #546: @56 = (@11?@67:0) */
  for (i=0, rr=w56, cs=w67; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #547: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #548: @67 = (@13?@67:0) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #549: @56 = (@56+@67) */
  for (i=0, rr=w56, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #550: {@68, @69, @44, @16} = vertsplit(@56) */
  w68 = w56[0];
  w69 = w56[1];
  w44 = w56[2];
  w16 = w56[3];
  /* #551: @66 = (@5*@16) */
  w66  = (w05*w16);
  /* #552: @70 = (@6*@44) */
  w70  = (w06*w44);
  /* #553: @66 = (@66+@70) */
  w66 += w70;
  /* #554: @70 = (@7*@69) */
  w70  = (w07*w69);
  /* #555: @66 = (@66-@70) */
  w66 -= w70;
  /* #556: @70 = (@8*@68) */
  w70  = (w08*w68);
  /* #557: @66 = (@66-@70) */
  w66 -= w70;
  /* #558: @56 = @30; (@56[3] += @66) */
  casadi_copy(w30, 4, w56);
  for (rr=w56+3, cs=(&w66); rr!=w56+4; rr+=1) *rr += *cs++;
  /* #559: @66 = (@5*@44) */
  w66  = (w05*w44);
  /* #560: @70 = (@6*@16) */
  w70  = (w06*w16);
  /* #561: @66 = (@66-@70) */
  w66 -= w70;
  /* #562: @70 = (@8*@69) */
  w70  = (w08*w69);
  /* #563: @66 = (@66+@70) */
  w66 += w70;
  /* #564: @70 = (@7*@68) */
  w70  = (w07*w68);
  /* #565: @66 = (@66-@70) */
  w66 -= w70;
  /* #566: (@56[2] += @66) */
  for (rr=w56+2, cs=(&w66); rr!=w56+3; rr+=1) *rr += *cs++;
  /* #567: @66 = (@7*@16) */
  w66  = (w07*w16);
  /* #568: @70 = (@8*@44) */
  w70  = (w08*w44);
  /* #569: @66 = (@66-@70) */
  w66 -= w70;
  /* #570: @70 = (@5*@69) */
  w70  = (w05*w69);
  /* #571: @66 = (@66+@70) */
  w66 += w70;
  /* #572: @70 = (@6*@68) */
  w70  = (w06*w68);
  /* #573: @66 = (@66-@70) */
  w66 -= w70;
  /* #574: (@56[1] += @66) */
  for (rr=w56+1, cs=(&w66); rr!=w56+2; rr+=1) *rr += *cs++;
  /* #575: @16 = (@8*@16) */
  w16  = (w08*w16);
  /* #576: @44 = (@7*@44) */
  w44  = (w07*w44);
  /* #577: @16 = (@16+@44) */
  w16 += w44;
  /* #578: @69 = (@6*@69) */
  w69  = (w06*w69);
  /* #579: @16 = (@16+@69) */
  w16 += w69;
  /* #580: @68 = (@5*@68) */
  w68  = (w05*w68);
  /* #581: @16 = (@16+@68) */
  w16 += w68;
  /* #582: (@56[0] += @16) */
  for (rr=w56+0, cs=(&w16); rr!=w56+1; rr+=1) *rr += *cs++;
  /* #583: @16 = dot(@27, @56) */
  w16 = casadi_dot(4, w27, w56);
  /* #584: @57 = (@57/@9) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w09;
  /* #585: @67 = (@61*@60) */
  for (i=0, rr=w67, cr=w61; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #586: @57 = (@57-@67) */
  for (i=0, rr=w57, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #587: @57 = (-@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #588: @68 = dot(@57, @29) */
  w68 = casadi_dot(4, w57, w29);
  /* #589: @16 = (@16+@68) */
  w16 += w68;
  /* #590: @16 = (@16/@9) */
  w16 /= w09;
  /* #591: @68 = (@40*@60) */
  w68  = (w40*w60);
  /* #592: @16 = (@16-@68) */
  w16 -= w68;
  /* #593: @57 = (@28*@16) */
  for (i=0, rr=w57, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #594: @47 = (@42*@47) */
  w47  = (w42*w47);
  /* #595: @67 = dense(@47) */
  casadi_densify((&w47), casadi_s10, w67, 0);
  /* #596: @57 = (@57+@67) */
  for (i=0, rr=w57, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #597: @45 = @19; (@45[3:7] += @57) */
  casadi_copy(w19, 11, w45);
  for (rr=w45+3, cs=w57; rr!=w45+7; rr+=1) *rr += *cs++;
  /* #598: @51 = sparsity_cast(@51) */
  /* #599: @51 = (-@51) */
  w51 = (- w51 );
  /* #600: @51 = @51' */
  /* #601: @63 = mac(@51,@21,@1) */
  casadi_copy(w01, 3, w63);
  casadi_mtimes((&w51), casadi_s11, w21, casadi_s5, w63, casadi_s4, w, 0);
  /* #602: @63 = @63' */
  /* #603: @20 = mac(@51,@36,@1) */
  casadi_copy(w01, 3, w20);
  casadi_mtimes((&w51), casadi_s11, w36, casadi_s5, w20, casadi_s4, w, 0);
  /* #604: @20 = @20' */
  /* #605: @63 = (@63+@20) */
  for (i=0, rr=w63, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #606: @63 = (-@63) */
  for (i=0, rr=w63, cs=w63; i<3; ++i) *rr++ = (- *cs++ );
  /* #607: (@45[:3] += @63) */
  for (rr=w45+0, cs=w63; rr!=w45+3; rr+=1) *rr += *cs++;
  /* #608: {@51, @47, @16, @68, @69, @44, @66, @70, @43, @71, @74} = vertsplit(@45) */
  w51 = w45[0];
  w47 = w45[1];
  w16 = w45[2];
  w68 = w45[3];
  w69 = w45[4];
  w44 = w45[5];
  w66 = w45[6];
  w70 = w45[7];
  w43 = w45[8];
  w71 = w45[9];
  w74 = w45[10];
  /* #609: @56 = (@56/@9) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) /= w09;
  /* #610: @57 = (@25*@60) */
  for (i=0, rr=w57, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #611: @56 = (@56-@57) */
  for (i=0, rr=w56, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #612: {@60, @73, @72, @58} = vertsplit(@56) */
  w60 = w56[0];
  w73 = w56[1];
  w72 = w56[2];
  w58 = w56[3];
  /* #613: @60 = (@60+@68) */
  w60 += w68;
  /* #614: @69 = (@69-@73) */
  w69 -= w73;
  /* #615: @44 = (@44-@72) */
  w44 -= w72;
  /* #616: @66 = (@66-@58) */
  w66 -= w58;
  /* #617: @17 = vertcat(@52, @48, @50, @49, @51, @47, @16, @60, @69, @44, @66, @70, @43, @71, @74) */
  rr=w17;
  *rr++ = w52;
  *rr++ = w48;
  *rr++ = w50;
  *rr++ = w49;
  *rr++ = w51;
  *rr++ = w47;
  *rr++ = w16;
  *rr++ = w60;
  *rr++ = w69;
  *rr++ = w44;
  *rr++ = w66;
  *rr++ = w70;
  *rr++ = w43;
  *rr++ = w71;
  *rr++ = w74;
  /* #618: @45 = @17[:11] */
  for (rr=w45, cs=w17+0; cs!=w17+11; cs+=1) *rr++ = *cs;
  /* #619: (@53[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @45) */
  for (cii=casadi_s12, rr=w53, cs=w45; cii!=casadi_s12+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #620: (@53[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @45) */
  for (cii=casadi_s13, rr=w53, cs=w45; cii!=casadi_s13+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #621: @63 = ones(15x1,3nz) */
  casadi_fill(w63, 3, 1.);
  /* #622: {NULL, NULL, @52, NULL, NULL, NULL, @48, NULL, NULL, @50, NULL, NULL, NULL, NULL, NULL} = vertsplit(@63) */
  w52 = w63[0];
  w48 = w63[1];
  w50 = w63[2];
  /* #623: @49 = vertcat(@55, @55, @52, @55) */
  rr=(&w49);
  *rr++ = w52;
  /* #624: @49 = @49' */
  /* #625: @56 = mac(@49,@26,@23) */
  casadi_copy(w23, 4, w56);
  casadi_mtimes((&w49), casadi_s14, w26, casadi_s1, w56, casadi_s0, w, 0);
  /* #626: @56 = @56' */
  /* #627: @57 = mac(@49,@35,@23) */
  casadi_copy(w23, 4, w57);
  casadi_mtimes((&w49), casadi_s14, w35, casadi_s1, w57, casadi_s0, w, 0);
  /* #628: @57 = @57' */
  /* #629: @56 = (@56+@57) */
  for (i=0, rr=w56, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #630: {@49, @52, @51, @47} = vertsplit(@56) */
  w49 = w56[0];
  w52 = w56[1];
  w51 = w56[2];
  w47 = w56[3];
  /* #631: @16 = (-@50) */
  w16 = (- w50 );
  /* #632: @60 = vertcat(@55, @55, @16, @55) */
  rr=(&w60);
  *rr++ = w16;
  /* #633: @60 = (@60/@9) */
  w60 /= w09;
  /* #634: @56 = dense(@60) */
  casadi_densify((&w60), casadi_s15, w56, 0);
  /* #635: @60 = project(@28) */
  casadi_sparsify(w28, (&w60), casadi_s15, 0);
  /* #636: @50 = sparsity_cast(@50) */
  /* #637: @16 = dot(@60, @50) */
  w16 = casadi_dot(1, (&w60), (&w50));
  /* #638: @16 = (@16/@9) */
  w16 /= w09;
  /* #639: @57 = (@24*@16) */
  for (i=0, rr=w57, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #640: @56 = (@56-@57) */
  for (i=0, rr=w56, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #641: @60 = @56[0] */
  for (rr=(&w60), cs=w56+0; cs!=w56+1; cs+=1) *rr++ = *cs;
  /* #642: @69 = (@5*@60) */
  w69  = (w05*w60);
  /* #643: @44 = @56[1] */
  for (rr=(&w44), cs=w56+1; cs!=w56+2; cs+=1) *rr++ = *cs;
  /* #644: @66 = (@6*@44) */
  w66  = (w06*w44);
  /* #645: @69 = (@69-@66) */
  w69 -= w66;
  /* #646: @66 = @56[2] */
  for (rr=(&w66), cs=w56+2; cs!=w56+3; cs+=1) *rr++ = *cs;
  /* #647: @70 = (@7*@66) */
  w70  = (w07*w66);
  /* #648: @69 = (@69-@70) */
  w69 -= w70;
  /* #649: @70 = @56[3] */
  for (rr=(&w70), cs=w56+3; cs!=w56+4; cs+=1) *rr++ = *cs;
  /* #650: @43 = (@8*@70) */
  w43  = (w08*w70);
  /* #651: @69 = (@69-@43) */
  w69 -= w43;
  /* #652: @43 = (@6*@60) */
  w43  = (w06*w60);
  /* #653: @71 = (@5*@44) */
  w71  = (w05*w44);
  /* #654: @43 = (@43+@71) */
  w43 += w71;
  /* #655: @71 = (@8*@66) */
  w71  = (w08*w66);
  /* #656: @43 = (@43+@71) */
  w43 += w71;
  /* #657: @71 = (@7*@70) */
  w71  = (w07*w70);
  /* #658: @43 = (@43-@71) */
  w43 -= w71;
  /* #659: @71 = (@7*@60) */
  w71  = (w07*w60);
  /* #660: @74 = (@8*@44) */
  w74  = (w08*w44);
  /* #661: @71 = (@71-@74) */
  w71 -= w74;
  /* #662: @74 = (@5*@66) */
  w74  = (w05*w66);
  /* #663: @71 = (@71+@74) */
  w71 += w74;
  /* #664: @74 = (@6*@70) */
  w74  = (w06*w70);
  /* #665: @71 = (@71+@74) */
  w71 += w74;
  /* #666: @60 = (@8*@60) */
  w60  = (w08*w60);
  /* #667: @44 = (@7*@44) */
  w44  = (w07*w44);
  /* #668: @60 = (@60+@44) */
  w60 += w44;
  /* #669: @66 = (@6*@66) */
  w66  = (w06*w66);
  /* #670: @60 = (@60-@66) */
  w60 -= w66;
  /* #671: @70 = (@5*@70) */
  w70  = (w05*w70);
  /* #672: @60 = (@60+@70) */
  w60 += w70;
  /* #673: @57 = vertcat(@69, @43, @71, @60) */
  rr=w57;
  *rr++ = w69;
  *rr++ = w43;
  *rr++ = w71;
  *rr++ = w60;
  /* #674: @67 = (-@57) */
  for (i=0, rr=w67, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #675: @67 = (@13?@67:0) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #676: @57 = (@11?@57:0) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #677: @67 = (@67+@57) */
  for (i=0, rr=w67, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #678: @63 = @67[1:4] */
  for (rr=w63, cs=w67+1; cs!=w67+4; cs+=1) *rr++ = *cs;
  /* #679: @69 = dot(@18, @63) */
  w69 = casadi_dot(3, w18, w63);
  /* #680: @69 = (@69/@14) */
  w69 /= w14;
  /* #681: @43 = (@69/@3) */
  w43  = (w69/w03);
  /* #682: @71 = (@46*@69) */
  w71  = (w46*w69);
  /* #683: @60 = @67[0] */
  for (rr=(&w60), cs=w67+0; cs!=w67+1; cs+=1) *rr++ = *cs;
  /* #684: @70 = (@15*@60) */
  w70  = (w15*w60);
  /* #685: @71 = (@71+@70) */
  w71 += w70;
  /* #686: @70 = (@59*@71) */
  w70  = (w59*w71);
  /* #687: @43 = (@43-@70) */
  w43 -= w70;
  /* #688: @43 = (@0*@43) */
  w43  = (w00*w43);
  /* #689: @20 = (2.*@63) */
  for (i=0, rr=w20, cs=w63; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #690: @75 = (@10*@20) */
  for (i=0, rr=w75, cs=w20; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #691: @70 = (@12*@69) */
  w70  = (w12*w69);
  /* #692: @66 = (@4*@60) */
  w66  = (w04*w60);
  /* #693: @70 = (@70-@66) */
  w70 -= w66;
  /* #694: @64 = (@31*@70) */
  for (i=0, rr=w64, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w70);
  /* #695: @75 = (@75+@64) */
  for (i=0, rr=w75, cs=w64; i<3; ++i) (*rr++) += (*cs++);
  /* #696: @75 = (@75/@14) */
  for (i=0, rr=w75; i<3; ++i) (*rr++) /= w14;
  /* #697: @64 = (@32*@69) */
  for (i=0, rr=w64, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #698: @75 = (@75-@64) */
  for (i=0, rr=w75, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #699: @64 = @75' */
  casadi_copy(w75, 3, w64);
  /* #700: @22 = mac(@64,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w64+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #701: @22 = @22' */
  /* #702: @38 = mac(@64,@36,@1) */
  casadi_copy(w01, 3, w38);
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w64+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #703: @38 = @38' */
  /* #704: @22 = (@22+@38) */
  for (i=0, rr=w22, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #705: @38 = (@22/@14) */
  for (i=0, rr=w38, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #706: @64 = (@39*@69) */
  for (i=0, rr=w64, cr=w39; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #707: @38 = (@38-@64) */
  for (i=0, rr=w38, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #708: @66 = dot(@31, @38) */
  w66 = casadi_dot(3, w31, w38);
  /* #709: @44 = dot(@20, @37) */
  w44 = casadi_dot(3, w20, w37);
  /* #710: @66 = (@66+@44) */
  w66 += w44;
  /* #711: @44 = (@4*@66) */
  w44  = (w04*w66);
  /* #712: @43 = (@43+@44) */
  w43 += w44;
  /* #713: @43 = (-@43) */
  w43 = (- w43 );
  /* #714: @67 = @30; (@67[0] += @43) */
  casadi_copy(w30, 4, w67);
  for (rr=w67+0, cs=(&w43); rr!=w67+1; rr+=1) *rr += *cs++;
  /* #715: @43 = dot(@33, @22) */
  w43 = casadi_dot(3, w33, w22);
  /* #716: @75 = (@75/@14) */
  for (i=0, rr=w75; i<3; ++i) (*rr++) /= w14;
  /* #717: @22 = (@62*@69) */
  for (i=0, rr=w22, cr=w62; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #718: @75 = (@75-@22) */
  for (i=0, rr=w75, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #719: @75 = (-@75) */
  for (i=0, rr=w75, cs=w75; i<3; ++i) *rr++ = (- *cs++ );
  /* #720: @44 = dot(@75, @34) */
  w44 = casadi_dot(3, w75, w34);
  /* #721: @43 = (@43+@44) */
  w43 += w44;
  /* #722: @60 = (@60/@3) */
  w60 /= w03;
  /* #723: @71 = (@65*@71) */
  w71  = (w65*w71);
  /* #724: @60 = (@60-@71) */
  w60 -= w71;
  /* #725: @60 = (@0*@60) */
  w60  = (w00*w60);
  /* #726: @66 = (@12*@66) */
  w66  = (w12*w66);
  /* #727: @60 = (@60+@66) */
  w60 += w66;
  /* #728: @43 = (@43+@60) */
  w43 += w60;
  /* #729: @43 = (@43/@14) */
  w43 /= w14;
  /* #730: @69 = (@41*@69) */
  w69  = (w41*w69);
  /* #731: @43 = (@43-@69) */
  w43 -= w69;
  /* #732: @75 = (@18*@43) */
  for (i=0, rr=w75, cr=w18; i<3; ++i) (*rr++)  = ((*cr++)*w43);
  /* #733: @63 = (@2*@63) */
  for (i=0, rr=w63, cs=w63; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #734: @75 = (@75+@63) */
  for (i=0, rr=w75, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #735: @63 = (@37*@70) */
  for (i=0, rr=w63, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w70);
  /* #736: @38 = (@10*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #737: @63 = (@63+@38) */
  for (i=0, rr=w63, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #738: @63 = (2.*@63) */
  for (i=0, rr=w63, cs=w63; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #739: @75 = (@75+@63) */
  for (i=0, rr=w75, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #740: (@67[1:4] += @75) */
  for (rr=w67+1, cs=w75; rr!=w67+4; rr+=1) *rr += *cs++;
  /* #741: @57 = (@11?@67:0) */
  for (i=0, rr=w57, cs=w67; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #742: @67 = (-@67) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) *rr++ = (- *cs++ );
  /* #743: @67 = (@13?@67:0) */
  for (i=0, rr=w67, cs=w67; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #744: @57 = (@57+@67) */
  for (i=0, rr=w57, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #745: {@70, @43, @69, @60} = vertsplit(@57) */
  w70 = w57[0];
  w43 = w57[1];
  w69 = w57[2];
  w60 = w57[3];
  /* #746: @66 = (@5*@60) */
  w66  = (w05*w60);
  /* #747: @71 = (@6*@69) */
  w71  = (w06*w69);
  /* #748: @66 = (@66+@71) */
  w66 += w71;
  /* #749: @71 = (@7*@43) */
  w71  = (w07*w43);
  /* #750: @66 = (@66-@71) */
  w66 -= w71;
  /* #751: @71 = (@8*@70) */
  w71  = (w08*w70);
  /* #752: @66 = (@66-@71) */
  w66 -= w71;
  /* #753: @57 = @30; (@57[3] += @66) */
  casadi_copy(w30, 4, w57);
  for (rr=w57+3, cs=(&w66); rr!=w57+4; rr+=1) *rr += *cs++;
  /* #754: @66 = (@5*@69) */
  w66  = (w05*w69);
  /* #755: @71 = (@6*@60) */
  w71  = (w06*w60);
  /* #756: @66 = (@66-@71) */
  w66 -= w71;
  /* #757: @71 = (@8*@43) */
  w71  = (w08*w43);
  /* #758: @66 = (@66+@71) */
  w66 += w71;
  /* #759: @71 = (@7*@70) */
  w71  = (w07*w70);
  /* #760: @66 = (@66-@71) */
  w66 -= w71;
  /* #761: (@57[2] += @66) */
  for (rr=w57+2, cs=(&w66); rr!=w57+3; rr+=1) *rr += *cs++;
  /* #762: @66 = (@7*@60) */
  w66  = (w07*w60);
  /* #763: @71 = (@8*@69) */
  w71  = (w08*w69);
  /* #764: @66 = (@66-@71) */
  w66 -= w71;
  /* #765: @71 = (@5*@43) */
  w71  = (w05*w43);
  /* #766: @66 = (@66+@71) */
  w66 += w71;
  /* #767: @71 = (@6*@70) */
  w71  = (w06*w70);
  /* #768: @66 = (@66-@71) */
  w66 -= w71;
  /* #769: (@57[1] += @66) */
  for (rr=w57+1, cs=(&w66); rr!=w57+2; rr+=1) *rr += *cs++;
  /* #770: @60 = (@8*@60) */
  w60  = (w08*w60);
  /* #771: @69 = (@7*@69) */
  w69  = (w07*w69);
  /* #772: @60 = (@60+@69) */
  w60 += w69;
  /* #773: @43 = (@6*@43) */
  w43  = (w06*w43);
  /* #774: @60 = (@60+@43) */
  w60 += w43;
  /* #775: @70 = (@5*@70) */
  w70  = (w05*w70);
  /* #776: @60 = (@60+@70) */
  w60 += w70;
  /* #777: (@57[0] += @60) */
  for (rr=w57+0, cs=(&w60); rr!=w57+1; rr+=1) *rr += *cs++;
  /* #778: @60 = dot(@27, @57) */
  w60 = casadi_dot(4, w27, w57);
  /* #779: @56 = (@56/@9) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) /= w09;
  /* #780: @67 = (@61*@16) */
  for (i=0, rr=w67, cr=w61; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #781: @56 = (@56-@67) */
  for (i=0, rr=w56, cs=w67; i<4; ++i) (*rr++) -= (*cs++);
  /* #782: @56 = (-@56) */
  for (i=0, rr=w56, cs=w56; i<4; ++i) *rr++ = (- *cs++ );
  /* #783: @70 = dot(@56, @29) */
  w70 = casadi_dot(4, w56, w29);
  /* #784: @60 = (@60+@70) */
  w60 += w70;
  /* #785: @60 = (@60/@9) */
  w60 /= w09;
  /* #786: @70 = (@40*@16) */
  w70  = (w40*w16);
  /* #787: @60 = (@60-@70) */
  w60 -= w70;
  /* #788: @56 = (@28*@60) */
  for (i=0, rr=w56, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w60);
  /* #789: @50 = (@42*@50) */
  w50  = (w42*w50);
  /* #790: @67 = dense(@50) */
  casadi_densify((&w50), casadi_s15, w67, 0);
  /* #791: @56 = (@56+@67) */
  for (i=0, rr=w56, cs=w67; i<4; ++i) (*rr++) += (*cs++);
  /* #792: @45 = @19; (@45[3:7] += @56) */
  casadi_copy(w19, 11, w45);
  for (rr=w45+3, cs=w56; rr!=w45+7; rr+=1) *rr += *cs++;
  /* #793: @48 = sparsity_cast(@48) */
  /* #794: @48 = (-@48) */
  w48 = (- w48 );
  /* #795: @48 = @48' */
  /* #796: @75 = mac(@48,@21,@1) */
  casadi_copy(w01, 3, w75);
  casadi_mtimes((&w48), casadi_s16, w21, casadi_s5, w75, casadi_s4, w, 0);
  /* #797: @75 = @75' */
  /* #798: @63 = mac(@48,@36,@1) */
  casadi_copy(w01, 3, w63);
  casadi_mtimes((&w48), casadi_s16, w36, casadi_s5, w63, casadi_s4, w, 0);
  /* #799: @63 = @63' */
  /* #800: @75 = (@75+@63) */
  for (i=0, rr=w75, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #801: @75 = (-@75) */
  for (i=0, rr=w75, cs=w75; i<3; ++i) *rr++ = (- *cs++ );
  /* #802: (@45[:3] += @75) */
  for (rr=w45+0, cs=w75; rr!=w45+3; rr+=1) *rr += *cs++;
  /* #803: {@48, @50, @60, @70, @43, @69, @66, @71, @44, @74, @58} = vertsplit(@45) */
  w48 = w45[0];
  w50 = w45[1];
  w60 = w45[2];
  w70 = w45[3];
  w43 = w45[4];
  w69 = w45[5];
  w66 = w45[6];
  w71 = w45[7];
  w44 = w45[8];
  w74 = w45[9];
  w58 = w45[10];
  /* #804: @57 = (@57/@9) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w09;
  /* #805: @56 = (@25*@16) */
  for (i=0, rr=w56, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w16);
  /* #806: @57 = (@57-@56) */
  for (i=0, rr=w57, cs=w56; i<4; ++i) (*rr++) -= (*cs++);
  /* #807: {@16, @72, @73, @68} = vertsplit(@57) */
  w16 = w57[0];
  w72 = w57[1];
  w73 = w57[2];
  w68 = w57[3];
  /* #808: @16 = (@16+@70) */
  w16 += w70;
  /* #809: @43 = (@43-@72) */
  w43 -= w72;
  /* #810: @69 = (@69-@73) */
  w69 -= w73;
  /* #811: @66 = (@66-@68) */
  w66 -= w68;
  /* #812: @17 = vertcat(@49, @52, @51, @47, @48, @50, @60, @16, @43, @69, @66, @71, @44, @74, @58) */
  rr=w17;
  *rr++ = w49;
  *rr++ = w52;
  *rr++ = w51;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w50;
  *rr++ = w60;
  *rr++ = w16;
  *rr++ = w43;
  *rr++ = w69;
  *rr++ = w66;
  *rr++ = w71;
  *rr++ = w44;
  *rr++ = w74;
  *rr++ = w58;
  /* #813: @45 = @17[:11] */
  for (rr=w45, cs=w17+0; cs!=w17+11; cs+=1) *rr++ = *cs;
  /* #814: (@53[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @45) */
  for (cii=casadi_s17, rr=w53, cs=w45; cii!=casadi_s17+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #815: (@53[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @45) */
  for (cii=casadi_s18, rr=w53, cs=w45; cii!=casadi_s18+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #816: @76 = ones(15x1,2nz) */
  casadi_fill(w76, 2, 1.);
  /* #817: {NULL, NULL, NULL, @49, NULL, NULL, NULL, NULL, NULL, NULL, @52, NULL, NULL, NULL, NULL} = vertsplit(@76) */
  w49 = w76[0];
  w52 = w76[1];
  /* #818: @51 = vertcat(@55, @55, @55, @49) */
  rr=(&w51);
  *rr++ = w49;
  /* #819: @51 = @51' */
  /* #820: @57 = mac(@51,@26,@23) */
  casadi_copy(w23, 4, w57);
  casadi_mtimes((&w51), casadi_s19, w26, casadi_s1, w57, casadi_s0, w, 0);
  /* #821: @57 = @57' */
  /* #822: @23 = mac(@51,@35,@23) */
  casadi_mtimes((&w51), casadi_s19, w35, casadi_s1, w23, casadi_s0, w, 0);
  /* #823: @23 = @23' */
  /* #824: @57 = (@57+@23) */
  for (i=0, rr=w57, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #825: {@51, @49, @47, @48} = vertsplit(@57) */
  w51 = w57[0];
  w49 = w57[1];
  w47 = w57[2];
  w48 = w57[3];
  /* #826: @50 = (-@52) */
  w50 = (- w52 );
  /* #827: @60 = vertcat(@55, @55, @55, @50) */
  rr=(&w60);
  *rr++ = w50;
  /* #828: @60 = (@60/@9) */
  w60 /= w09;
  /* #829: @57 = dense(@60) */
  casadi_densify((&w60), casadi_s20, w57, 0);
  /* #830: @60 = project(@28) */
  casadi_sparsify(w28, (&w60), casadi_s20, 0);
  /* #831: @52 = sparsity_cast(@52) */
  /* #832: @50 = dot(@60, @52) */
  w50 = casadi_dot(1, (&w60), (&w52));
  /* #833: @50 = (@50/@9) */
  w50 /= w09;
  /* #834: @24 = (@24*@50) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) *= w50;
  /* #835: @57 = (@57-@24) */
  for (i=0, rr=w57, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #836: @60 = @57[0] */
  for (rr=(&w60), cs=w57+0; cs!=w57+1; cs+=1) *rr++ = *cs;
  /* #837: @16 = (@5*@60) */
  w16  = (w05*w60);
  /* #838: @43 = @57[1] */
  for (rr=(&w43), cs=w57+1; cs!=w57+2; cs+=1) *rr++ = *cs;
  /* #839: @69 = (@6*@43) */
  w69  = (w06*w43);
  /* #840: @16 = (@16-@69) */
  w16 -= w69;
  /* #841: @69 = @57[2] */
  for (rr=(&w69), cs=w57+2; cs!=w57+3; cs+=1) *rr++ = *cs;
  /* #842: @66 = (@7*@69) */
  w66  = (w07*w69);
  /* #843: @16 = (@16-@66) */
  w16 -= w66;
  /* #844: @66 = @57[3] */
  for (rr=(&w66), cs=w57+3; cs!=w57+4; cs+=1) *rr++ = *cs;
  /* #845: @71 = (@8*@66) */
  w71  = (w08*w66);
  /* #846: @16 = (@16-@71) */
  w16 -= w71;
  /* #847: @71 = (@6*@60) */
  w71  = (w06*w60);
  /* #848: @44 = (@5*@43) */
  w44  = (w05*w43);
  /* #849: @71 = (@71+@44) */
  w71 += w44;
  /* #850: @44 = (@8*@69) */
  w44  = (w08*w69);
  /* #851: @71 = (@71+@44) */
  w71 += w44;
  /* #852: @44 = (@7*@66) */
  w44  = (w07*w66);
  /* #853: @71 = (@71-@44) */
  w71 -= w44;
  /* #854: @44 = (@7*@60) */
  w44  = (w07*w60);
  /* #855: @74 = (@8*@43) */
  w74  = (w08*w43);
  /* #856: @44 = (@44-@74) */
  w44 -= w74;
  /* #857: @74 = (@5*@69) */
  w74  = (w05*w69);
  /* #858: @44 = (@44+@74) */
  w44 += w74;
  /* #859: @74 = (@6*@66) */
  w74  = (w06*w66);
  /* #860: @44 = (@44+@74) */
  w44 += w74;
  /* #861: @60 = (@8*@60) */
  w60  = (w08*w60);
  /* #862: @43 = (@7*@43) */
  w43  = (w07*w43);
  /* #863: @60 = (@60+@43) */
  w60 += w43;
  /* #864: @69 = (@6*@69) */
  w69  = (w06*w69);
  /* #865: @60 = (@60-@69) */
  w60 -= w69;
  /* #866: @66 = (@5*@66) */
  w66  = (w05*w66);
  /* #867: @60 = (@60+@66) */
  w60 += w66;
  /* #868: @24 = vertcat(@16, @71, @44, @60) */
  rr=w24;
  *rr++ = w16;
  *rr++ = w71;
  *rr++ = w44;
  *rr++ = w60;
  /* #869: @23 = (-@24) */
  for (i=0, rr=w23, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #870: @23 = (@13?@23:0) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #871: @24 = (@11?@24:0) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #872: @23 = (@23+@24) */
  for (i=0, rr=w23, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #873: @75 = @23[1:4] */
  for (rr=w75, cs=w23+1; cs!=w23+4; cs+=1) *rr++ = *cs;
  /* #874: @16 = dot(@18, @75) */
  w16 = casadi_dot(3, w18, w75);
  /* #875: @16 = (@16/@14) */
  w16 /= w14;
  /* #876: @71 = (@16/@3) */
  w71  = (w16/w03);
  /* #877: @46 = (@46*@16) */
  w46 *= w16;
  /* #878: @44 = @23[0] */
  for (rr=(&w44), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #879: @15 = (@15*@44) */
  w15 *= w44;
  /* #880: @46 = (@46+@15) */
  w46 += w15;
  /* #881: @59 = (@59*@46) */
  w59 *= w46;
  /* #882: @71 = (@71-@59) */
  w71 -= w59;
  /* #883: @71 = (@0*@71) */
  w71  = (w00*w71);
  /* #884: @63 = (2.*@75) */
  for (i=0, rr=w63, cs=w75; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #885: @38 = (@10*@63) */
  for (i=0, rr=w38, cs=w63; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #886: @59 = (@12*@16) */
  w59  = (w12*w16);
  /* #887: @15 = (@4*@44) */
  w15  = (w04*w44);
  /* #888: @59 = (@59-@15) */
  w59 -= w15;
  /* #889: @22 = (@31*@59) */
  for (i=0, rr=w22, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #890: @38 = (@38+@22) */
  for (i=0, rr=w38, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #891: @38 = (@38/@14) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w14;
  /* #892: @32 = (@32*@16) */
  for (i=0, rr=w32; i<3; ++i) (*rr++) *= w16;
  /* #893: @38 = (@38-@32) */
  for (i=0, rr=w38, cs=w32; i<3; ++i) (*rr++) -= (*cs++);
  /* #894: @32 = @38' */
  casadi_copy(w38, 3, w32);
  /* #895: @22 = mac(@32,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #896: @22 = @22' */
  /* #897: @1 = mac(@32,@36,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w32+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #898: @1 = @1' */
  /* #899: @22 = (@22+@1) */
  for (i=0, rr=w22, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #900: @1 = (@22/@14) */
  for (i=0, rr=w01, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #901: @39 = (@39*@16) */
  for (i=0, rr=w39; i<3; ++i) (*rr++) *= w16;
  /* #902: @1 = (@1-@39) */
  for (i=0, rr=w01, cs=w39; i<3; ++i) (*rr++) -= (*cs++);
  /* #903: @15 = dot(@31, @1) */
  w15 = casadi_dot(3, w31, w01);
  /* #904: @60 = dot(@63, @37) */
  w60 = casadi_dot(3, w63, w37);
  /* #905: @15 = (@15+@60) */
  w15 += w60;
  /* #906: @4 = (@4*@15) */
  w04 *= w15;
  /* #907: @71 = (@71+@4) */
  w71 += w04;
  /* #908: @71 = (-@71) */
  w71 = (- w71 );
  /* #909: @23 = @30; (@23[0] += @71) */
  casadi_copy(w30, 4, w23);
  for (rr=w23+0, cs=(&w71); rr!=w23+1; rr+=1) *rr += *cs++;
  /* #910: @71 = dot(@33, @22) */
  w71 = casadi_dot(3, w33, w22);
  /* #911: @38 = (@38/@14) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w14;
  /* #912: @62 = (@62*@16) */
  for (i=0, rr=w62; i<3; ++i) (*rr++) *= w16;
  /* #913: @38 = (@38-@62) */
  for (i=0, rr=w38, cs=w62; i<3; ++i) (*rr++) -= (*cs++);
  /* #914: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #915: @4 = dot(@38, @34) */
  w04 = casadi_dot(3, w38, w34);
  /* #916: @71 = (@71+@4) */
  w71 += w04;
  /* #917: @44 = (@44/@3) */
  w44 /= w03;
  /* #918: @65 = (@65*@46) */
  w65 *= w46;
  /* #919: @44 = (@44-@65) */
  w44 -= w65;
  /* #920: @0 = (@0*@44) */
  w00 *= w44;
  /* #921: @12 = (@12*@15) */
  w12 *= w15;
  /* #922: @0 = (@0+@12) */
  w00 += w12;
  /* #923: @71 = (@71+@0) */
  w71 += w00;
  /* #924: @71 = (@71/@14) */
  w71 /= w14;
  /* #925: @41 = (@41*@16) */
  w41 *= w16;
  /* #926: @71 = (@71-@41) */
  w71 -= w41;
  /* #927: @18 = (@18*@71) */
  for (i=0, rr=w18; i<3; ++i) (*rr++) *= w71;
  /* #928: @75 = (@2*@75) */
  for (i=0, rr=w75, cs=w75; i<3; ++i) (*rr++)  = (w02*(*cs++));
  /* #929: @18 = (@18+@75) */
  for (i=0, rr=w18, cs=w75; i<3; ++i) (*rr++) += (*cs++);
  /* #930: @37 = (@37*@59) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w59;
  /* #931: @1 = (@10*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #932: @37 = (@37+@1) */
  for (i=0, rr=w37, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #933: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #934: @18 = (@18+@37) */
  for (i=0, rr=w18, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #935: (@23[1:4] += @18) */
  for (rr=w23+1, cs=w18; rr!=w23+4; rr+=1) *rr += *cs++;
  /* #936: @24 = (@11?@23:0) */
  for (i=0, rr=w24, cs=w23; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #937: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #938: @23 = (@13?@23:0) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #939: @24 = (@24+@23) */
  for (i=0, rr=w24, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #940: {@13, @11, @10, @59} = vertsplit(@24) */
  w13 = w24[0];
  w11 = w24[1];
  w10 = w24[2];
  w59 = w24[3];
  /* #941: @2 = (@5*@59) */
  w02  = (w05*w59);
  /* #942: @71 = (@6*@10) */
  w71  = (w06*w10);
  /* #943: @2 = (@2+@71) */
  w02 += w71;
  /* #944: @71 = (@7*@11) */
  w71  = (w07*w11);
  /* #945: @2 = (@2-@71) */
  w02 -= w71;
  /* #946: @71 = (@8*@13) */
  w71  = (w08*w13);
  /* #947: @2 = (@2-@71) */
  w02 -= w71;
  /* #948: (@30[3] += @2) */
  for (rr=w30+3, cs=(&w02); rr!=w30+4; rr+=1) *rr += *cs++;
  /* #949: @2 = (@5*@10) */
  w02  = (w05*w10);
  /* #950: @71 = (@6*@59) */
  w71  = (w06*w59);
  /* #951: @2 = (@2-@71) */
  w02 -= w71;
  /* #952: @71 = (@8*@11) */
  w71  = (w08*w11);
  /* #953: @2 = (@2+@71) */
  w02 += w71;
  /* #954: @71 = (@7*@13) */
  w71  = (w07*w13);
  /* #955: @2 = (@2-@71) */
  w02 -= w71;
  /* #956: (@30[2] += @2) */
  for (rr=w30+2, cs=(&w02); rr!=w30+3; rr+=1) *rr += *cs++;
  /* #957: @2 = (@7*@59) */
  w02  = (w07*w59);
  /* #958: @71 = (@8*@10) */
  w71  = (w08*w10);
  /* #959: @2 = (@2-@71) */
  w02 -= w71;
  /* #960: @71 = (@5*@11) */
  w71  = (w05*w11);
  /* #961: @2 = (@2+@71) */
  w02 += w71;
  /* #962: @71 = (@6*@13) */
  w71  = (w06*w13);
  /* #963: @2 = (@2-@71) */
  w02 -= w71;
  /* #964: (@30[1] += @2) */
  for (rr=w30+1, cs=(&w02); rr!=w30+2; rr+=1) *rr += *cs++;
  /* #965: @8 = (@8*@59) */
  w08 *= w59;
  /* #966: @7 = (@7*@10) */
  w07 *= w10;
  /* #967: @8 = (@8+@7) */
  w08 += w07;
  /* #968: @6 = (@6*@11) */
  w06 *= w11;
  /* #969: @8 = (@8+@6) */
  w08 += w06;
  /* #970: @5 = (@5*@13) */
  w05 *= w13;
  /* #971: @8 = (@8+@5) */
  w08 += w05;
  /* #972: (@30[0] += @8) */
  for (rr=w30+0, cs=(&w08); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #973: @8 = dot(@27, @30) */
  w08 = casadi_dot(4, w27, w30);
  /* #974: @57 = (@57/@9) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w09;
  /* #975: @61 = (@61*@50) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) *= w50;
  /* #976: @57 = (@57-@61) */
  for (i=0, rr=w57, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #977: @57 = (-@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) *rr++ = (- *cs++ );
  /* #978: @5 = dot(@57, @29) */
  w05 = casadi_dot(4, w57, w29);
  /* #979: @8 = (@8+@5) */
  w08 += w05;
  /* #980: @8 = (@8/@9) */
  w08 /= w09;
  /* #981: @40 = (@40*@50) */
  w40 *= w50;
  /* #982: @8 = (@8-@40) */
  w08 -= w40;
  /* #983: @28 = (@28*@8) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) *= w08;
  /* #984: @42 = (@42*@52) */
  w42 *= w52;
  /* #985: @57 = dense(@42) */
  casadi_densify((&w42), casadi_s20, w57, 0);
  /* #986: @28 = (@28+@57) */
  for (i=0, rr=w28, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #987: (@19[3:7] += @28) */
  for (rr=w19+3, cs=w28; rr!=w19+7; rr+=1) *rr += *cs++;
  /* #988: {@42, @52, @8, @40, @5, @13, @6, @11, @7, @10, @59} = vertsplit(@19) */
  w42 = w19[0];
  w52 = w19[1];
  w08 = w19[2];
  w40 = w19[3];
  w05 = w19[4];
  w13 = w19[5];
  w06 = w19[6];
  w11 = w19[7];
  w07 = w19[8];
  w10 = w19[9];
  w59 = w19[10];
  /* #989: @30 = (@30/@9) */
  for (i=0, rr=w30; i<4; ++i) (*rr++) /= w09;
  /* #990: @25 = (@25*@50) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) *= w50;
  /* #991: @30 = (@30-@25) */
  for (i=0, rr=w30, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #992: {@50, @9, @2, @71} = vertsplit(@30) */
  w50 = w30[0];
  w09 = w30[1];
  w02 = w30[2];
  w71 = w30[3];
  /* #993: @50 = (@50+@40) */
  w50 += w40;
  /* #994: @5 = (@5-@9) */
  w05 -= w09;
  /* #995: @13 = (@13-@2) */
  w13 -= w02;
  /* #996: @6 = (@6-@71) */
  w06 -= w71;
  /* #997: @17 = vertcat(@51, @49, @47, @48, @42, @52, @8, @50, @5, @13, @6, @11, @7, @10, @59) */
  rr=w17;
  *rr++ = w51;
  *rr++ = w49;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w42;
  *rr++ = w52;
  *rr++ = w08;
  *rr++ = w50;
  *rr++ = w05;
  *rr++ = w13;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w59;
  /* #998: @77 = @17[:14:7;:4] */
  for (rr=w77, cs=w17+0; cs!=w17+14; cs+=7) for (ct=cs+0; ct!=cs+4; ct+=1) *rr++ = *ct;
  /* #999: (@53[:50:25;12:16] = @77) */
  for (rr=w53+0, cs=w77; rr!=w53+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *cs++;
  /* #1000: (@53[:50:25;3:19:4] = @77) */
  for (rr=w53+0, cs=w77; rr!=w53+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *cs++;
  /* #1001: @78 = @53' */
  casadi_trans(w53,casadi_s21, w78, casadi_s21, iw);
  /* #1002: output[2][0] = @78 */
  casadi_copy(w78, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s22;
    case 1: return casadi_s23;
    case 2: return casadi_s24;
    case 3: return casadi_s25;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s26;
    case 1: return casadi_s25;
    case 2: return casadi_s21;
    case 3: return casadi_s27;
    case 4: return casadi_s28;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 20;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 316;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 20*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 316*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
