/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {15, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* Drone_ode_cost_ext_cost_0_fun:(i0[11],i1[4],i2[0],i3[15])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w19=w+38, *w20=w+49, *w21=w+52, *w22=w+61;
  casadi_real *w23=w+64, *w24=w+68, *w25=w+72, *w26=w+76;
  const casadi_real *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #20: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #21: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #22: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #23: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #24: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #25: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #26: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #27: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #28: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #29: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #30: @19 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #31: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #32: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #34: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #35: @2 = 1.1 */
  w02 = 1.1000000000000001e+00;
  /* #36: (@21[0] = @2) */
  for (rr=w21+0, cs=(&w02); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #37: (@21[4] = @2) */
  for (rr=w21+4, cs=(&w02); rr!=w21+5; rr+=1) *rr = *cs++;
  /* #38: (@21[8] = @2) */
  for (rr=w21+8, cs=(&w02); rr!=w21+9; rr+=1) *rr = *cs++;
  /* #39: @22 = mac(@20,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@22,@18,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #42: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #43: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #44: @13 = input[1][2] */
  w13 = arg[1] ? arg[1][2] : 0;
  /* #45: @14 = input[1][3] */
  w14 = arg[1] ? arg[1][3] : 0;
  /* #46: @24 = vertcat(@3, @4, @13, @14) */
  rr=w24;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w13;
  *rr++ = w14;
  /* #47: @25 = @24' */
  casadi_copy(w24, 4, w25);
  /* #48: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #49: @3 = 1 */
  w03 = 1.;
  /* #50: (@26[0] = @3) */
  for (rr=w26+0, cs=(&w03); rr!=w26+1; rr+=1) *rr = *cs++;
  /* #51: (@26[5] = @3) */
  for (rr=w26+5, cs=(&w03); rr!=w26+6; rr+=1) *rr = *cs++;
  /* #52: (@26[10] = @3) */
  for (rr=w26+10, cs=(&w03); rr!=w26+11; rr+=1) *rr = *cs++;
  /* #53: (@26[15] = @3) */
  for (rr=w26+15, cs=(&w03); rr!=w26+16; rr+=1) *rr = *cs++;
  /* #54: @23 = mac(@25,@26,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w26+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #55: @3 = mac(@23,@24,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w24+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #56: @2 = (@2+@3) */
  w02 += w03;
  /* #57: @10 = (-@10) */
  w10 = (- w10 );
  /* #58: @11 = (-@11) */
  w11 = (- w11 );
  /* #59: @12 = (-@12) */
  w12 = (- w12 );
  /* #60: @23 = vertcat(@9, @10, @11, @12) */
  rr=w23;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #61: @24 = @19[3:7] */
  for (rr=w24, cs=w19+3; cs!=w19+7; cs+=1) *rr++ = *cs;
  /* #62: @9 = ||@24||_F */
  w09 = casadi_norm_2(4, w24);
  /* #63: @23 = (@23/@9) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) /= w09;
  /* #64: @9 = @23[0] */
  for (rr=(&w09), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #65: @10 = (@9*@5) */
  w10  = (w09*w05);
  /* #66: @11 = @23[1] */
  for (rr=(&w11), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #67: @12 = (@11*@6) */
  w12  = (w11*w06);
  /* #68: @10 = (@10-@12) */
  w10 -= w12;
  /* #69: @12 = @23[2] */
  for (rr=(&w12), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #70: @3 = (@12*@7) */
  w03  = (w12*w07);
  /* #71: @10 = (@10-@3) */
  w10 -= w03;
  /* #72: @3 = @23[3] */
  for (rr=(&w03), cs=w23+3; cs!=w23+4; cs+=1) *rr++ = *cs;
  /* #73: @4 = (@3*@8) */
  w04  = (w03*w08);
  /* #74: @10 = (@10-@4) */
  w10 -= w04;
  /* #75: @4 = (@10<@0) */
  w04  = (w10<w00);
  /* #76: @13 = (@9*@6) */
  w13  = (w09*w06);
  /* #77: @14 = (@11*@5) */
  w14  = (w11*w05);
  /* #78: @13 = (@13+@14) */
  w13 += w14;
  /* #79: @14 = (@12*@8) */
  w14  = (w12*w08);
  /* #80: @13 = (@13+@14) */
  w13 += w14;
  /* #81: @14 = (@3*@7) */
  w14  = (w03*w07);
  /* #82: @13 = (@13-@14) */
  w13 -= w14;
  /* #83: @14 = (@9*@7) */
  w14  = (w09*w07);
  /* #84: @15 = (@11*@8) */
  w15  = (w11*w08);
  /* #85: @14 = (@14-@15) */
  w14 -= w15;
  /* #86: @15 = (@12*@5) */
  w15  = (w12*w05);
  /* #87: @14 = (@14+@15) */
  w14 += w15;
  /* #88: @15 = (@3*@6) */
  w15  = (w03*w06);
  /* #89: @14 = (@14+@15) */
  w14 += w15;
  /* #90: @9 = (@9*@8) */
  w09 *= w08;
  /* #91: @11 = (@11*@7) */
  w11 *= w07;
  /* #92: @9 = (@9+@11) */
  w09 += w11;
  /* #93: @12 = (@12*@6) */
  w12 *= w06;
  /* #94: @9 = (@9-@12) */
  w09 -= w12;
  /* #95: @3 = (@3*@5) */
  w03 *= w05;
  /* #96: @9 = (@9+@3) */
  w09 += w03;
  /* #97: @23 = vertcat(@10, @13, @14, @9) */
  rr=w23;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w09;
  /* #98: @24 = (-@23) */
  for (i=0, rr=w24, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #99: @24 = (@4?@24:0) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) (*rr++)  = (w04?cs[i]:0);
  /* #100: @4 = (!@4) */
  w04 = (! w04 );
  /* #101: @23 = (@4?@23:0) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w04?cs[i]:0);
  /* #102: @24 = (@24+@23) */
  for (i=0, rr=w24, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #103: @22 = @24[1:4] */
  for (rr=w22, cs=w24+1; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #104: @18 = (2.*@22) */
  for (i=0, rr=w18, cs=w22; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #105: @4 = ||@22||_F */
  w04 = casadi_norm_2(3, w22);
  /* #106: @10 = @24[0] */
  for (rr=(&w10), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #107: @10 = atan2(@4,@10) */
  w10  = atan2(w04,w10);
  /* #108: @18 = (@18*@10) */
  for (i=0, rr=w18; i<3; ++i) (*rr++) *= w10;
  /* #109: @18 = (@18/@4) */
  for (i=0, rr=w18; i<3; ++i) (*rr++) /= w04;
  /* #110: @22 = @18' */
  casadi_copy(w18, 3, w22);
  /* #111: @1 = mac(@22,@21,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #112: @0 = mac(@1,@18,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #113: @2 = (@2+@0) */
  w02 += w00;
  /* #114: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 92;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 92*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
