/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {15, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

/* Drone_ode_cost_ext_cost_e_fun_jac:(i0[11],i1[0],i2[0],i3[15])->(o0,o1[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w19=w+38, *w20=w+49, *w21=w+52, *w22=w+61;
  casadi_real *w23=w+64, *w24=w+68, *w25=w+72, *w26=w+76, *w27=w+80, *w28=w+83, *w29=w+86, *w30=w+89, *w31=w+92, *w32=w+101, *w33=w+104;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #20: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #21: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #22: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #23: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #24: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #25: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #26: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #27: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #28: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #29: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #30: @19 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #31: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #32: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #34: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #35: @2 = 1.1 */
  w02 = 1.1000000000000001e+00;
  /* #36: (@21[0] = @2) */
  for (rr=w21+0, cs=(&w02); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #37: (@21[4] = @2) */
  for (rr=w21+4, cs=(&w02); rr!=w21+5; rr+=1) *rr = *cs++;
  /* #38: (@21[8] = @2) */
  for (rr=w21+8, cs=(&w02); rr!=w21+9; rr+=1) *rr = *cs++;
  /* #39: @22 = mac(@20,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@22,@18,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @10 = (-@10) */
  w10 = (- w10 );
  /* #42: @11 = (-@11) */
  w11 = (- w11 );
  /* #43: @12 = (-@12) */
  w12 = (- w12 );
  /* #44: @23 = vertcat(@9, @10, @11, @12) */
  rr=w23;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #45: @24 = @19[3:7] */
  for (rr=w24, cs=w19+3; cs!=w19+7; cs+=1) *rr++ = *cs;
  /* #46: @9 = ||@24||_F */
  w09 = casadi_norm_2(4, w24);
  /* #47: @23 = (@23/@9) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) /= w09;
  /* #48: @10 = @23[0] */
  for (rr=(&w10), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #49: @11 = (@10*@5) */
  w11  = (w10*w05);
  /* #50: @12 = @23[1] */
  for (rr=(&w12), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #51: @3 = (@12*@6) */
  w03  = (w12*w06);
  /* #52: @11 = (@11-@3) */
  w11 -= w03;
  /* #53: @3 = @23[2] */
  for (rr=(&w03), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #54: @4 = (@3*@7) */
  w04  = (w03*w07);
  /* #55: @11 = (@11-@4) */
  w11 -= w04;
  /* #56: @4 = @23[3] */
  for (rr=(&w04), cs=w23+3; cs!=w23+4; cs+=1) *rr++ = *cs;
  /* #57: @13 = (@4*@8) */
  w13  = (w04*w08);
  /* #58: @11 = (@11-@13) */
  w11 -= w13;
  /* #59: @13 = (@11<@0) */
  w13  = (w11<w00);
  /* #60: @14 = (@10*@6) */
  w14  = (w10*w06);
  /* #61: @15 = (@12*@5) */
  w15  = (w12*w05);
  /* #62: @14 = (@14+@15) */
  w14 += w15;
  /* #63: @15 = (@3*@8) */
  w15  = (w03*w08);
  /* #64: @14 = (@14+@15) */
  w14 += w15;
  /* #65: @15 = (@4*@7) */
  w15  = (w04*w07);
  /* #66: @14 = (@14-@15) */
  w14 -= w15;
  /* #67: @15 = (@10*@7) */
  w15  = (w10*w07);
  /* #68: @16 = (@12*@8) */
  w16  = (w12*w08);
  /* #69: @15 = (@15-@16) */
  w15 -= w16;
  /* #70: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #71: @15 = (@15+@16) */
  w15 += w16;
  /* #72: @16 = (@4*@6) */
  w16  = (w04*w06);
  /* #73: @15 = (@15+@16) */
  w15 += w16;
  /* #74: @10 = (@10*@8) */
  w10 *= w08;
  /* #75: @12 = (@12*@7) */
  w12 *= w07;
  /* #76: @10 = (@10+@12) */
  w10 += w12;
  /* #77: @3 = (@3*@6) */
  w03 *= w06;
  /* #78: @10 = (@10-@3) */
  w10 -= w03;
  /* #79: @4 = (@4*@5) */
  w04 *= w05;
  /* #80: @10 = (@10+@4) */
  w10 += w04;
  /* #81: @25 = vertcat(@11, @14, @15, @10) */
  rr=w25;
  *rr++ = w11;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w10;
  /* #82: @26 = (-@25) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) *rr++ = (- *cs++ );
  /* #83: @26 = (@13?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #84: @11 = (!@13) */
  w11 = (! w13 );
  /* #85: @25 = (@11?@25:0) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #86: @26 = (@26+@25) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #87: @18 = @26[1:4] */
  for (rr=w18, cs=w26+1; cs!=w26+4; cs+=1) *rr++ = *cs;
  /* #88: @27 = (2.*@18) */
  for (i=0, rr=w27, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #89: @14 = ||@18||_F */
  w14 = casadi_norm_2(3, w18);
  /* #90: @15 = @26[0] */
  for (rr=(&w15), cs=w26+0; cs!=w26+1; cs+=1) *rr++ = *cs;
  /* #91: @10 = atan2(@14,@15) */
  w10  = atan2(w14,w15);
  /* #92: @28 = (@27*@10) */
  for (i=0, rr=w28, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w10);
  /* #93: @28 = (@28/@14) */
  for (i=0, rr=w28; i<3; ++i) (*rr++) /= w14;
  /* #94: @29 = @28' */
  casadi_copy(w28, 3, w29);
  /* #95: @30 = mac(@29,@21,@1) */
  casadi_copy(w01, 3, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #96: @0 = mac(@30,@28,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #97: @2 = (@2+@0) */
  w02 += w00;
  /* #98: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #99: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #100: @23 = (@23/@9) */
  for (i=0, rr=w23; i<4; ++i) (*rr++) /= w09;
  /* #101: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #102: @26 = zeros(4x1) */
  casadi_clear(w26, 4);
  /* #103: @2 = sq(@14) */
  w02 = casadi_sq( w14 );
  /* #104: @0 = sq(@15) */
  w00 = casadi_sq( w15 );
  /* #105: @2 = (@2+@0) */
  w02 += w00;
  /* #106: @0 = (@14/@2) */
  w00  = (w14/w02);
  /* #107: @30 = @30' */
  /* #108: @31 = @21' */
  for (i=0, rr=w31, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #109: @32 = mac(@29,@31,@1) */
  casadi_copy(w01, 3, w32);
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w29+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #110: @32 = @32' */
  /* #111: @30 = (@30+@32) */
  for (i=0, rr=w30, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #112: @32 = (@30/@14) */
  for (i=0, rr=w32, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #113: @4 = dot(@27, @32) */
  w04 = casadi_dot(3, w27, w32);
  /* #114: @0 = (@0*@4) */
  w00 *= w04;
  /* #115: @0 = (-@0) */
  w00 = (- w00 );
  /* #116: @25 = @26; (@25[0] += @0) */
  casadi_copy(w26, 4, w25);
  for (rr=w25+0, cs=(&w00); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #117: @28 = (@28/@14) */
  for (i=0, rr=w28; i<3; ++i) (*rr++) /= w14;
  /* #118: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #119: @0 = dot(@28, @30) */
  w00 = casadi_dot(3, w28, w30);
  /* #120: @15 = (@15/@2) */
  w15 /= w02;
  /* #121: @15 = (@15*@4) */
  w15 *= w04;
  /* #122: @0 = (@0+@15) */
  w00 += w15;
  /* #123: @0 = (@0/@14) */
  w00 /= w14;
  /* #124: @18 = (@0*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #125: @32 = (@10*@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #126: @32 = (2.*@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #127: @18 = (@18+@32) */
  for (i=0, rr=w18, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #128: (@25[1:4] += @18) */
  for (rr=w25+1, cs=w18; rr!=w25+4; rr+=1) *rr += *cs++;
  /* #129: @33 = (@11?@25:0) */
  for (i=0, rr=w33, cs=w25; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #130: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) *rr++ = (- *cs++ );
  /* #131: @25 = (@13?@25:0) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #132: @33 = (@33+@25) */
  for (i=0, rr=w33, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #133: {@13, @11, @10, @0} = vertsplit(@33) */
  w13 = w33[0];
  w11 = w33[1];
  w10 = w33[2];
  w00 = w33[3];
  /* #134: @14 = (@5*@0) */
  w14  = (w05*w00);
  /* #135: @15 = (@6*@10) */
  w15  = (w06*w10);
  /* #136: @14 = (@14+@15) */
  w14 += w15;
  /* #137: @15 = (@7*@11) */
  w15  = (w07*w11);
  /* #138: @14 = (@14-@15) */
  w14 -= w15;
  /* #139: @15 = (@8*@13) */
  w15  = (w08*w13);
  /* #140: @14 = (@14-@15) */
  w14 -= w15;
  /* #141: (@26[3] += @14) */
  for (rr=w26+3, cs=(&w14); rr!=w26+4; rr+=1) *rr += *cs++;
  /* #142: @14 = (@5*@10) */
  w14  = (w05*w10);
  /* #143: @15 = (@6*@0) */
  w15  = (w06*w00);
  /* #144: @14 = (@14-@15) */
  w14 -= w15;
  /* #145: @15 = (@8*@11) */
  w15  = (w08*w11);
  /* #146: @14 = (@14+@15) */
  w14 += w15;
  /* #147: @15 = (@7*@13) */
  w15  = (w07*w13);
  /* #148: @14 = (@14-@15) */
  w14 -= w15;
  /* #149: (@26[2] += @14) */
  for (rr=w26+2, cs=(&w14); rr!=w26+3; rr+=1) *rr += *cs++;
  /* #150: @14 = (@7*@0) */
  w14  = (w07*w00);
  /* #151: @15 = (@8*@10) */
  w15  = (w08*w10);
  /* #152: @14 = (@14-@15) */
  w14 -= w15;
  /* #153: @15 = (@5*@11) */
  w15  = (w05*w11);
  /* #154: @14 = (@14+@15) */
  w14 += w15;
  /* #155: @15 = (@6*@13) */
  w15  = (w06*w13);
  /* #156: @14 = (@14-@15) */
  w14 -= w15;
  /* #157: (@26[1] += @14) */
  for (rr=w26+1, cs=(&w14); rr!=w26+2; rr+=1) *rr += *cs++;
  /* #158: @8 = (@8*@0) */
  w08 *= w00;
  /* #159: @7 = (@7*@10) */
  w07 *= w10;
  /* #160: @8 = (@8+@7) */
  w08 += w07;
  /* #161: @6 = (@6*@11) */
  w06 *= w11;
  /* #162: @8 = (@8+@6) */
  w08 += w06;
  /* #163: @5 = (@5*@13) */
  w05 *= w13;
  /* #164: @8 = (@8+@5) */
  w08 += w05;
  /* #165: (@26[0] += @8) */
  for (rr=w26+0, cs=(&w08); rr!=w26+1; rr+=1) *rr += *cs++;
  /* #166: @8 = dot(@23, @26) */
  w08 = casadi_dot(4, w23, w26);
  /* #167: @8 = (@8/@9) */
  w08 /= w09;
  /* #168: @24 = (@8*@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) (*rr++)  = (w08*(*cs++));
  /* #169: (@19[3:7] += @24) */
  for (rr=w19+3, cs=w24; rr!=w19+7; rr+=1) *rr += *cs++;
  /* #170: @22 = @22' */
  /* #171: @1 = mac(@20,@31,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #172: @1 = @1' */
  /* #173: @22 = (@22+@1) */
  for (i=0, rr=w22, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #174: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #175: (@19[:3] += @22) */
  for (rr=w19+0, cs=w22; rr!=w19+3; rr+=1) *rr += *cs++;
  /* #176: {@8, @5, @13, @6, @11, @7, @10, @0, @14, @15, @4} = vertsplit(@19) */
  w08 = w19[0];
  w05 = w19[1];
  w13 = w19[2];
  w06 = w19[3];
  w11 = w19[4];
  w07 = w19[5];
  w10 = w19[6];
  w00 = w19[7];
  w14 = w19[8];
  w15 = w19[9];
  w04 = w19[10];
  /* #177: output[1][0] = @8 */
  if (res[1]) res[1][0] = w08;
  /* #178: output[1][1] = @5 */
  if (res[1]) res[1][1] = w05;
  /* #179: output[1][2] = @13 */
  if (res[1]) res[1][2] = w13;
  /* #180: @26 = (@26/@9) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w09;
  /* #181: {@9, @13, @5, @8} = vertsplit(@26) */
  w09 = w26[0];
  w13 = w26[1];
  w05 = w26[2];
  w08 = w26[3];
  /* #182: @9 = (@9+@6) */
  w09 += w06;
  /* #183: output[1][3] = @9 */
  if (res[1]) res[1][3] = w09;
  /* #184: @11 = (@11-@13) */
  w11 -= w13;
  /* #185: output[1][4] = @11 */
  if (res[1]) res[1][4] = w11;
  /* #186: @7 = (@7-@5) */
  w07 -= w05;
  /* #187: output[1][5] = @7 */
  if (res[1]) res[1][5] = w07;
  /* #188: @10 = (@10-@8) */
  w10 -= w08;
  /* #189: output[1][6] = @10 */
  if (res[1]) res[1][6] = w10;
  /* #190: output[1][7] = @0 */
  if (res[1]) res[1][7] = w00;
  /* #191: output[1][8] = @14 */
  if (res[1]) res[1][8] = w14;
  /* #192: output[1][9] = @15 */
  if (res[1]) res[1][9] = w15;
  /* #193: output[1][10] = @4 */
  if (res[1]) res[1][10] = w04;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 108;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 108*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
