/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {15, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* Drone_ode_cost_ext_cost_0_fun_jac:(i0[11],i1[4],i2[0],i3[15])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+2, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+20, *w18=w+35, *w19=w+38, *w20=w+49, *w21=w+52, *w22=w+61;
  casadi_real *w23=w+64, *w24=w+68, *w25=w+72, *w26=w+76, *w27=w+92, *w28=w+96, *w29=w+100, *w30=w+104, *w31=w+108, *w32=w+111, *w33=w+114, *w34=w+117;
  casadi_real *w35=w+120, *w36=w+136, *w37=w+145;
  const casadi_real *cr, *cs, *ct;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w01, 3);
  /* #2: @2 = input[3][0] */
  w02 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w03 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w04 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w05 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w06 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w07 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w08 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w09 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #20: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #21: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #22: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #23: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #24: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #25: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #26: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #27: @14 = input[0][8] */
  w14 = arg[0] ? arg[0][8] : 0;
  /* #28: @15 = input[0][9] */
  w15 = arg[0] ? arg[0][9] : 0;
  /* #29: @16 = input[0][10] */
  w16 = arg[0] ? arg[0][10] : 0;
  /* #30: @19 = vertcat(@2, @3, @4, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w19;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #31: @20 = @19[:3] */
  for (rr=w20, cs=w19+0; cs!=w19+3; cs+=1) *rr++ = *cs;
  /* #32: @18 = (@18-@20) */
  for (i=0, rr=w18, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #33: @20 = @18' */
  casadi_copy(w18, 3, w20);
  /* #34: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #35: @2 = 1.1 */
  w02 = 1.1000000000000001e+00;
  /* #36: (@21[0] = @2) */
  for (rr=w21+0, cs=(&w02); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #37: (@21[4] = @2) */
  for (rr=w21+4, cs=(&w02); rr!=w21+5; rr+=1) *rr = *cs++;
  /* #38: (@21[8] = @2) */
  for (rr=w21+8, cs=(&w02); rr!=w21+9; rr+=1) *rr = *cs++;
  /* #39: @22 = mac(@20,@21,@1) */
  casadi_copy(w01, 3, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #40: @2 = mac(@22,@18,@0) */
  casadi_copy((&w00), 1, (&w02));
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w22+j, ct=w18+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #41: @23 = zeros(1x4) */
  casadi_clear(w23, 4);
  /* #42: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #43: @4 = input[1][1] */
  w04 = arg[1] ? arg[1][1] : 0;
  /* #44: @13 = input[1][2] */
  w13 = arg[1] ? arg[1][2] : 0;
  /* #45: @14 = input[1][3] */
  w14 = arg[1] ? arg[1][3] : 0;
  /* #46: @24 = vertcat(@3, @4, @13, @14) */
  rr=w24;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w13;
  *rr++ = w14;
  /* #47: @25 = @24' */
  casadi_copy(w24, 4, w25);
  /* #48: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #49: @3 = 1 */
  w03 = 1.;
  /* #50: (@26[0] = @3) */
  for (rr=w26+0, cs=(&w03); rr!=w26+1; rr+=1) *rr = *cs++;
  /* #51: (@26[5] = @3) */
  for (rr=w26+5, cs=(&w03); rr!=w26+6; rr+=1) *rr = *cs++;
  /* #52: (@26[10] = @3) */
  for (rr=w26+10, cs=(&w03); rr!=w26+11; rr+=1) *rr = *cs++;
  /* #53: (@26[15] = @3) */
  for (rr=w26+15, cs=(&w03); rr!=w26+16; rr+=1) *rr = *cs++;
  /* #54: @27 = mac(@25,@26,@23) */
  casadi_copy(w23, 4, w27);
  for (i=0, rr=w27; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w26+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #55: @3 = mac(@27,@24,@0) */
  casadi_copy((&w00), 1, (&w03));
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w27+j, ct=w24+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #56: @2 = (@2+@3) */
  w02 += w03;
  /* #57: @10 = (-@10) */
  w10 = (- w10 );
  /* #58: @11 = (-@11) */
  w11 = (- w11 );
  /* #59: @12 = (-@12) */
  w12 = (- w12 );
  /* #60: @24 = vertcat(@9, @10, @11, @12) */
  rr=w24;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #61: @28 = @19[3:7] */
  for (rr=w28, cs=w19+3; cs!=w19+7; cs+=1) *rr++ = *cs;
  /* #62: @9 = ||@28||_F */
  w09 = casadi_norm_2(4, w28);
  /* #63: @24 = (@24/@9) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w09;
  /* #64: @10 = @24[0] */
  for (rr=(&w10), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #65: @11 = (@10*@5) */
  w11  = (w10*w05);
  /* #66: @12 = @24[1] */
  for (rr=(&w12), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #67: @3 = (@12*@6) */
  w03  = (w12*w06);
  /* #68: @11 = (@11-@3) */
  w11 -= w03;
  /* #69: @3 = @24[2] */
  for (rr=(&w03), cs=w24+2; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #70: @4 = (@3*@7) */
  w04  = (w03*w07);
  /* #71: @11 = (@11-@4) */
  w11 -= w04;
  /* #72: @4 = @24[3] */
  for (rr=(&w04), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #73: @13 = (@4*@8) */
  w13  = (w04*w08);
  /* #74: @11 = (@11-@13) */
  w11 -= w13;
  /* #75: @13 = (@11<@0) */
  w13  = (w11<w00);
  /* #76: @14 = (@10*@6) */
  w14  = (w10*w06);
  /* #77: @15 = (@12*@5) */
  w15  = (w12*w05);
  /* #78: @14 = (@14+@15) */
  w14 += w15;
  /* #79: @15 = (@3*@8) */
  w15  = (w03*w08);
  /* #80: @14 = (@14+@15) */
  w14 += w15;
  /* #81: @15 = (@4*@7) */
  w15  = (w04*w07);
  /* #82: @14 = (@14-@15) */
  w14 -= w15;
  /* #83: @15 = (@10*@7) */
  w15  = (w10*w07);
  /* #84: @16 = (@12*@8) */
  w16  = (w12*w08);
  /* #85: @15 = (@15-@16) */
  w15 -= w16;
  /* #86: @16 = (@3*@5) */
  w16  = (w03*w05);
  /* #87: @15 = (@15+@16) */
  w15 += w16;
  /* #88: @16 = (@4*@6) */
  w16  = (w04*w06);
  /* #89: @15 = (@15+@16) */
  w15 += w16;
  /* #90: @10 = (@10*@8) */
  w10 *= w08;
  /* #91: @12 = (@12*@7) */
  w12 *= w07;
  /* #92: @10 = (@10+@12) */
  w10 += w12;
  /* #93: @3 = (@3*@6) */
  w03 *= w06;
  /* #94: @10 = (@10-@3) */
  w10 -= w03;
  /* #95: @4 = (@4*@5) */
  w04 *= w05;
  /* #96: @10 = (@10+@4) */
  w10 += w04;
  /* #97: @29 = vertcat(@11, @14, @15, @10) */
  rr=w29;
  *rr++ = w11;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w10;
  /* #98: @30 = (-@29) */
  for (i=0, rr=w30, cs=w29; i<4; ++i) *rr++ = (- *cs++ );
  /* #99: @30 = (@13?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #100: @11 = (!@13) */
  w11 = (! w13 );
  /* #101: @29 = (@11?@29:0) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #102: @30 = (@30+@29) */
  for (i=0, rr=w30, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #103: @18 = @30[1:4] */
  for (rr=w18, cs=w30+1; cs!=w30+4; cs+=1) *rr++ = *cs;
  /* #104: @31 = (2.*@18) */
  for (i=0, rr=w31, cs=w18; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #105: @14 = ||@18||_F */
  w14 = casadi_norm_2(3, w18);
  /* #106: @15 = @30[0] */
  for (rr=(&w15), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #107: @10 = atan2(@14,@15) */
  w10  = atan2(w14,w15);
  /* #108: @32 = (@31*@10) */
  for (i=0, rr=w32, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w10);
  /* #109: @32 = (@32/@14) */
  for (i=0, rr=w32; i<3; ++i) (*rr++) /= w14;
  /* #110: @33 = @32' */
  casadi_copy(w32, 3, w33);
  /* #111: @34 = mac(@33,@21,@1) */
  casadi_copy(w01, 3, w34);
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w21+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #112: @0 = mac(@34,@32,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w32+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #113: @2 = (@2+@0) */
  w02 += w00;
  /* #114: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #115: @27 = @27' */
  /* #116: @35 = @26' */
  for (i=0, rr=w35, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #117: @23 = mac(@25,@35,@23) */
  for (i=0, rr=w23; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w35+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #118: @23 = @23' */
  /* #119: @27 = (@27+@23) */
  for (i=0, rr=w27, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #120: {@2, @0, @4, @3} = vertsplit(@27) */
  w02 = w27[0];
  w00 = w27[1];
  w04 = w27[2];
  w03 = w27[3];
  /* #121: output[1][0] = @2 */
  if (res[1]) res[1][0] = w02;
  /* #122: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #123: output[1][2] = @4 */
  if (res[1]) res[1][2] = w04;
  /* #124: output[1][3] = @3 */
  if (res[1]) res[1][3] = w03;
  /* #125: @19 = zeros(11x1) */
  casadi_clear(w19, 11);
  /* #126: @24 = (@24/@9) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w09;
  /* #127: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #128: @27 = zeros(4x1) */
  casadi_clear(w27, 4);
  /* #129: @3 = sq(@14) */
  w03 = casadi_sq( w14 );
  /* #130: @4 = sq(@15) */
  w04 = casadi_sq( w15 );
  /* #131: @3 = (@3+@4) */
  w03 += w04;
  /* #132: @4 = (@14/@3) */
  w04  = (w14/w03);
  /* #133: @34 = @34' */
  /* #134: @36 = @21' */
  for (i=0, rr=w36, cs=w21; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #135: @37 = mac(@33,@36,@1) */
  casadi_copy(w01, 3, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w33+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #136: @37 = @37' */
  /* #137: @34 = (@34+@37) */
  for (i=0, rr=w34, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #138: @37 = (@34/@14) */
  for (i=0, rr=w37, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #139: @0 = dot(@31, @37) */
  w00 = casadi_dot(3, w31, w37);
  /* #140: @4 = (@4*@0) */
  w04 *= w00;
  /* #141: @4 = (-@4) */
  w04 = (- w04 );
  /* #142: @23 = @27; (@23[0] += @4) */
  casadi_copy(w27, 4, w23);
  for (rr=w23+0, cs=(&w04); rr!=w23+1; rr+=1) *rr += *cs++;
  /* #143: @32 = (@32/@14) */
  for (i=0, rr=w32; i<3; ++i) (*rr++) /= w14;
  /* #144: @32 = (-@32) */
  for (i=0, rr=w32, cs=w32; i<3; ++i) *rr++ = (- *cs++ );
  /* #145: @4 = dot(@32, @34) */
  w04 = casadi_dot(3, w32, w34);
  /* #146: @15 = (@15/@3) */
  w15 /= w03;
  /* #147: @15 = (@15*@0) */
  w15 *= w00;
  /* #148: @4 = (@4+@15) */
  w04 += w15;
  /* #149: @4 = (@4/@14) */
  w04 /= w14;
  /* #150: @18 = (@4*@18) */
  for (i=0, rr=w18, cs=w18; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #151: @37 = (@10*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #152: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #153: @18 = (@18+@37) */
  for (i=0, rr=w18, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #154: (@23[1:4] += @18) */
  for (rr=w23+1, cs=w18; rr!=w23+4; rr+=1) *rr += *cs++;
  /* #155: @25 = (@11?@23:0) */
  for (i=0, rr=w25, cs=w23; i<4; ++i) (*rr++)  = (w11?cs[i]:0);
  /* #156: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) *rr++ = (- *cs++ );
  /* #157: @23 = (@13?@23:0) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w13?cs[i]:0);
  /* #158: @25 = (@25+@23) */
  for (i=0, rr=w25, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #159: {@13, @11, @10, @4} = vertsplit(@25) */
  w13 = w25[0];
  w11 = w25[1];
  w10 = w25[2];
  w04 = w25[3];
  /* #160: @14 = (@5*@4) */
  w14  = (w05*w04);
  /* #161: @15 = (@6*@10) */
  w15  = (w06*w10);
  /* #162: @14 = (@14+@15) */
  w14 += w15;
  /* #163: @15 = (@7*@11) */
  w15  = (w07*w11);
  /* #164: @14 = (@14-@15) */
  w14 -= w15;
  /* #165: @15 = (@8*@13) */
  w15  = (w08*w13);
  /* #166: @14 = (@14-@15) */
  w14 -= w15;
  /* #167: (@27[3] += @14) */
  for (rr=w27+3, cs=(&w14); rr!=w27+4; rr+=1) *rr += *cs++;
  /* #168: @14 = (@5*@10) */
  w14  = (w05*w10);
  /* #169: @15 = (@6*@4) */
  w15  = (w06*w04);
  /* #170: @14 = (@14-@15) */
  w14 -= w15;
  /* #171: @15 = (@8*@11) */
  w15  = (w08*w11);
  /* #172: @14 = (@14+@15) */
  w14 += w15;
  /* #173: @15 = (@7*@13) */
  w15  = (w07*w13);
  /* #174: @14 = (@14-@15) */
  w14 -= w15;
  /* #175: (@27[2] += @14) */
  for (rr=w27+2, cs=(&w14); rr!=w27+3; rr+=1) *rr += *cs++;
  /* #176: @14 = (@7*@4) */
  w14  = (w07*w04);
  /* #177: @15 = (@8*@10) */
  w15  = (w08*w10);
  /* #178: @14 = (@14-@15) */
  w14 -= w15;
  /* #179: @15 = (@5*@11) */
  w15  = (w05*w11);
  /* #180: @14 = (@14+@15) */
  w14 += w15;
  /* #181: @15 = (@6*@13) */
  w15  = (w06*w13);
  /* #182: @14 = (@14-@15) */
  w14 -= w15;
  /* #183: (@27[1] += @14) */
  for (rr=w27+1, cs=(&w14); rr!=w27+2; rr+=1) *rr += *cs++;
  /* #184: @8 = (@8*@4) */
  w08 *= w04;
  /* #185: @7 = (@7*@10) */
  w07 *= w10;
  /* #186: @8 = (@8+@7) */
  w08 += w07;
  /* #187: @6 = (@6*@11) */
  w06 *= w11;
  /* #188: @8 = (@8+@6) */
  w08 += w06;
  /* #189: @5 = (@5*@13) */
  w05 *= w13;
  /* #190: @8 = (@8+@5) */
  w08 += w05;
  /* #191: (@27[0] += @8) */
  for (rr=w27+0, cs=(&w08); rr!=w27+1; rr+=1) *rr += *cs++;
  /* #192: @8 = dot(@24, @27) */
  w08 = casadi_dot(4, w24, w27);
  /* #193: @8 = (@8/@9) */
  w08 /= w09;
  /* #194: @28 = (@8*@28) */
  for (i=0, rr=w28, cs=w28; i<4; ++i) (*rr++)  = (w08*(*cs++));
  /* #195: (@19[3:7] += @28) */
  for (rr=w19+3, cs=w28; rr!=w19+7; rr+=1) *rr += *cs++;
  /* #196: @22 = @22' */
  /* #197: @1 = mac(@20,@36,@1) */
  for (i=0, rr=w01; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #198: @1 = @1' */
  /* #199: @22 = (@22+@1) */
  for (i=0, rr=w22, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #200: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) *rr++ = (- *cs++ );
  /* #201: (@19[:3] += @22) */
  for (rr=w19+0, cs=w22; rr!=w19+3; rr+=1) *rr += *cs++;
  /* #202: {@8, @5, @13, @6, @11, @7, @10, @4, @14, @15, @0} = vertsplit(@19) */
  w08 = w19[0];
  w05 = w19[1];
  w13 = w19[2];
  w06 = w19[3];
  w11 = w19[4];
  w07 = w19[5];
  w10 = w19[6];
  w04 = w19[7];
  w14 = w19[8];
  w15 = w19[9];
  w00 = w19[10];
  /* #203: output[1][4] = @8 */
  if (res[1]) res[1][4] = w08;
  /* #204: output[1][5] = @5 */
  if (res[1]) res[1][5] = w05;
  /* #205: output[1][6] = @13 */
  if (res[1]) res[1][6] = w13;
  /* #206: @27 = (@27/@9) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w09;
  /* #207: {@9, @13, @5, @8} = vertsplit(@27) */
  w09 = w27[0];
  w13 = w27[1];
  w05 = w27[2];
  w08 = w27[3];
  /* #208: @9 = (@9+@6) */
  w09 += w06;
  /* #209: output[1][7] = @9 */
  if (res[1]) res[1][7] = w09;
  /* #210: @11 = (@11-@13) */
  w11 -= w13;
  /* #211: output[1][8] = @11 */
  if (res[1]) res[1][8] = w11;
  /* #212: @7 = (@7-@5) */
  w07 -= w05;
  /* #213: output[1][9] = @7 */
  if (res[1]) res[1][9] = w07;
  /* #214: @10 = (@10-@8) */
  w10 -= w08;
  /* #215: output[1][10] = @10 */
  if (res[1]) res[1][10] = w10;
  /* #216: output[1][11] = @4 */
  if (res[1]) res[1][11] = w04;
  /* #217: output[1][12] = @14 */
  if (res[1]) res[1][12] = w14;
  /* #218: output[1][13] = @15 */
  if (res[1]) res[1][13] = w15;
  /* #219: output[1][14] = @0 */
  if (res[1]) res[1][14] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 148;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 148*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
